/* Auto-generated from debug_quad.vert.msl -- do not edit by hand. */
static const char debug_quad_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_DebugVertUniforms\n"
    "{\n"
    "    float4 quad_bounds;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(constant type_DebugVertUniforms& DebugVertUniforms [[buffer(0)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    bool _39;\n"
    "    if (gl_VertexIndex != 1u)\n"
    "    {\n"
    "        _39 = gl_VertexIndex == 4u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _39 = true;\n"
    "    }\n"
    "    bool _44;\n"
    "    if (!_39)\n"
    "    {\n"
    "        _44 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _44 = true;\n"
    "    }\n"
    "    float _45 = float(_44);\n"
    "    bool _50;\n"
    "    if (gl_VertexIndex != 2u)\n"
    "    {\n"
    "        _50 = gl_VertexIndex == 3u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _50 = true;\n"
    "    }\n"
    "    bool _55;\n"
    "    if (!_50)\n"
    "    {\n"
    "        _55 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _55 = true;\n"
    "    }\n"
    "    float _56 = float(_55);\n"
    "    out.gl_Position = float4(mix(DebugVertUniforms.quad_bounds.x, DebugVertUniforms.quad_bounds.z, _45), mix(DebugVertUniforms.quad_bounds.y, DebugVertUniforms.quad_bounds.w, _56), 0.0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = float2(_45, 1.0 - _56);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int debug_quad_vert_msl_size = sizeof(debug_quad_vert_msl) - 1;
