/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4 cascade_splits;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float shadow_texel_size;\n"
    "    float shadow_bias;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], texture2d<float> shadow_map0 [[texture(0)]], texture2d<float> shadow_map1 [[texture(1)]], texture2d<float> shadow_map2 [[texture(2)]], sampler shadow_smp0 [[sampler(0)]], sampler shadow_smp1 [[sampler(1)]], sampler shadow_smp2 [[sampler(2)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _74 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _79 = fwidth(_74);\n"
    "    float2 _82 = float2(GridFragUniforms.line_width);\n"
    "    float2 _85 = float2(1.0) - smoothstep(_82, _82 + _79, abs(fract(_74 - float2(0.5)) - float2(0.5)));\n"
    "    float _99 = length(in.in_var_TEXCOORD0 - GridFragUniforms.eye_pos.xyz);\n"
    "    float3 _113 = mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_85.x, _85.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_79.x, _79.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, _99))));\n"
    "    float _400;\n"
    "    if (_99 < GridFragUniforms.cascade_splits.x)\n"
    "    {\n"
    "        float3 _124 = in.in_var_TEXCOORD1.xyz / float3(in.in_var_TEXCOORD1.w);\n"
    "        float2 _127 = (_124.xy * 0.5) + float2(0.5);\n"
    "        _127.y = 1.0 - _127.y;\n"
    "        float _143 = _124.z - GridFragUniforms.shadow_bias;\n"
    "        _400 = ((((((((float(shadow_map0.sample(shadow_smp0, (_127 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _143) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, _127).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) + float(shadow_map0.sample(shadow_smp0, (_127 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _143)) * 0.111111111938953399658203125;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _399;\n"
    "        if (_99 < GridFragUniforms.cascade_splits.y)\n"
    "        {\n"
    "            float3 _219 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "            float2 _222 = (_219.xy * 0.5) + float2(0.5);\n"
    "            _222.y = 1.0 - _222.y;\n"
    "            float _238 = _219.z - GridFragUniforms.shadow_bias;\n"
    "            _399 = ((((((((float(shadow_map1.sample(shadow_smp1, (_222 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _238) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, _222).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) + float(shadow_map1.sample(shadow_smp1, (_222 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _238)) * 0.111111111938953399658203125;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _398;\n"
    "            if (_99 < GridFragUniforms.cascade_splits.z)\n"
    "            {\n"
    "                float3 _313 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "                float2 _316 = (_313.xy * 0.5) + float2(0.5);\n"
    "                _316.y = 1.0 - _316.y;\n"
    "                float _332 = _313.z - GridFragUniforms.shadow_bias;\n"
    "                _398 = ((((((((float(shadow_map2.sample(shadow_smp2, (_316 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _332) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, _316).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) + float(shadow_map2.sample(shadow_smp2, (_316 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _332)) * 0.111111111938953399658203125;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _398 = 1.0;\n"
    "            }\n"
    "            _399 = _398;\n"
    "        }\n"
    "        _400 = _399;\n"
    "    }\n"
    "    float3 _404 = fast::normalize(GridFragUniforms.light_dir.xyz);\n"
    "    float3 _427 = ((_113 * GridFragUniforms.ambient) + (_113 * (_400 * precise::max(_404.y, 0.0)))) + ((float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_404 + fast::normalize(GridFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0)).y, 0.0), GridFragUniforms.shininess))) * _400);\n"
    "    out.out_var_SV_Target = float4(_427, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
