/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4 cascade_splits;\n"
    "    uint has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float shadow_texel_size;\n"
    "    float shadow_bias;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 in_var_TEXCOORD5 [[user(locn5)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_map0 [[texture(1)]], texture2d<float> shadow_map1 [[texture(2)]], texture2d<float> shadow_map2 [[texture(3)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp0 [[sampler(1)]], sampler shadow_smp1 [[sampler(2)]], sampler shadow_smp2 [[sampler(3)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _91;\n"
    "    if (SceneFragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _91 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0) * SceneFragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _91 = SceneFragUniforms.base_color;\n"
    "    }\n"
    "    float _96 = length(in.in_var_TEXCOORD2 - SceneFragUniforms.eye_pos.xyz);\n"
    "    float _383;\n"
    "    if (_96 < SceneFragUniforms.cascade_splits.x)\n"
    "    {\n"
    "        float3 _107 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _110 = (_107.xy * 0.5) + float2(0.5);\n"
    "        _110.y = 1.0 - _110.y;\n"
    "        float _126 = _107.z - SceneFragUniforms.shadow_bias;\n"
    "        _383 = ((((((((float(shadow_map0.sample(shadow_smp0, (_110 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, _110).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) + float(shadow_map0.sample(shadow_smp0, (_110 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _126)) * 0.111111111938953399658203125;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _382;\n"
    "        if (_96 < SceneFragUniforms.cascade_splits.y)\n"
    "        {\n"
    "            float3 _202 = in.in_var_TEXCOORD4.xyz / float3(in.in_var_TEXCOORD4.w);\n"
    "            float2 _205 = (_202.xy * 0.5) + float2(0.5);\n"
    "            _205.y = 1.0 - _205.y;\n"
    "            float _221 = _202.z - SceneFragUniforms.shadow_bias;\n"
    "            _382 = ((((((((float(shadow_map1.sample(shadow_smp1, (_205 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, _205).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) + float(shadow_map1.sample(shadow_smp1, (_205 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _221)) * 0.111111111938953399658203125;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _381;\n"
    "            if (_96 < SceneFragUniforms.cascade_splits.z)\n"
    "            {\n"
    "                float3 _296 = in.in_var_TEXCOORD5.xyz / float3(in.in_var_TEXCOORD5.w);\n"
    "                float2 _299 = (_296.xy * 0.5) + float2(0.5);\n"
    "                _299.y = 1.0 - _299.y;\n"
    "                float _315 = _296.z - SceneFragUniforms.shadow_bias;\n"
    "                _381 = ((((((((float(shadow_map2.sample(shadow_smp2, (_299 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, _299).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) + float(shadow_map2.sample(shadow_smp2, (_299 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _315)) * 0.111111111938953399658203125;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _381 = 1.0;\n"
    "            }\n"
    "            _382 = _381;\n"
    "        }\n"
    "        _383 = _382;\n"
    "    }\n"
    "    float3 _384 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _388 = fast::normalize(SceneFragUniforms.light_dir.xyz);\n"
    "    out.out_var_SV_Target = float4(((_91.xyz * SceneFragUniforms.ambient) + (_91.xyz * (_383 * precise::max(dot(_384, _388), 0.0)))) + (float3(1.0) * ((_383 * SceneFragUniforms.specular_str) * powr(precise::max(dot(_384, fast::normalize(_388 + fast::normalize(SceneFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), SceneFragUniforms.shininess))), _91.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
