/* Auto-generated from shadow.vert.msl -- do not edit by hand. */
static const char shadow_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_ShadowVertUniforms\n"
    "{\n"
    "    float4x4 light_mvp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_ShadowVertUniforms& ShadowVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowVertUniforms.light_mvp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_vert_msl_size = sizeof(shadow_vert_msl) - 1;
