/* Auto-generated from outline.frag.msl -- do not edit by hand. */
static const char outline_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_OutlineUniforms\n"
    "{\n"
    "    float4 outline_color;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(constant type_OutlineUniforms& OutlineUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.out_var_SV_Target = OutlineUniforms.outline_color;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int outline_frag_msl_size = sizeof(outline_frag_msl) - 1;
