/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    char _m8_pad[8];\n"
    "    packed_float3 tint;\n"
    "    float _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _58 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float3 _67 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _84 = fast::normalize(-SceneFragUniforms.light_dir.xyz);\n"
    "    float _150;\n"
    "    do\n"
    "    {\n"
    "        float3 _103 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _106 = (_103.xy * 0.5) + float2(0.5);\n"
    "        float _108 = 1.0 - _106.y;\n"
    "        float2 _109 = _106;\n"
    "        _109.y = _108;\n"
    "        float _110 = _106.x;\n"
    "        bool _115;\n"
    "        if ((isunordered(_110, 0.0) || _110 >= 0.0))\n"
    "        {\n"
    "            _115 = _110 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _115 = true;\n"
    "        }\n"
    "        bool _120;\n"
    "        if (!_115)\n"
    "        {\n"
    "            _120 = _108 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _120 = true;\n"
    "        }\n"
    "        bool _125;\n"
    "        if (!_120)\n"
    "        {\n"
    "            _125 = _108 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _125 = true;\n"
    "        }\n"
    "        if (_125)\n"
    "        {\n"
    "            _150 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _128 = _103.z;\n"
    "        float _130;\n"
    "        _130 = 0.0;\n"
    "        for (int _133 = 0; _133 < 4; )\n"
    "        {\n"
    "            _130 += float((_128 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_109 + (_58[_133] * float2(0.00048828125)))).x);\n"
    "            _133++;\n"
    "            continue;\n"
    "        }\n"
    "        _150 = _130 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4(((SceneFragUniforms.base_color.xyz * SceneFragUniforms.ambient) + (float3(SceneFragUniforms.tint) * SceneFragUniforms.ambient)) + (((((SceneFragUniforms.base_color.xyz * precise::max(dot(_67, _84), 0.0)) + float3(SceneFragUniforms.specular_str * powr(precise::max(dot(_67, fast::normalize(_84 + fast::normalize(float3(SceneFragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), SceneFragUniforms.shininess))) * SceneFragUniforms.light_intensity) * float3(SceneFragUniforms.light_color)) * _150), SceneFragUniforms.base_color.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
