/* Auto-generated from particle.frag.msl -- do not edit by hand. */
static const char particle_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "constant float4 _22 = {};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float4 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float2 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> atlas_tex [[texture(0)]], sampler atlas_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _30 = float4(in.in_var_TEXCOORD0.x, in.in_var_TEXCOORD0.y, in.in_var_TEXCOORD0.z, _22.w);\n"
    "    float _33 = atlas_tex.sample(atlas_smp, in.in_var_TEXCOORD1).w * in.in_var_TEXCOORD0.w;\n"
    "    _30.w = _33;\n"
    "    if (_33 < 0.0040000001899898052215576171875)\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    out.out_var_SV_Target = _30;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int particle_frag_msl_size = sizeof(particle_frag_msl) - 1;
