/* Auto-generated from particle.vert.msl -- do not edit by hand. */
static const char particle_vert_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct Particle\n"
    "{\n"
    "    float4 pos_lifetime;\n"
    "    float4 vel_size;\n"
    "    float4 color;\n"
    "    float4 max_life_type;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_Particle\n"
    "{\n"
    "    Particle _m0[1];\n"
    "};\n"
    "\n"
    "struct type_BillboardUniforms\n"
    "{\n"
    "    float4x4 view_proj;\n"
    "    float4 cam_right;\n"
    "    float4 cam_up;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 6> _59 = spvUnsafeArray<float2, 6>({ float2(-0.5), float2(0.5, -0.5), float2(0.5), float2(-0.5), float2(0.5), float2(-0.5, 0.5) });\n"
    "constant spvUnsafeArray<float2, 6> _60 = spvUnsafeArray<float2, 6>({ float2(0.0, 1.0), float2(1.0), float2(1.0, 0.0), float2(0.0, 1.0), float2(1.0, 0.0), float2(0.0) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float2 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(const device type_StructuredBuffer_Particle& particles [[buffer(0)]], constant type_BillboardUniforms& BillboardUniforms [[buffer(1)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _119;\n"
    "    float4 _120;\n"
    "    float2 _121;\n"
    "    do\n"
    "    {\n"
    "        uint _65 = gl_VertexIndex / 6u;\n"
    "        uint _66 = gl_VertexIndex % 6u;\n"
    "        if (particles._m0[_65].pos_lifetime.w <= 0.0)\n"
    "        {\n"
    "            _119 = float4(0.0);\n"
    "            _120 = float4(0.0);\n"
    "            _121 = float2(0.0);\n"
    "            break;\n"
    "        }\n"
    "        uint _108 = uint(fast::clamp(1.0 - (particles._m0[_65].pos_lifetime.w / precise::max(particles._m0[_65].max_life_type.x, 0.001000000047497451305389404296875)), 0.0, 0.999000012874603271484375) * 16.0);\n"
    "        _119 = BillboardUniforms.view_proj * float4(particles._m0[_65].pos_lifetime.xyz + ((BillboardUniforms.cam_right.xyz * (_59[_66].x * particles._m0[_65].vel_size.w)) + (BillboardUniforms.cam_up.xyz * (_59[_66].y * particles._m0[_65].vel_size.w))), 1.0);\n"
    "        _120 = particles._m0[_65].color;\n"
    "        _121 = (float2(float(_108 % 4u), float(_108 / 4u)) * 0.25) + (_60[_66] * 0.25);\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.gl_Position = _119;\n"
    "    out.out_var_TEXCOORD0 = _120;\n"
    "    out.out_var_TEXCOORD1 = _121;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int particle_vert_msl_size = sizeof(particle_vert_msl) - 1;
