/* Auto-generated from fog.frag.msl -- do not edit by hand. */
static const char fog_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 mat_ambient;\n"
    "    float4 mat_diffuse;\n"
    "    float4 mat_specular;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    uint has_texture;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "    float _pad2;\n"
    "    float4 fog_color;\n"
    "    float fog_start;\n"
    "    float fog_end;\n"
    "    float fog_density;\n"
    "    uint fog_mode;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float3 _65;\n"
    "    if (FragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _65 = FragUniforms.mat_diffuse.xyz * diffuse_tex.sample(smp, in.in_var_TEXCOORD0).xyz;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _65 = FragUniforms.mat_diffuse.xyz;\n"
    "    }\n"
    "    float3 _66 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _70 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _74 = FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2;\n"
    "    float _95 = length(_74);\n"
    "    float _128;\n"
    "    if (FragUniforms.fog_mode == 0u)\n"
    "    {\n"
    "        _128 = fast::clamp((FragUniforms.fog_end - _95) / (FragUniforms.fog_end - FragUniforms.fog_start), 0.0, 1.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _127;\n"
    "        if (FragUniforms.fog_mode == 1u)\n"
    "        {\n"
    "            _127 = fast::clamp(exp((-FragUniforms.fog_density) * _95), 0.0, 1.0);\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _122 = FragUniforms.fog_density * _95;\n"
    "            _127 = fast::clamp(exp(-(_122 * _122)), 0.0, 1.0);\n"
    "        }\n"
    "        _128 = _127;\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(mix(FragUniforms.fog_color.xyz, (FragUniforms.mat_ambient.xyz + (_65 * precise::max(dot(_66, _70), 0.0))) + (FragUniforms.mat_specular.xyz * powr(precise::max(dot(_66, fast::normalize(_70 + fast::normalize(_74))), 0.0), FragUniforms.mat_specular.w)), float3(_128)), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int fog_frag_msl_size = sizeof(fog_frag_msl) - 1;
