/* Auto-generated from grid_fog.frag.msl -- do not edit by hand. */
static const char grid_fog_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "    float4 fog_color;\n"
    "    float fog_start;\n"
    "    float fog_end;\n"
    "    float fog_density;\n"
    "    uint fog_mode;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _50 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _51 = fwidth(_50);\n"
    "    float2 _56 = abs(fract(_50 - float2(0.5)) - float2(0.5)) / _51;\n"
    "    float4 _84 = mix(GridFragUniforms.bg_color, GridFragUniforms.line_color, float4(((1.0 - fast::clamp(precise::min(_56.x, _56.y), 0.0, 1.0)) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_51.x, _51.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0.xz - GridFragUniforms.eye_pos.xz)))));\n"
    "    float3 _88 = fast::normalize(GridFragUniforms.light_dir.xyz);\n"
    "    float3 _90 = GridFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0;\n"
    "    float3 _92 = _84.xyz;\n"
    "    float _112 = length(_90);\n"
    "    float _145;\n"
    "    if (GridFragUniforms.fog_mode == 0u)\n"
    "    {\n"
    "        _145 = fast::clamp((GridFragUniforms.fog_end - _112) / (GridFragUniforms.fog_end - GridFragUniforms.fog_start), 0.0, 1.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _144;\n"
    "        if (GridFragUniforms.fog_mode == 1u)\n"
    "        {\n"
    "            _144 = fast::clamp(exp((-GridFragUniforms.fog_density) * _112), 0.0, 1.0);\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _139 = GridFragUniforms.fog_density * _112;\n"
    "            _144 = fast::clamp(exp(-(_139 * _139)), 0.0, 1.0);\n"
    "        }\n"
    "        _145 = _144;\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(mix(GridFragUniforms.fog_color.xyz, ((_92 * GridFragUniforms.ambient) + (_92 * precise::max(_88.y, 0.0))) + (float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_88 + fast::normalize(_90)).y, 0.0), GridFragUniforms.shininess))), float3(_145)), _84.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_fog_frag_msl_size = sizeof(grid_fog_frag_msl) - 1;
