/* Auto-generated from sky.vert.msl -- do not edit by hand. */
static const char sky_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SkyVertUniforms\n"
    "{\n"
    "    float4x4 ray_matrix;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float2 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(constant type_SkyVertUniforms& SkyVertUniforms [[buffer(0)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    bool _40;\n"
    "    if (gl_VertexIndex != 1u)\n"
    "    {\n"
    "        _40 = gl_VertexIndex == 4u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _40 = true;\n"
    "    }\n"
    "    bool _45;\n"
    "    if (!_40)\n"
    "    {\n"
    "        _45 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _45 = true;\n"
    "    }\n"
    "    float _46 = float(_45);\n"
    "    bool _51;\n"
    "    if (gl_VertexIndex != 2u)\n"
    "    {\n"
    "        _51 = gl_VertexIndex == 3u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _51 = true;\n"
    "    }\n"
    "    bool _56;\n"
    "    if (!_51)\n"
    "    {\n"
    "        _56 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _56 = true;\n"
    "    }\n"
    "    float _57 = float(_56);\n"
    "    float _61 = (_46 * 2.0) - 1.0;\n"
    "    float _63 = (_57 * 2.0) - 1.0;\n"
    "    float4 _68 = SkyVertUniforms.ray_matrix * float4(_61, _63, 1.0, 1.0);\n"
    "    out.gl_Position = float4(_61, _63, 0.0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = _68.xyz / float3(_68.w);\n"
    "    out.out_var_TEXCOORD1 = float2(_46, 1.0 - _57);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int sky_vert_msl_size = sizeof(sky_vert_msl) - 1;
