/* Auto-generated from pulled.vert.msl -- do not edit by hand. */
static const char pulled_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct PulledVertex\n"
    "{\n"
    "    float3 position;\n"
    "    float3 normal;\n"
    "    float2 uv;\n"
    "    char _m0_final_padding[8];\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_PulledVertex\n"
    "{\n"
    "    PulledVertex _m0[1];\n"
    "};\n"
    "\n"
    "struct type_SceneUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(const device type_StructuredBuffer_PulledVertex& vertex_buffer [[buffer(0)]], constant type_SceneUniforms& SceneUniforms [[buffer(1)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _49 = float4(vertex_buffer._m0[gl_VertexIndex].position, 1.0);\n"
    "    out.gl_Position = SceneUniforms.mvp * _49;\n"
    "    out.out_var_TEXCOORD0 = (SceneUniforms.model * _49).xyz;\n"
    "    out.out_var_TEXCOORD1 = fast::normalize(vertex_buffer._m0[gl_VertexIndex].normal * float3x3(float4(SceneUniforms.model[0][0], SceneUniforms.model[1][0], SceneUniforms.model[2][0], SceneUniforms.model[3][0]).xyz, float4(SceneUniforms.model[0][1], SceneUniforms.model[1][1], SceneUniforms.model[2][1], SceneUniforms.model[3][1]).xyz, float4(SceneUniforms.model[0][2], SceneUniforms.model[1][2], SceneUniforms.model[2][2], SceneUniforms.model[3][2]).xyz));\n"
    "    out.out_var_TEXCOORD2 = vertex_buffer._m0[gl_VertexIndex].uv;\n"
    "    out.out_var_TEXCOORD3 = SceneUniforms.light_vp * _49;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int pulled_vert_msl_size = sizeof(pulled_vert_msl) - 1;
