/* Auto-generated from pulled.frag.msl -- do not edit by hand. */
static const char pulled_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _62 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_tex [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _82;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _82 = FragUniforms.base_color * diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _82 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _83 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _96 = fast::normalize(-FragUniforms.light_dir.xyz);\n"
    "    float _162;\n"
    "    do\n"
    "    {\n"
    "        float3 _115 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _118 = (_115.xy * 0.5) + float2(0.5);\n"
    "        float _120 = 1.0 - _118.y;\n"
    "        float2 _121 = _118;\n"
    "        _121.y = _120;\n"
    "        float _122 = _118.x;\n"
    "        bool _127;\n"
    "        if ((isunordered(_122, 0.0) || _122 >= 0.0))\n"
    "        {\n"
    "            _127 = _122 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _127 = true;\n"
    "        }\n"
    "        bool _132;\n"
    "        if (!_127)\n"
    "        {\n"
    "            _132 = _120 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _132 = true;\n"
    "        }\n"
    "        bool _137;\n"
    "        if (!_132)\n"
    "        {\n"
    "            _137 = _120 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _137 = true;\n"
    "        }\n"
    "        if (_137)\n"
    "        {\n"
    "            _162 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _140 = _115.z;\n"
    "        float _142;\n"
    "        _142 = 0.0;\n"
    "        for (int _145 = 0; _145 < 4; )\n"
    "        {\n"
    "            _142 += float((_140 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_121 + (_62[_145] * float2(0.00048828125)))).x);\n"
    "            _145++;\n"
    "            continue;\n"
    "        }\n"
    "        _162 = _142 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_82.xyz * FragUniforms.ambient) + (((((_82.xyz * precise::max(dot(_83, _96), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_83, fast::normalize(_96 + fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess))) * FragUniforms.light_intensity) * float3(FragUniforms.light_color)) * _162), _82.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int pulled_frag_msl_size = sizeof(pulled_frag_msl) - 1;
