/* Auto-generated from shadow_pulled.vert.msl -- do not edit by hand. */
static const char shadow_pulled_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct PulledVertex\n"
    "{\n"
    "    float3 position;\n"
    "    float3 normal;\n"
    "    float2 uv;\n"
    "    char _m0_final_padding[8];\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_PulledVertex\n"
    "{\n"
    "    PulledVertex _m0[1];\n"
    "};\n"
    "\n"
    "struct type_ShadowUniforms\n"
    "{\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(const device type_StructuredBuffer_PulledVertex& vertex_buffer [[buffer(0)]], constant type_ShadowUniforms& ShadowUniforms [[buffer(1)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowUniforms.light_vp * float4(vertex_buffer._m0[gl_VertexIndex].position, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_pulled_vert_msl_size = sizeof(shadow_pulled_vert_msl) - 1;
