/* Auto-generated from debug_box.vert.msl -- do not edit by hand. */
static const char debug_box_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct ObjectTransform\n"
    "{\n"
    "    float4x4 model;\n"
    "    float4 color;\n"
    "    float4 bounding_sphere;\n"
    "    uint num_indices;\n"
    "    uint first_index;\n"
    "    int vertex_offset;\n"
    "    uint _pad;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_ObjectTransform\n"
    "{\n"
    "    ObjectTransform _m0[1];\n"
    "};\n"
    "\n"
    "struct type_DebugVertUniforms\n"
    "{\n"
    "    float4x4 debug_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    uint out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    uint in_var_TEXCOORD3 [[attribute(3)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], const device type_StructuredBuffer_ObjectTransform& object_data [[buffer(0)]], constant type_DebugVertUniforms& DebugVertUniforms [[buffer(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = DebugVertUniforms.debug_vp * (object_data._m0[in.in_var_TEXCOORD3].model * float4(in.in_var_TEXCOORD0, 1.0));\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD1 * float3x3(cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][1], object_data._m0[in.in_var_TEXCOORD3].model[1][1], object_data._m0[in.in_var_TEXCOORD3].model[2][1], object_data._m0[in.in_var_TEXCOORD3].model[3][1]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][2], object_data._m0[in.in_var_TEXCOORD3].model[1][2], object_data._m0[in.in_var_TEXCOORD3].model[2][2], object_data._m0[in.in_var_TEXCOORD3].model[3][2]).xyz), cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][2], object_data._m0[in.in_var_TEXCOORD3].model[1][2], object_data._m0[in.in_var_TEXCOORD3].model[2][2], object_data._m0[in.in_var_TEXCOORD3].model[3][2]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][0], object_data._m0[in.in_var_TEXCOORD3].model[1][0], object_data._m0[in.in_var_TEXCOORD3].model[2][0], object_data._m0[in.in_var_TEXCOORD3].model[3][0]).xyz), cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][0], object_data._m0[in.in_var_TEXCOORD3].model[1][0], object_data._m0[in.in_var_TEXCOORD3].model[2][0], object_data._m0[in.in_var_TEXCOORD3].model[3][0]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][1], object_data._m0[in.in_var_TEXCOORD3].model[1][1], object_data._m0[in.in_var_TEXCOORD3].model[2][1], object_data._m0[in.in_var_TEXCOORD3].model[3][1]).xyz));\n"
    "    out.out_var_TEXCOORD1 = in.in_var_TEXCOORD3;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int debug_box_vert_msl_size = sizeof(debug_box_vert_msl) - 1;
