/* Auto-generated from frustum_cull.comp.msl -- do not edit by hand. */
static const char frustum_cull_comp_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct ObjectData\n"
    "{\n"
    "    float4x4 model;\n"
    "    float4 color;\n"
    "    float4 bounding_sphere;\n"
    "    uint num_indices;\n"
    "    uint first_index;\n"
    "    int vertex_offset;\n"
    "    uint _pad;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_ObjectData\n"
    "{\n"
    "    ObjectData _m0[1];\n"
    "};\n"
    "\n"
    "struct IndirectCommand\n"
    "{\n"
    "    uint num_indices;\n"
    "    uint num_instances;\n"
    "    uint first_index;\n"
    "    int vertex_offset;\n"
    "    uint first_instance;\n"
    "};\n"
    "\n"
    "struct type_RWStructuredBuffer_IndirectCommand\n"
    "{\n"
    "    IndirectCommand _m0[1];\n"
    "};\n"
    "\n"
    "struct type_RWStructuredBuffer_uint\n"
    "{\n"
    "    uint _m0[1];\n"
    "};\n"
    "\n"
    "struct type_CullUniforms\n"
    "{\n"
    "    float4 frustum_planes[6];\n"
    "    uint num_objects;\n"
    "    uint enable_culling;\n"
    "    float2 _pad;\n"
    "};\n"
    "\n"
    "constant bool _47 = {};\n"
    "\n"
    "kernel void main0(device type_StructuredBuffer_ObjectData& objects [[buffer(0)]], device type_RWStructuredBuffer_IndirectCommand& indirect_commands [[buffer(1)]], device type_RWStructuredBuffer_uint& visibility [[buffer(2)]], constant type_CullUniforms& CullUniforms [[buffer(3)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])\n"
    "{\n"
    "    do\n"
    "    {\n"
    "        if (gl_GlobalInvocationID.x >= CullUniforms.num_objects)\n"
    "        {\n"
    "            break;\n"
    "        }\n"
    "        bool _103;\n"
    "        if (CullUniforms.enable_culling != 0u)\n"
    "        {\n"
    "            bool _102;\n"
    "            do\n"
    "            {\n"
    "                bool _99;\n"
    "                bool _100;\n"
    "                int _82 = 0;\n"
    "                for (;;)\n"
    "                {\n"
    "                    if (_82 < 6)\n"
    "                    {\n"
    "                        if ((dot(objects._m0[gl_GlobalInvocationID.x].bounding_sphere.xyz, CullUniforms.frustum_planes[_82].xyz) + CullUniforms.frustum_planes[_82].w) < (-objects._m0[gl_GlobalInvocationID.x].bounding_sphere.w))\n"
    "                        {\n"
    "                            _99 = false;\n"
    "                            _100 = true;\n"
    "                            break;\n"
    "                        }\n"
    "                        _82++;\n"
    "                        continue;\n"
    "                    }\n"
    "                    else\n"
    "                    {\n"
    "                        _99 = _47;\n"
    "                        _100 = false;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                if (_100)\n"
    "                {\n"
    "                    _102 = _99;\n"
    "                    break;\n"
    "                }\n"
    "                _102 = true;\n"
    "                break;\n"
    "            } while(false);\n"
    "            _103 = _102;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _103 = true;\n"
    "        }\n"
    "        uint _105 = uint(int(_103));\n"
    "        indirect_commands._m0[gl_GlobalInvocationID.x] = IndirectCommand{ objects._m0[gl_GlobalInvocationID.x].num_indices, _105, objects._m0[gl_GlobalInvocationID.x].first_index, objects._m0[gl_GlobalInvocationID.x].vertex_offset, gl_GlobalInvocationID.x };\n"
    "        visibility._m0[gl_GlobalInvocationID.x] = _105;\n"
    "        break;\n"
    "    } while(false);\n"
    "}\n"
    "\n"
;
static const unsigned int frustum_cull_comp_msl_size = sizeof(frustum_cull_comp_msl) - 1;
