/* Auto-generated from indirect_box.frag.msl -- do not edit by hand. */
static const char indirect_box_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float shadow_texel;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], depth2d<float> shadow_map [[texture(1)]], sampler tex_sampler [[sampler(0)]], sampler shadow_sampler [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _69 = diffuse_tex.sample(tex_sampler, in.in_var_TEXCOORD2);\n"
    "    float4 _70 = _69 * in.in_var_TEXCOORD4;\n"
    "    float3 _71 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _75 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _87 = _70.xyz;\n"
    "    float _204;\n"
    "    do\n"
    "    {\n"
    "        float3 _104 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _107 = (_104.xy * 0.5) + float2(0.5);\n"
    "        float _109 = 1.0 - _107.y;\n"
    "        float2 _110 = _107;\n"
    "        _110.y = _109;\n"
    "        float _111 = _104.z;\n"
    "        float _112 = _107.x;\n"
    "        bool _117;\n"
    "        if ((isunordered(_112, 0.0) || _112 >= 0.0))\n"
    "        {\n"
    "            _117 = _112 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _117 = true;\n"
    "        }\n"
    "        bool _122;\n"
    "        if (!_117)\n"
    "        {\n"
    "            _122 = _109 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _122 = true;\n"
    "        }\n"
    "        bool _127;\n"
    "        if (!_122)\n"
    "        {\n"
    "            _127 = _109 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _127 = true;\n"
    "        }\n"
    "        bool _132;\n"
    "        if (!_127)\n"
    "        {\n"
    "            _132 = _111 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _132 = true;\n"
    "        }\n"
    "        bool _137;\n"
    "        if (!_132)\n"
    "        {\n"
    "            _137 = _111 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _137 = true;\n"
    "        }\n"
    "        if (_137)\n"
    "        {\n"
    "            _204 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _146 = _111 - 0.00200000009499490261077880859375;\n"
    "        _204 = ((((((((shadow_map.sample_compare(shadow_sampler, (_110 + (float2(-1.0) * FragUniforms.shadow_texel)), _146, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(0.0, -1.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(1.0, -1.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(-1.0, 0.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _110, _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(1.0, 0.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(-1.0, 1.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(0.0, 1.0) * FragUniforms.shadow_texel)), _146, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_110 + (float2(1.0) * FragUniforms.shadow_texel)), _146, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_87 * FragUniforms.ambient) + (((_87 * precise::max(dot(_71, _75), 0.0)) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_71, fast::normalize(_75 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess)))) * _204), _70.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int indirect_box_frag_msl_size = sizeof(indirect_box_frag_msl) - 1;
