/* Auto-generated from indirect_shadow.vert.msl -- do not edit by hand. */
static const char indirect_shadow_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct ObjectTransform\n"
    "{\n"
    "    float4x4 model;\n"
    "    float4 color;\n"
    "    float4 bounding_sphere;\n"
    "    uint num_indices;\n"
    "    uint first_index;\n"
    "    int vertex_offset;\n"
    "    uint _pad;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_ObjectTransform\n"
    "{\n"
    "    ObjectTransform _m0[1];\n"
    "};\n"
    "\n"
    "struct type_ShadowUniforms\n"
    "{\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    uint in_var_TEXCOORD3 [[attribute(3)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], const device type_StructuredBuffer_ObjectTransform& object_data [[buffer(0)]], constant type_ShadowUniforms& ShadowUniforms [[buffer(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowUniforms.light_vp * (object_data._m0[in.in_var_TEXCOORD3].model * float4(in.in_var_TEXCOORD0, 1.0));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int indirect_shadow_vert_msl_size = sizeof(indirect_shadow_vert_msl) - 1;
