/* Auto-generated from indirect_box.vert.msl -- do not edit by hand. */
static const char indirect_box_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct ObjectTransform\n"
    "{\n"
    "    float4x4 model;\n"
    "    float4 color;\n"
    "    float4 bounding_sphere;\n"
    "    uint num_indices;\n"
    "    uint first_index;\n"
    "    int vertex_offset;\n"
    "    uint _pad;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_ObjectTransform\n"
    "{\n"
    "    ObjectTransform _m0[1];\n"
    "};\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 out_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    uint in_var_TEXCOORD3 [[attribute(3)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], const device type_StructuredBuffer_ObjectTransform& object_data [[buffer(0)]], constant type_VertUniforms& VertUniforms [[buffer(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _59 = object_data._m0[in.in_var_TEXCOORD3].model * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = VertUniforms.vp * _59;\n"
    "    out.out_var_TEXCOORD0 = _59.xyz;\n"
    "    out.out_var_TEXCOORD1 = in.in_var_TEXCOORD1 * float3x3(cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][1], object_data._m0[in.in_var_TEXCOORD3].model[1][1], object_data._m0[in.in_var_TEXCOORD3].model[2][1], object_data._m0[in.in_var_TEXCOORD3].model[3][1]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][2], object_data._m0[in.in_var_TEXCOORD3].model[1][2], object_data._m0[in.in_var_TEXCOORD3].model[2][2], object_data._m0[in.in_var_TEXCOORD3].model[3][2]).xyz), cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][2], object_data._m0[in.in_var_TEXCOORD3].model[1][2], object_data._m0[in.in_var_TEXCOORD3].model[2][2], object_data._m0[in.in_var_TEXCOORD3].model[3][2]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][0], object_data._m0[in.in_var_TEXCOORD3].model[1][0], object_data._m0[in.in_var_TEXCOORD3].model[2][0], object_data._m0[in.in_var_TEXCOORD3].model[3][0]).xyz), cross(float4(object_data._m0[in.in_var_TEXCOORD3].model[0][0], object_data._m0[in.in_var_TEXCOORD3].model[1][0], object_data._m0[in.in_var_TEXCOORD3].model[2][0], object_data._m0[in.in_var_TEXCOORD3].model[3][0]).xyz, float4(object_data._m0[in.in_var_TEXCOORD3].model[0][1], object_data._m0[in.in_var_TEXCOORD3].model[1][1], object_data._m0[in.in_var_TEXCOORD3].model[2][1], object_data._m0[in.in_var_TEXCOORD3].model[3][1]).xyz));\n"
    "    out.out_var_TEXCOORD2 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD3 = VertUniforms.light_vp * _59;\n"
    "    out.out_var_TEXCOORD4 = object_data._m0[in.in_var_TEXCOORD3].color;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int indirect_box_vert_msl_size = sizeof(indirect_box_vert_msl) - 1;
