/* Auto-generated from truck_scene.vert.msl -- do not edit by hand. */
static const char truck_scene_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_TruckVertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "    float4 in_var_TEXCOORD4 [[attribute(4)]];\n"
    "    float4 in_var_TEXCOORD5 [[attribute(5)]];\n"
    "    float4 in_var_TEXCOORD6 [[attribute(6)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_TruckVertUniforms& TruckVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4x4 _46 = transpose(float4x4(in.in_var_TEXCOORD3, in.in_var_TEXCOORD4, in.in_var_TEXCOORD5, in.in_var_TEXCOORD6));\n"
    "    float4 _51 = float4(in.in_var_TEXCOORD0, 1.0) * _46;\n"
    "    float3 _60 = _46[0].xyz;\n"
    "    float3 _62 = _46[1].xyz;\n"
    "    float3 _64 = _46[2].xyz;\n"
    "    out.gl_Position = TruckVertUniforms.vp * _51;\n"
    "    out.out_var_TEXCOORD0 = _51.xyz;\n"
    "    out.out_var_TEXCOORD1 = in.in_var_TEXCOORD1 * float3x3(cross(_62, _64), cross(_64, _60), cross(_60, _62));\n"
    "    out.out_var_TEXCOORD2 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD3 = TruckVertUniforms.light_vp * _51;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int truck_scene_vert_msl_size = sizeof(truck_scene_vert_msl) - 1;
