/* Auto-generated from truck_scene.frag.msl -- do not edit by hand. */
static const char truck_scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_TruckFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float shadow_texel;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    uint has_texture;\n"
    "    packed_float3 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_TruckFragUniforms& TruckFragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], depth2d<float> shadow_map [[texture(1)]], sampler tex_sampler [[sampler(0)]], sampler shadow_sampler [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _82;\n"
    "    if (TruckFragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _82 = diffuse_tex.sample(tex_sampler, in.in_var_TEXCOORD2) * TruckFragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _82 = TruckFragUniforms.base_color;\n"
    "    }\n"
    "    float3 _83 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _87 = fast::normalize(TruckFragUniforms.light_dir.xyz);\n"
    "    float _216;\n"
    "    do\n"
    "    {\n"
    "        float3 _116 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _119 = (_116.xy * 0.5) + float2(0.5);\n"
    "        float _121 = 1.0 - _119.y;\n"
    "        float2 _122 = _119;\n"
    "        _122.y = _121;\n"
    "        float _123 = _116.z;\n"
    "        float _124 = _119.x;\n"
    "        bool _129;\n"
    "        if ((isunordered(_124, 0.0) || _124 >= 0.0))\n"
    "        {\n"
    "            _129 = _124 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _129 = true;\n"
    "        }\n"
    "        bool _134;\n"
    "        if (!_129)\n"
    "        {\n"
    "            _134 = _121 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        bool _139;\n"
    "        if (!_134)\n"
    "        {\n"
    "            _139 = _121 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _139 = true;\n"
    "        }\n"
    "        bool _144;\n"
    "        if (!_139)\n"
    "        {\n"
    "            _144 = _123 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _144 = true;\n"
    "        }\n"
    "        bool _149;\n"
    "        if (!_144)\n"
    "        {\n"
    "            _149 = _123 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _149 = true;\n"
    "        }\n"
    "        if (_149)\n"
    "        {\n"
    "            _216 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _158 = _123 - 0.00200000009499490261077880859375;\n"
    "        _216 = ((((((((shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(0.0, -1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0, -1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0, 0.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _122, _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0, 0.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0, 1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(0.0, 1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0) * TruckFragUniforms.shadow_texel)), _158, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_82.xyz * TruckFragUniforms.ambient) + (((_82.xyz * precise::max(dot(_83, _87), 0.0)) + (float3(1.0) * (TruckFragUniforms.specular_str * powr(precise::max(dot(_83, fast::normalize(_87 + fast::normalize(TruckFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0))), 0.0), TruckFragUniforms.shininess)))) * _216), _82.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int truck_scene_frag_msl_size = sizeof(truck_scene_frag_msl) - 1;
