/**
 * Tests for the .fmat JSON parser.
 *
 * Validates against golden fixtures generated by
 * tests/pipeline/generate_fixtures.py.
 *
 * SPDX-License-Identifier: Zlib
 */

import { describe, it, expect } from "vitest"
import { readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { parseFmat, FmatParseError } from "../fmat-parser"

// ── Fixture loading ─────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = resolve(__dirname, "../../../../../tests/pipeline/fixtures")

function loadFixtureText(name: string): string {
  return readFileSync(resolve(FIXTURES_DIR, name), "utf-8")
}

// ── Golden fixture tests ────────────────────────────────────────────────

describe("fmat-parser (golden fixtures)", () => {
  it("parses simple.fmat correctly", () => {
    const text = loadFixtureText("simple.fmat")
    const data = parseFmat(text)

    expect(data.version).toBe(1)
    expect(data.materials).toHaveLength(2)

    // Material 0: Wood
    const wood = data.materials[0]
    expect(wood.name).toBe("Wood")
    expect(wood.baseColorFactor).toEqual([0.8, 0.6, 0.3, 1.0])
    expect(wood.baseColorTexture).toBe("textures/wood_albedo.png")
    expect(wood.metallicFactor).toBe(0)
    expect(wood.roughnessFactor).toBe(0.8)
    expect(wood.metallicRoughnessTexture).toBe("textures/wood_mr.png")
    expect(wood.normalTexture).toBe("textures/wood_normal.png")
    expect(wood.normalScale).toBe(1.0)
    expect(wood.occlusionTexture).toBeNull()
    expect(wood.occlusionStrength).toBe(1.0)
    expect(wood.emissiveFactor).toEqual([0, 0, 0])
    expect(wood.emissiveTexture).toBeNull()
    expect(wood.alphaMode).toBe("OPAQUE")
    expect(wood.alphaCutoff).toBe(0.5)
    expect(wood.doubleSided).toBe(false)

    // Material 1: Glass
    const glass = data.materials[1]
    expect(glass.name).toBe("Glass")
    expect(glass.baseColorFactor).toEqual([0.9, 0.9, 1.0, 0.5])
    expect(glass.baseColorTexture).toBeNull()
    expect(glass.metallicFactor).toBe(0)
    expect(glass.roughnessFactor).toBe(0.1)
    expect(glass.alphaMode).toBe("BLEND")
    expect(glass.doubleSided).toBe(true)
  })
})

// ── Error case tests ────────────────────────────────────────────────────

describe("fmat-parser (error cases)", () => {
  it("rejects invalid JSON", () => {
    expect(() => parseFmat("{not json")).toThrow(FmatParseError)
    expect(() => parseFmat("{not json")).toThrow(/Invalid JSON/)
  })

  it("rejects non-object root", () => {
    expect(() => parseFmat("[]")).toThrow(FmatParseError)
    expect(() => parseFmat("[]")).toThrow(/root must be a JSON object/)
  })

  it("rejects wrong version", () => {
    expect(() => parseFmat('{"version": 99, "materials": []}')).toThrow(
      FmatParseError,
    )
    expect(() => parseFmat('{"version": 99, "materials": []}')).toThrow(
      /Unsupported .fmat version/,
    )
  })

  it("rejects missing materials array", () => {
    expect(() => parseFmat('{"version": 1}')).toThrow(FmatParseError)
    expect(() => parseFmat('{"version": 1}')).toThrow(
      /"materials" must be an array/,
    )
  })

  it("rejects non-object material entry", () => {
    expect(() =>
      parseFmat('{"version": 1, "materials": ["not an object"]}'),
    ).toThrow(FmatParseError)
    expect(() =>
      parseFmat('{"version": 1, "materials": ["not an object"]}'),
    ).toThrow(/must be an object/)
  })

  it("rejects invalid alpha_mode", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Bad",
          base_color_factor: [1, 1, 1, 1],
          emissive_factor: [0, 0, 0],
          alpha_mode: "INVALID",
        },
      ],
    })
    expect(() => parseFmat(json)).toThrow(FmatParseError)
    expect(() => parseFmat(json)).toThrow(/invalid alpha_mode/)
  })

  it("rejects texture path with directory traversal", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Evil",
          base_color_factor: [1, 1, 1, 1],
          emissive_factor: [0, 0, 0],
          base_color_texture: "../../../etc/passwd",
        },
      ],
    })
    expect(() => parseFmat(json)).toThrow(FmatParseError)
    expect(() => parseFmat(json)).toThrow(/contains "\.\."/)
  })

  it("rejects absolute texture path", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Evil",
          base_color_factor: [1, 1, 1, 1],
          emissive_factor: [0, 0, 0],
          base_color_texture: "/etc/passwd",
        },
      ],
    })
    expect(() => parseFmat(json)).toThrow(FmatParseError)
    expect(() => parseFmat(json)).toThrow(/absolute/)
  })

  it("rejects Windows absolute texture path", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Evil",
          base_color_factor: [1, 1, 1, 1],
          emissive_factor: [0, 0, 0],
          base_color_texture: "C:\\Windows\\System32\\config",
        },
      ],
    })
    expect(() => parseFmat(json)).toThrow(FmatParseError)
    expect(() => parseFmat(json)).toThrow(/absolute/)
  })

  it("clamps out-of-range color factors to [0, 1]", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Clamped",
          base_color_factor: [-0.5, 2.0, 0.5, 1.0],
          emissive_factor: [0, 0, 0],
        },
      ],
    })
    const data = parseFmat(json)
    expect(data.materials[0].baseColorFactor).toEqual([0, 1, 0.5, 1.0])
  })

  it("uses defaults for missing optional fields", () => {
    const json = JSON.stringify({
      version: 1,
      materials: [
        {
          name: "Minimal",
          base_color_factor: [1, 1, 1, 1],
          emissive_factor: [0, 0, 0],
        },
      ],
    })
    const data = parseFmat(json)
    const m = data.materials[0]
    expect(m.metallicFactor).toBe(1.0)
    expect(m.roughnessFactor).toBe(1.0)
    expect(m.normalScale).toBe(1.0)
    expect(m.occlusionStrength).toBe(1.0)
    expect(m.alphaCutoff).toBe(0.5)
    expect(m.alphaMode).toBe("OPAQUE")
    expect(m.doubleSided).toBe(false)
    expect(m.baseColorTexture).toBeNull()
  })
})
