/**
 * Tests for the .fmesh binary parser.
 *
 * Validates against golden fixtures generated by
 * tests/pipeline/generate_fixtures.py — if the C binary format
 * changes, these tests will fail until the TypeScript parser is
 * updated to match.
 *
 * SPDX-License-Identifier: Zlib
 */

import { describe, it, expect } from "vitest"
import { readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import {
  parseFmesh,
  FmeshParseError,
  FMESH_HEADER_SIZE,
  FMESH_STRIDE_TAN,
  FMESH_STRIDE_NO_TAN,
  FMESH_VERSION_V2,
  FMESH_VERSION_V3,
  FMESH_FLAG_TANGENTS,
  FMESH_MAX_LODS,
  FMESH_MAX_SUBMESHES,
} from "../fmesh-parser"

// ── Fixture loading ─────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = resolve(__dirname, "../../../../../tests/pipeline/fixtures")

function loadFixture(name: string): ArrayBuffer {
  const buf = readFileSync(resolve(FIXTURES_DIR, name))
  // Convert Node.js Buffer to ArrayBuffer
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
}

// ── Helper: build a minimal .fmesh ArrayBuffer in code ──────────────────

function buildFmesh(opts: {
  magic?: string
  version?: number
  vertexCount?: number
  stride?: number
  lodCount?: number
  flags?: number
  submeshCount?: number
  /**
   * If true, write valid vertex + index data for up to 3 vertices.
   * The helper always writes min(vertexCount, 3) actual vertices —
   * remaining slots are zero-filled.
   */
  writeData?: boolean
  /** Override the total buffer size (for truncation tests). */
  bufferSize?: number
}): ArrayBuffer {
  const magic = opts.magic ?? "FMSH"
  const version = opts.version ?? FMESH_VERSION_V2
  const vertexCount = opts.vertexCount ?? 3
  const stride = opts.stride ?? FMESH_STRIDE_NO_TAN
  const lodCount = opts.lodCount ?? 1
  const flags = opts.flags ?? 0
  const submeshCount = opts.submeshCount ?? 1
  const writeData = opts.writeData ?? true

  // Calculate sizes
  const perLodSize = 4 + submeshCount * 12
  const lodTableSize = lodCount * perLodSize
  const vertexDataSize = vertexCount * stride
  const totalIndices = lodCount * submeshCount * 3 // 3 indices per submesh
  const indexDataSize = totalIndices * 4

  const fullSize = FMESH_HEADER_SIZE + lodTableSize + vertexDataSize + indexDataSize
  const bufSize = opts.bufferSize ?? fullSize
  const buf = new ArrayBuffer(bufSize)
  const view = new DataView(buf)

  // Header
  for (let i = 0; i < 4 && i < magic.length; i++) {
    view.setUint8(i, magic.charCodeAt(i))
  }
  if (bufSize >= 8) view.setUint32(4, version, true)
  if (bufSize >= 12) view.setUint32(8, vertexCount, true)
  if (bufSize >= 16) view.setUint32(12, stride, true)
  if (bufSize >= 20) view.setUint32(16, lodCount, true)
  if (bufSize >= 24) view.setUint32(20, flags, true)
  if (bufSize >= 28) view.setUint32(24, submeshCount, true)

  if (!writeData || bufSize < fullSize) return buf

  // LOD-submesh table
  let pos = FMESH_HEADER_SIZE
  let runningOffset = 0
  for (let lod = 0; lod < lodCount; lod++) {
    view.setFloat32(pos, lod * 0.01, true)
    pos += 4
    for (let s = 0; s < submeshCount; s++) {
      view.setUint32(pos, 3, true)     // index_count
      view.setUint32(pos + 4, runningOffset, true) // index_offset
      view.setInt32(pos + 8, s, true)  // material_index
      pos += 12
      runningOffset += 3 * 4
    }
  }

  // Vertex data: up to 3 vertices (remaining slots are zero-filled)
  const vStart = FMESH_HEADER_SIZE + lodTableSize
  const positions = [
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
  ]
  const vertsToWrite = Math.min(vertexCount, positions.length)
  for (let v = 0; v < vertsToWrite; v++) {
    const off = vStart + v * stride
    // position
    view.setFloat32(off + 0, positions[v][0], true)
    view.setFloat32(off + 4, positions[v][1], true)
    view.setFloat32(off + 8, positions[v][2], true)
    // normal (0, 0, 1)
    view.setFloat32(off + 12, 0, true)
    view.setFloat32(off + 16, 0, true)
    view.setFloat32(off + 20, 1, true)
    // uv
    view.setFloat32(off + 24, positions[v][0], true)
    view.setFloat32(off + 28, positions[v][1], true)
    if (stride === FMESH_STRIDE_TAN) {
      // tangent (1, 0, 0, 1)
      view.setFloat32(off + 32, 1, true)
      view.setFloat32(off + 36, 0, true)
      view.setFloat32(off + 40, 0, true)
      view.setFloat32(off + 44, 1, true)
    }
  }

  // Index data: (0, 1, 2) repeated
  const iStart = vStart + vertexDataSize
  for (let i = 0; i < totalIndices / 3; i++) {
    const base = iStart + i * 12
    view.setUint32(base + 0, 0, true)
    view.setUint32(base + 4, 1, true)
    view.setUint32(base + 8, 2, true)
  }

  return buf
}

// ── Golden fixture tests ────────────────────────────────────────────────

describe("fmesh-parser (golden fixtures)", () => {
  it("parses triangle.fmesh correctly", () => {
    const buf = loadFixture("triangle.fmesh")
    const data = parseFmesh(buf)

    // Header
    expect(data.header.version).toBe(FMESH_VERSION_V2)
    expect(data.header.vertexCount).toBe(3)
    expect(data.header.vertexStride).toBe(FMESH_STRIDE_TAN)
    expect(data.header.lodCount).toBe(1)
    expect(data.header.flags).toBe(FMESH_FLAG_TANGENTS)
    expect(data.header.submeshCount).toBe(1)
    expect(data.hasTangents).toBe(true)

    // LOD table
    expect(data.lods).toHaveLength(1)
    expect(data.lods[0].targetError).toBeCloseTo(0.0)
    expect(data.lods[0].submeshes).toHaveLength(1)
    expect(data.lods[0].submeshes[0].indexCount).toBe(3)
    expect(data.lods[0].submeshes[0].indexOffset).toBe(0)
    expect(data.lods[0].submeshes[0].materialIndex).toBe(0)

    // Indices
    expect(data.indices).toHaveLength(3)
    expect(Array.from(data.indices)).toEqual([0, 1, 2])

    // Vertex data: verify first vertex position (0, 0, 0)
    const vView = new DataView(data.vertexBuffer)
    const vOff = data.vertexBufferOffset
    expect(vView.getFloat32(vOff + 0, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 4, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 8, true)).toBeCloseTo(0.0)

    // Second vertex position (1, 0, 0)
    const v1Off = vOff + FMESH_STRIDE_TAN
    expect(vView.getFloat32(v1Off + 0, true)).toBeCloseTo(1.0)
    expect(vView.getFloat32(v1Off + 4, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(v1Off + 8, true)).toBeCloseTo(0.0)

    // Third vertex position (0, 1, 0)
    const v2Off = vOff + 2 * FMESH_STRIDE_TAN
    expect(vView.getFloat32(v2Off + 0, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(v2Off + 4, true)).toBeCloseTo(1.0)
    expect(vView.getFloat32(v2Off + 8, true)).toBeCloseTo(0.0)

    // First vertex normal (0, 0, 1)
    expect(vView.getFloat32(vOff + 12, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 16, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 20, true)).toBeCloseTo(1.0)

    // First vertex tangent (1, 0, 0, 1)
    expect(vView.getFloat32(vOff + 32, true)).toBeCloseTo(1.0)
    expect(vView.getFloat32(vOff + 36, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 40, true)).toBeCloseTo(0.0)
    expect(vView.getFloat32(vOff + 44, true)).toBeCloseTo(1.0)
  })

  it("parses multi_lod.fmesh correctly", () => {
    const buf = loadFixture("multi_lod.fmesh")
    const data = parseFmesh(buf)

    expect(data.header.lodCount).toBe(2)
    expect(data.header.submeshCount).toBe(2)
    expect(data.lods).toHaveLength(2)

    // LOD 0: target_error = 0.0
    expect(data.lods[0].targetError).toBeCloseTo(0.0)
    expect(data.lods[0].submeshes).toHaveLength(2)
    expect(data.lods[0].submeshes[0].materialIndex).toBe(0)
    expect(data.lods[0].submeshes[1].materialIndex).toBe(1)

    // LOD 1: target_error = 0.01
    expect(data.lods[1].targetError).toBeCloseTo(0.01)
    expect(data.lods[1].submeshes).toHaveLength(2)

    // Total indices: 2 LODs × 2 submeshes × 3 indices = 12
    expect(data.indices).toHaveLength(12)

    // Each group of 3 indices is (0, 1, 2)
    for (let i = 0; i < 12; i += 3) {
      expect(data.indices[i]).toBe(0)
      expect(data.indices[i + 1]).toBe(1)
      expect(data.indices[i + 2]).toBe(2)
    }
  })
})

// ── Constructed buffer tests ────────────────────────────────────────────

describe("fmesh-parser (constructed buffers)", () => {
  it("parses a stride-32 mesh without tangents", () => {
    const buf = buildFmesh({ stride: FMESH_STRIDE_NO_TAN, flags: 0 })
    const data = parseFmesh(buf)
    expect(data.hasTangents).toBe(false)
    expect(data.header.vertexStride).toBe(FMESH_STRIDE_NO_TAN)
    expect(data.header.vertexCount).toBe(3)
  })

  it("parses a mesh with maximum valid LOD count", () => {
    const buf = buildFmesh({ lodCount: FMESH_MAX_LODS })
    const data = parseFmesh(buf)
    expect(data.lods).toHaveLength(FMESH_MAX_LODS)
  })

  it("accepts version 3 (skinned/morph format)", () => {
    const buf = buildFmesh({ version: FMESH_VERSION_V3 })
    const data = parseFmesh(buf)
    expect(data.header.vertexCount).toBe(3)
  })
})

// ── Error case tests ────────────────────────────────────────────────────

describe("fmesh-parser (error cases)", () => {
  it("rejects buffer smaller than header", () => {
    const buf = new ArrayBuffer(16)
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/too small for .fmesh header/),
      }),
    )
  })

  it("rejects invalid magic", () => {
    const buf = buildFmesh({ magic: "XXXX" })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Invalid .fmesh magic/),
      }),
    )
  })

  it("rejects unsupported version", () => {
    const buf = buildFmesh({ version: 99 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Unsupported .fmesh version/),
      }),
    )
  })

  it("rejects version 1 (pre-submesh format)", () => {
    const buf = buildFmesh({ version: 1 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Unsupported .fmesh version/),
      }),
    )
  })

  it("rejects vertex_count of 0", () => {
    const buf = buildFmesh({ vertexCount: 0, writeData: false })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/vertex_count is 0/),
      }),
    )
  })

  it("rejects invalid stride (not 32 or 48)", () => {
    const buf = buildFmesh({ stride: 64, flags: 0 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Invalid .fmesh vertex_stride/),
      }),
    )
  })

  it("rejects lod_count of 0", () => {
    const buf = buildFmesh({ lodCount: 0 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/lod_count is 0/),
      }),
    )
  })

  it("rejects lod_count exceeding maximum", () => {
    const buf = buildFmesh({ lodCount: FMESH_MAX_LODS + 1 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/lod_count.*exceeds maximum/),
      }),
    )
  })

  it("rejects submesh_count exceeding maximum", () => {
    const buf = buildFmesh({ submeshCount: FMESH_MAX_SUBMESHES + 1 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/submesh_count.*exceeds maximum/),
      }),
    )
  })

  it("rejects submesh_count of 0", () => {
    const buf = buildFmesh({ submeshCount: 0 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/submesh_count is 0/),
      }),
    )
  })

  it("rejects stride/flag mismatch (tangent flag without stride 48)", () => {
    const buf = buildFmesh({ stride: FMESH_STRIDE_NO_TAN, flags: FMESH_FLAG_TANGENTS })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Flag\/stride mismatch/),
      }),
    )
  })

  it("rejects stride/flag mismatch (stride 48 without tangent flag)", () => {
    const buf = buildFmesh({ stride: FMESH_STRIDE_TAN, flags: 0 })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Flag\/stride mismatch/),
      }),
    )
  })

  it("rejects truncated LOD table", () => {
    // Header says 2 LODs but buffer only has header
    const buf = buildFmesh({
      lodCount: 2,
      bufferSize: FMESH_HEADER_SIZE + 4, // only room for 4 bytes of table
      writeData: false,
    })
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/too small for LOD-submesh table/),
      }),
    )
  })

  it("rejects truncated vertex data", () => {
    // Valid header + LOD table but vertex section is cut short
    const lodTableSize = 4 + 12 // 1 LOD, 1 submesh
    const buf = buildFmesh({
      bufferSize: FMESH_HEADER_SIZE + lodTableSize + 10, // 10 bytes of vertex data (need 96)
      writeData: false,
    })
    // Write valid LOD table so parser gets past that stage
    const view = new DataView(buf)
    let pos = FMESH_HEADER_SIZE
    view.setFloat32(pos, 0.0, true)
    pos += 4
    view.setUint32(pos, 3, true) // index_count
    view.setUint32(pos + 4, 0, true) // index_offset
    view.setInt32(pos + 8, 0, true) // material_index

    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/too small for vertex data/),
      }),
    )
  })

  it("rejects truncated index data", () => {
    // Valid header + LOD table + vertex data but index section is cut short
    const lodTableSize = 4 + 12
    const vertexDataSize = 3 * FMESH_STRIDE_NO_TAN
    const fullSize = FMESH_HEADER_SIZE + lodTableSize + vertexDataSize + 12 // need 12 bytes of index data
    const buf = buildFmesh({
      bufferSize: fullSize - 4, // 4 bytes short
      writeData: false,
    })
    // Write valid LOD table
    const view = new DataView(buf)
    let pos = FMESH_HEADER_SIZE
    view.setFloat32(pos, 0.0, true)
    pos += 4
    view.setUint32(pos, 3, true)
    view.setUint32(pos + 4, 0, true)
    view.setInt32(pos + 8, 0, true)

    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/too small for index data/),
      }),
    )
  })

  it("rejects index values exceeding vertex count", () => {
    const buf = buildFmesh({})
    // Corrupt one index to be out of bounds
    const view = new DataView(buf)
    const lodTableSize = 4 + 12
    const vertexDataSize = 3 * FMESH_STRIDE_NO_TAN
    const indexStart = FMESH_HEADER_SIZE + lodTableSize + vertexDataSize
    view.setUint32(indexStart, 99, true) // index 0 = 99, but vertex_count = 3
    expect(() => parseFmesh(buf)).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/Index out of bounds/),
      }),
    )
  })

  it("rejects empty buffer", () => {
    expect(() => parseFmesh(new ArrayBuffer(0))).toThrow(
      expect.objectContaining({
        name: "FmeshParseError",
        message: expect.stringMatching(/too small for .fmesh header/),
      }),
    )
  })
})
