/**
 * Tests for the .ftex binary parser.
 *
 * Validates against golden fixtures generated by
 * tests/pipeline/generate_fixtures.py.
 *
 * SPDX-License-Identifier: Zlib
 */

import { describe, it, expect } from "vitest"
import { readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import {
  parseFtex,
  FtexParseError,
  FTEX_MAGIC,
  FTEX_VERSION,
  FTEX_HEADER_SIZE,
  FTEX_MIP_ENTRY_SIZE,
  FTEX_FORMAT_BC7_SRGB,
  FTEX_MAX_MIP_LEVELS,
  FTEX_MAX_DIMENSION,
} from "../ftex-parser"

// ── Fixture loading ─────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = resolve(__dirname, "../../../../../tests/pipeline/fixtures")

function loadFixture(name: string): ArrayBuffer {
  const buf = readFileSync(resolve(FIXTURES_DIR, name))
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
}

// ── Helper: build a .ftex ArrayBuffer ───────────────────────────────────

function buildFtex(opts?: {
  magic?: number
  version?: number
  format?: number
  width?: number
  height?: number
  mipCount?: number
  /** If false, don't write valid mip data. */
  writeData?: boolean
  bufferSize?: number
}): ArrayBuffer {
  const magic = opts?.magic ?? FTEX_MAGIC
  const version = opts?.version ?? FTEX_VERSION
  const format = opts?.format ?? FTEX_FORMAT_BC7_SRGB
  const width = opts?.width ?? 4
  const height = opts?.height ?? 4
  const mipCount = opts?.mipCount ?? 1
  const writeData = opts?.writeData ?? true

  // BC7: 16 bytes per 4×4 block
  const blocksX = Math.ceil(width / 4)
  const blocksY = Math.ceil(height / 4)
  const blockDataSize = blocksX * blocksY * 16
  const dataOffset = FTEX_HEADER_SIZE + mipCount * FTEX_MIP_ENTRY_SIZE

  const fullSize = dataOffset + (writeData ? blockDataSize : 0)
  const bufSize = opts?.bufferSize ?? fullSize
  const buf = new ArrayBuffer(bufSize)
  const view = new DataView(buf)

  view.setUint32(0, magic, true)
  view.setUint32(4, version, true)
  view.setUint32(8, format, true)
  view.setUint32(12, width, true)
  view.setUint32(16, height, true)
  view.setUint32(20, mipCount, true)

  if (writeData && bufSize >= fullSize) {
    // Mip entry
    view.setUint32(FTEX_HEADER_SIZE + 0, dataOffset, true)
    view.setUint32(FTEX_HEADER_SIZE + 4, blockDataSize, true)
    view.setUint32(FTEX_HEADER_SIZE + 8, width, true)
    view.setUint32(FTEX_HEADER_SIZE + 12, height, true)
  }

  return buf
}

// ── Golden fixture tests ────────────────────────────────────────────────

describe("ftex-parser (golden fixtures)", () => {
  it("parses checkerboard.ftex correctly", () => {
    const buf = loadFixture("checkerboard.ftex")
    const data = parseFtex(buf)

    expect(data.format).toBe(FTEX_FORMAT_BC7_SRGB)
    expect(data.width).toBe(4)
    expect(data.height).toBe(4)
    expect(data.mipCount).toBe(1)
    expect(data.mips).toHaveLength(1)

    // 4×4 = 1 block × 16 bytes
    expect(data.mips[0].dataSize).toBe(16)
    expect(data.mips[0].width).toBe(4)
    expect(data.mips[0].height).toBe(4)
    expect(data.mips[0].data.byteLength).toBe(16)

    // Data offset = header(32) + 1 mip entry(16) = 48
    expect(data.mips[0].dataOffset).toBe(FTEX_HEADER_SIZE + FTEX_MIP_ENTRY_SIZE)
  })
})

// ── Error case tests ────────────────────────────────────────────────────

describe("ftex-parser (error cases)", () => {
  it("rejects buffer smaller than header", () => {
    expect(() => parseFtex(new ArrayBuffer(16))).toThrow(FtexParseError)
    expect(() => parseFtex(new ArrayBuffer(16))).toThrow(/too small for .ftex header/)
  })

  it("rejects invalid magic", () => {
    const buf = buildFtex({ magic: 0xDEADBEEF })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Invalid .ftex magic/)
  })

  it("rejects unsupported version", () => {
    const buf = buildFtex({ version: 99 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Unsupported .ftex version/)
  })

  it("rejects unknown format", () => {
    const buf = buildFtex({ format: 42 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Unknown .ftex format/)
  })

  it("rejects zero dimensions", () => {
    const buf = buildFtex({ width: 0 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Invalid .ftex dimensions/)
  })

  it("rejects oversized dimensions", () => {
    const buf = buildFtex({ width: FTEX_MAX_DIMENSION + 1 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/exceeds maximum/)
  })

  it("rejects zero mip count", () => {
    const buf = buildFtex({ mipCount: 0 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Invalid .ftex mip_count/)
  })

  it("rejects mip count exceeding maximum", () => {
    const buf = buildFtex({ mipCount: FTEX_MAX_MIP_LEVELS + 1 })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/Invalid .ftex mip_count/)
  })

  it("rejects truncated mip table", () => {
    // Header says 2 mips but buffer only has room for header + 1 entry
    const buf = buildFtex({
      mipCount: 2,
      bufferSize: FTEX_HEADER_SIZE + FTEX_MIP_ENTRY_SIZE,
      writeData: false,
    })
    expect(() => parseFtex(buf)).toThrow(FtexParseError)
    expect(() => parseFtex(buf)).toThrow(/too small for mip table/)
  })

  it("rejects empty buffer", () => {
    expect(() => parseFtex(new ArrayBuffer(0))).toThrow(FtexParseError)
  })
})
