/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float fill_intensity;\n"
    "    float4 fill_dir;\n"
    "    packed_float3 spot_pos;\n"
    "    float spot_intensity;\n"
    "    packed_float3 spot_dir;\n"
    "    float cos_inner;\n"
    "    packed_float3 spot_color;\n"
    "    float cos_outer;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _69 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], texture2d<float> gobo_tex [[texture(1)]], sampler shadow_smp [[sampler(0)]], sampler gobo_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _77 = in.in_var_TEXCOORD0.xz / float2(FragUniforms.grid_spacing);\n"
    "    float2 _82 = fwidth(_77);\n"
    "    float2 _85 = float2(FragUniforms.line_width);\n"
    "    float2 _88 = float2(1.0) - smoothstep(_85, _85 + _82, abs(fract(_77 - float2(0.5)) - float2(0.5)));\n"
    "    float3 _115 = mix(FragUniforms.bg_color.xyz, FragUniforms.line_color.xyz, float3((precise::max(_88.x, _88.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_82.x, _82.y)))) * (1.0 - smoothstep(FragUniforms.fade_distance * 0.5, FragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(FragUniforms.eye_pos))))));\n"
    "    float3 _130 = (_115 * FragUniforms.ambient) + ((_115 * precise::max(fast::normalize(-FragUniforms.fill_dir.xyz).y, 0.0)) * FragUniforms.fill_intensity);\n"
    "    float3 _133 = in.in_var_TEXCOORD0 - float3(FragUniforms.spot_pos);\n"
    "    float _134 = length(_133);\n"
    "    float _145 = smoothstep(FragUniforms.cos_outer, FragUniforms.cos_inner, dot(_133 / float3(_134), fast::normalize(float3(FragUniforms.spot_dir))));\n"
    "    float3 _224;\n"
    "    if (_145 > 0.0)\n"
    "    {\n"
    "        float4 _155 = FragUniforms.light_vp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "        float3 _159 = _155.xyz / float3(_155.w);\n"
    "        float2 _162 = (_159.xy * 0.5) + float2(0.5);\n"
    "        float _164 = 1.0 - _162.y;\n"
    "        float2 _165 = _162;\n"
    "        _165.y = _164;\n"
    "        float _166 = _162.x;\n"
    "        float4 _177 = gobo_tex.sample(gobo_smp, _165);\n"
    "        float _179 = _159.z;\n"
    "        float _181;\n"
    "        _181 = 0.0;\n"
    "        for (int _184 = 0; _184 < 4; )\n"
    "        {\n"
    "            _181 += float((_179 - 0.00200000009499490261077880859375) <= shadow_tex.sample(shadow_smp, (_165 + (_69[_184] * float2(0.0009765625)))).x);\n"
    "            _184++;\n"
    "            continue;\n"
    "        }\n"
    "        _224 = _130 + ((((((((_115 * precise::max(fast::normalize(float3(FragUniforms.spot_pos) - in.in_var_TEXCOORD0).y, 0.0)) * _145) * _177.x) * (_181 * 0.25)) * (((step(0.0, _166) * step(_166, 1.0)) * step(0.0, _164)) * step(_164, 1.0))) * (1.0 / ((1.0 + (0.0900000035762786865234375 * _134)) + ((0.0320000015199184417724609375 * _134) * _134)))) * FragUniforms.spot_intensity) * float3(FragUniforms.spot_color));\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _224 = _130;\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(_224, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
