/* Auto-generated from grid.vert.msl -- do not edit by hand. */
static const char grid_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 vp_matrix;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = VertUniforms.vp_matrix * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD0;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_vert_msl_size = sizeof(grid_vert_msl) - 1;
