/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float ambient;\n"
    "    float fill_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float4 fill_dir;\n"
    "    packed_float3 spot_pos;\n"
    "    float spot_intensity;\n"
    "    packed_float3 spot_dir;\n"
    "    float cos_inner;\n"
    "    packed_float3 spot_color;\n"
    "    float cos_outer;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _71 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_tex [[texture(1)]], texture2d<float> gobo_tex [[texture(2)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp [[sampler(1)]], sampler gobo_smp [[sampler(2)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _89;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _89 = FragUniforms.base_color * diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _89 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _90 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _94 = fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0);\n"
    "    float3 _103 = fast::normalize(-FragUniforms.fill_dir.xyz);\n"
    "    float3 _122 = (_89.xyz * FragUniforms.ambient) + (((_89.xyz * precise::max(dot(_90, _103), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_90, fast::normalize(_103 + _94)), 0.0), FragUniforms.shininess))) * FragUniforms.fill_intensity);\n"
    "    float3 _125 = in.in_var_TEXCOORD0 - float3(FragUniforms.spot_pos);\n"
    "    float _126 = length(_125);\n"
    "    float _137 = smoothstep(FragUniforms.cos_outer, FragUniforms.cos_inner, dot(_125 / float3(_126), fast::normalize(float3(FragUniforms.spot_dir))));\n"
    "    float3 _224;\n"
    "    if (_137 > 0.0)\n"
    "    {\n"
    "        float4 _147 = FragUniforms.light_vp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "        float3 _151 = _147.xyz / float3(_147.w);\n"
    "        float2 _154 = (_151.xy * 0.5) + float2(0.5);\n"
    "        float _156 = 1.0 - _154.y;\n"
    "        float2 _157 = _154;\n"
    "        _157.y = _156;\n"
    "        float _158 = _154.x;\n"
    "        float4 _169 = gobo_tex.sample(gobo_smp, _157);\n"
    "        float _171 = _151.z;\n"
    "        float _173;\n"
    "        _173 = 0.0;\n"
    "        for (int _176 = 0; _176 < 4; )\n"
    "        {\n"
    "            _173 += float((_171 - 0.00200000009499490261077880859375) <= shadow_tex.sample(shadow_smp, (_157 + (_71[_176] * float2(0.0009765625)))).x);\n"
    "            _176++;\n"
    "            continue;\n"
    "        }\n"
    "        float3 _194 = fast::normalize(float3(FragUniforms.spot_pos) - in.in_var_TEXCOORD0);\n"
    "        _224 = _122 + (((((((((_89.xyz * precise::max(dot(_90, _194), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_90, fast::normalize(_194 + _94)), 0.0), FragUniforms.shininess))) * _137) * _169.x) * (_173 * 0.25)) * (((step(0.0, _158) * step(_158, 1.0)) * step(0.0, _156)) * step(_156, 1.0))) * (1.0 / ((1.0 + (0.0900000035762786865234375 * _126)) + ((0.0320000015199184417724609375 * _126) * _126)))) * FragUniforms.spot_intensity) * float3(FragUniforms.spot_color));\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _224 = _122;\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(_224, _89.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
