/*
 * Lesson 47 — Texture Atlas Rendering
 *
 * Demonstrates how texture atlases reduce GPU state changes by packing
 * multiple material textures into a single image and remapping UVs in
 * the fragment shader.
 *
 * The scene shows a 6x5 grid of cubes, each textured with a different
 * material (stone, wood, metal, brick, etc.).  Press Tab to toggle
 * between atlas mode (1 texture bind per frame) and individual mode
 * (30 texture binds per frame).  The forge UI panel displays the bind
 * count difference in real time.
 *
 * The atlas and its metadata (atlas.json) are pre-generated by the
 * pipeline's atlas packer (Asset Lesson 17).  The C code uses
 * forge_pipeline_load_atlas() to parse the UV offset/scale per material,
 * then passes those values as push constants to the fragment shader.
 *
 * Controls:
 *   WASD / Mouse  — move/look
 *   Space / Shift — fly up/down
 *   Tab           — toggle atlas / individual texture mode
 *   Escape        — release mouse cursor
 *
 * SPDX-License-Identifier: Zlib
 */

#define SDL_MAIN_USE_CALLBACKS 1

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <stddef.h>    /* offsetof */

#include "math/forge_math.h"

#define FORGE_SCENE_IMPLEMENTATION
#include "scene/forge_scene.h"

#define FORGE_PIPELINE_IMPLEMENTATION
#include "pipeline/forge_pipeline.h"

#define FORGE_SHAPES_IMPLEMENTATION
#include "shapes/forge_shapes.h"

/* ── Constants ─────────────────────────────────────────────────────────── */

#define WINDOW_WIDTH     1280
#define WINDOW_HEIGHT    720
#define ASSET_PATH_SIZE  512

/* Grid layout for the 30 material cubes */
#define GRID_COLS        6
#define GRID_ROWS        5
#define MATERIAL_COUNT   (GRID_COLS * GRID_ROWS)

/* Cube size and spacing (world units) */
#define CUBE_HALF_SIZE   0.45f
#define CUBE_SPACING     1.6f

/* Lighting */
#define LIGHT_DIR_X      0.4f
#define LIGHT_DIR_Y      0.8f
#define LIGHT_DIR_Z      0.6f
#define AMBIENT          0.15f
#define SHININESS        32.0f

/* Camera starting position and orientation */
#define CAM_START_X      0.0f
#define CAM_START_Y      6.0f
#define CAM_START_Z      12.0f
#define CAM_START_PITCH  -0.4f
#define CAM_START_YAW    0.0f

/* UI layout */
#define UI_PANEL_X       10.0f
#define UI_PANEL_Y       10.0f
#define UI_PANEL_W       300.0f
#define UI_PANEL_H       240.0f
#define UI_LABEL_H       20

/* Sampler limits */
#define SAMPLER_MAX_LOD  1000.0f

/* Relative path buffer for material filenames */
#define REL_PATH_SIZE    256

/* ── Material names (sorted alphabetically to match atlas.json) ──────── */

static const char *MATERIAL_NAMES[MATERIAL_COUNT] = {
    "bark",             "brushed_steel",    "cobblestone",
    "copper_patina",    "corrugated_metal", "cracked_concrete",
    "diamond_plate",    "dirt",             "flagstone",
    "grass",            "gravel",           "hardwood_floor",
    "herringbone_brick","leather",          "marble",
    "old_brick_wall",   "parquet",          "plywood",
    "red_brick",        "roof_tiles",       "rough_plaster",
    "rough_rock",       "rusted_iron",      "sandstone",
    "slate",            "smooth_concrete",  "stucco",
    "weathered_planks", "white_brick",      "woven_fabric",
};

/* ── Helper: build asset path relative to executable ─────────────────── */

static const char *asset_path(char *buf, size_t buf_size,
                              const char *base, const char *relative)
{
    int len = SDL_snprintf(buf, buf_size, "%s%s", base, relative);
    if (len < 0 || (size_t)len >= buf_size) {
        SDL_Log("asset_path: path too long: %s%s", base, relative);
        return NULL;
    }
    return buf;
}

/* ── Application state ───────────────────────────────────────────────── */

typedef struct {
    ForgeScene             scene;          /* rendering baseline (camera, grid, sky, UI) */

    /* Cube mesh (one cube, drawn 30 times with different transforms) */
    ForgeShape             cube_shape;     /* CPU-side procedural cube geometry     */
    SDL_GPUBuffer         *cube_vb;        /* interleaved pos+normal+uv (32B/vert) */
    SDL_GPUBuffer         *cube_ib;        /* index buffer (uint32)                */

    /* Atlas mode resources */
    SDL_GPUTexture        *atlas_texture;  /* packed atlas image (all materials)   */
    ForgePipelineAtlas     atlas_meta;     /* parsed atlas.json UV metadata        */

    /* Individual mode resources */
    SDL_GPUTexture        *individual_textures[MATERIAL_COUNT]; /* per-material textures */

    /* Shared sampler (linear filtering, clamp-to-edge for atlas safety) */
    SDL_GPUSampler        *sampler;        /* texture sampler for both modes       */

    /* Pre-computed atlas entry index per material (built once at init,
     * avoids per-frame string comparison in the draw loop) */
    int                    atlas_entry_idx[MATERIAL_COUNT]; /* index into atlas_meta.entries */

    /* Mode toggle */
    bool                   use_atlas;      /* true = atlas, false = individual     */

    /* UI state */
    int                    bind_count;     /* unique textures used this frame       */
    ForgeUiWindowState     ui_window;      /* draggable UI panel position/state    */
} app_state;

/* ── Helper: load a PNG into a GPU texture via forge_scene ────────────── */

static SDL_GPUTexture *load_texture(ForgeScene *scene, const char *path)
{
    SDL_Surface *surface = SDL_LoadSurface(path);
    if (!surface) {
        SDL_Log("load_texture: failed to load '%s': %s", path, SDL_GetError());
        return NULL;
    }
    SDL_GPUTexture *tex = forge_scene_upload_texture(scene, surface, true);
    SDL_DestroySurface(surface);
    if (!tex) {
        SDL_Log("load_texture: upload failed for '%s'", path);
    }
    return tex;
}

/* ═══════════════════════════════════════════════════════════════════════
 * SDL_AppInit — Create device, window, scene, geometry, textures, pipeline
 * ═══════════════════════════════════════════════════════════════════════ */

SDL_AppResult SDL_AppInit(void **appstate, int argc, char *argv[])
{
    app_state *state = (app_state *)SDL_calloc(1, sizeof(app_state));
    if (!state) {
        SDL_Log("SDL_AppInit: failed to allocate app_state");
        return SDL_APP_FAILURE;
    }
    *appstate = state;

    /* Start in atlas mode — the lesson's main teaching mode */
    state->use_atlas = true;

    /* ── Resolve base path for asset loading ─────────────────────────── */

    const char *base = SDL_GetBasePath();
    if (!base) {
        SDL_Log("SDL_AppInit: SDL_GetBasePath failed: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    /* ── Scene baseline (camera, grid, sky, UI) ──────────────────────── */

    /* Locate font for UI rendering */
    char font_buf[ASSET_PATH_SIZE];
    const char *font = asset_path(font_buf, sizeof(font_buf), base,
        "assets/fonts/liberation_mono/LiberationMono-Regular.ttf");
    if (!font) return SDL_APP_FAILURE;

    ForgeSceneConfig cfg = forge_scene_default_config("Lesson 47 — Texture Atlas Rendering");
    cfg.cam_start_pos   = vec3_create(CAM_START_X, CAM_START_Y, CAM_START_Z);
    cfg.cam_start_pitch = CAM_START_PITCH;
    cfg.cam_start_yaw   = CAM_START_YAW;
    cfg.font_path       = font;

    if (!forge_scene_init(&state->scene, &cfg, argc, argv)) {
        SDL_Log("SDL_AppInit: forge_scene_init failed");
        return SDL_APP_FAILURE;
    }

    SDL_GPUDevice *dev = forge_scene_device(&state->scene);

    /* ── UI window state ──────────────────────────────────────────────── */
    state->ui_window = forge_ui_window_state_default(
        UI_PANEL_X, UI_PANEL_Y, UI_PANEL_W, UI_PANEL_H);

    /* ── Generate cube geometry ──────────────────────────────────────── */

    /* Create a unit cube (extents [-1,+1]) then scale to CUBE_HALF_SIZE
     * via the model matrix.  slices=1, stacks=1 gives the simplest mesh. */
    state->cube_shape = forge_shapes_cube(1, 1);
    if (state->cube_shape.vertex_count == 0) {
        SDL_Log("SDL_AppInit: forge_shapes_cube failed");
        return SDL_APP_FAILURE;
    }

    /* Interleave ForgeShape (struct-of-arrays) into ForgeSceneTexturedVertex
     * (array-of-structs) for the scene textured pipeline. */
    {
        Uint32 vc = (Uint32)state->cube_shape.vertex_count;
        ForgeSceneTexturedVertex *verts = (ForgeSceneTexturedVertex *)SDL_calloc(
            vc, sizeof(ForgeSceneTexturedVertex));
        if (!verts) {
            SDL_Log("SDL_AppInit: vertex allocation failed");
            return SDL_APP_FAILURE;
        }
        for (Uint32 v = 0; v < vc; v++) {
            verts[v].position = state->cube_shape.positions[v];
            verts[v].normal   = state->cube_shape.normals[v];
            verts[v].uv       = state->cube_shape.uvs[v];
        }
        state->cube_vb = forge_scene_upload_buffer(
            &state->scene, SDL_GPU_BUFFERUSAGE_VERTEX,
            verts, vc * (Uint32)sizeof(ForgeSceneTexturedVertex));
        SDL_free(verts);
    }

    state->cube_ib = forge_scene_upload_buffer(
        &state->scene, SDL_GPU_BUFFERUSAGE_INDEX,
        state->cube_shape.indices,
        (Uint32)(state->cube_shape.index_count * sizeof(Uint32)));

    if (!state->cube_vb || !state->cube_ib) {
        SDL_Log("SDL_AppInit: buffer upload failed");
        return SDL_APP_FAILURE;
    }

    /* ── Load atlas texture + metadata ───────────────────────────────── */

    char atlas_png_buf[ASSET_PATH_SIZE];
    const char *atlas_png = asset_path(atlas_png_buf, sizeof(atlas_png_buf),
        base, "assets/atlas.png");
    if (!atlas_png) return SDL_APP_FAILURE;

    state->atlas_texture = load_texture(&state->scene, atlas_png);
    if (!state->atlas_texture) {
        SDL_Log("SDL_AppInit: failed to load atlas texture");
        return SDL_APP_FAILURE;
    }

    char atlas_json_buf[ASSET_PATH_SIZE];
    const char *atlas_json = asset_path(atlas_json_buf,
        sizeof(atlas_json_buf), base, "assets/atlas.json");
    if (!atlas_json) return SDL_APP_FAILURE;

    if (!forge_pipeline_load_atlas(atlas_json, &state->atlas_meta)) {
        SDL_Log("SDL_AppInit: failed to load atlas metadata");
        return SDL_APP_FAILURE;
    }
    SDL_Log("Atlas loaded: %dx%d, %d entries, %.1f%% utilization",
            state->atlas_meta.width, state->atlas_meta.height,
            state->atlas_meta.entry_count,
            state->atlas_meta.utilization * 100.0f);

    /* Build material → atlas entry index lookup table.  This avoids
     * per-frame string comparisons in the draw loop. */
    bool atlas_missing_entry = false;
    for (int i = 0; i < MATERIAL_COUNT; i++) {
        state->atlas_entry_idx[i] = -1;  /* -1 = not found */
        for (int j = 0; j < state->atlas_meta.entry_count; j++) {
            if (SDL_strcmp(state->atlas_meta.entries[j].name,
                          MATERIAL_NAMES[i]) == 0) {
                state->atlas_entry_idx[i] = j;
                break;
            }
        }
        if (state->atlas_entry_idx[i] < 0) {
            SDL_Log("SDL_AppInit: material '%s' not found in atlas",
                    MATERIAL_NAMES[i]);
            atlas_missing_entry = true;
        }
    }
    if (atlas_missing_entry) {
        SDL_Log("SDL_AppInit: atlas metadata is incomplete");
        return SDL_APP_FAILURE;
    }

    /* ── Load individual textures (for comparison mode) ──────────────── */

    for (int i = 0; i < MATERIAL_COUNT; i++) {
        char rel[REL_PATH_SIZE];
        SDL_snprintf(rel, sizeof(rel), "assets/materials/%s.png",
                     MATERIAL_NAMES[i]);
        char path[ASSET_PATH_SIZE];
        if (!asset_path(path, sizeof(path), base, rel))
            return SDL_APP_FAILURE;
        state->individual_textures[i] = load_texture(&state->scene, path);
        if (!state->individual_textures[i]) {
            SDL_Log("SDL_AppInit: failed to load '%s'", path);
            return SDL_APP_FAILURE;
        }
    }
    SDL_Log("Loaded %d individual textures", MATERIAL_COUNT);

    /* ── Create sampler ──────────────────────────────────────────────── */

    /* Clamp-to-edge prevents atlas bleeding at rect boundaries.
     * Linear filtering gives smooth textures at angles. */
    SDL_GPUSamplerCreateInfo si;
    SDL_zero(si);
    si.min_filter        = SDL_GPU_FILTER_LINEAR;
    si.mag_filter        = SDL_GPU_FILTER_LINEAR;
    si.mipmap_mode       = SDL_GPU_SAMPLERMIPMAPMODE_LINEAR;
    si.address_mode_u    = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    si.address_mode_v    = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    si.address_mode_w    = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE;
    si.max_anisotropy    = 1;
    si.min_lod           = 0.0f;
    si.max_lod           = SAMPLER_MAX_LOD;

    state->sampler = SDL_CreateGPUSampler(dev, &si);
    if (!state->sampler) {
        SDL_Log("SDL_AppInit: sampler creation failed: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    SDL_Log("Lesson 47 initialized: %d materials, atlas %dx%d",
            MATERIAL_COUNT, state->atlas_meta.width,
            state->atlas_meta.height);

    return SDL_APP_CONTINUE;
}

/* ═══════════════════════════════════════════════════════════════════════
 * SDL_AppEvent — Handle input: camera, mode toggle, quit
 * ═══════════════════════════════════════════════════════════════════════ */

SDL_AppResult SDL_AppEvent(void *appstate, SDL_Event *event)
{
    app_state *state = (app_state *)appstate;

    /* Let forge_scene handle camera, mouse capture, window resize, quit */
    SDL_AppResult r = forge_scene_handle_event(&state->scene, event);
    if (r != SDL_APP_CONTINUE) return r;

    if (event->type == SDL_EVENT_KEY_DOWN && !event->key.repeat) {
        switch (event->key.scancode) {
        case SDL_SCANCODE_TAB:
            /* Toggle between atlas and individual texture mode */
            state->use_atlas = !state->use_atlas;
            SDL_Log("Mode: %s", state->use_atlas ? "ATLAS" : "INDIVIDUAL");
            break;
        default:
            break;
        }
    }

    return SDL_APP_CONTINUE;
}

/* ═══════════════════════════════════════════════════════════════════════
 * SDL_AppIterate — Per-frame rendering: draw cubes, UI panel
 * ═══════════════════════════════════════════════════════════════════════ */

SDL_AppResult SDL_AppIterate(void *appstate)
{
    app_state *state = (app_state *)appstate;
    ForgeScene *s = &state->scene;

    /* Begin frame: acquire command buffer, update camera */
    if (!forge_scene_begin_frame(s)) return SDL_APP_CONTINUE;

    /* ── Shadow pass: draw cubes into the depth-only shadow map ───────── */
    forge_scene_begin_shadow_pass(s);
    {
        float grid_off_x = (GRID_COLS - 1) * CUBE_SPACING * 0.5f;
        float grid_off_z = (GRID_ROWS - 1) * CUBE_SPACING * 0.5f;
        for (int i = 0; i < MATERIAL_COUNT; i++) {
            int col = i % GRID_COLS;
            int row = i / GRID_COLS;
            float x = col * CUBE_SPACING - grid_off_x;
            float z = row * CUBE_SPACING - grid_off_z;
            float y = CUBE_HALF_SIZE;
            mat4 model = mat4_multiply(
                mat4_translate(vec3_create(x, y, z)),
                mat4_scale(vec3_create(CUBE_HALF_SIZE, CUBE_HALF_SIZE,
                                       CUBE_HALF_SIZE)));
            forge_scene_draw_shadow_textured_mesh(
                s, state->cube_vb, state->cube_ib,
                (Uint32)state->cube_shape.index_count, model);
        }
    }
    forge_scene_end_shadow_pass(s);

    /* Begin main render pass (draws sky gradient automatically). */
    forge_scene_begin_main_pass(s);
    forge_scene_draw_grid(s);

    /* ── Draw 30 textured cubes ──────────────────────────────────────── */

    /* Identity UV transform for non-atlas textures (no remap) */
    static const float UV_IDENTITY[4] = { 0.0f, 0.0f, 1.0f, 1.0f };

    /* Reset bind count for this frame */
    state->bind_count = 0;

    /* Center the grid so it's roughly centered at the origin */
    float grid_offset_x = (GRID_COLS - 1) * CUBE_SPACING * 0.5f;
    float grid_offset_z = (GRID_ROWS - 1) * CUBE_SPACING * 0.5f;

    for (int i = 0; i < MATERIAL_COUNT; i++) {
        int col = i % GRID_COLS;
        int row = i / GRID_COLS;

        /* Compute cube world position */
        float x = col * CUBE_SPACING - grid_offset_x;
        float z = row * CUBE_SPACING - grid_offset_z;
        float y = CUBE_HALF_SIZE;  /* sit on the ground plane */

        /* Model matrix: translate + scale to CUBE_HALF_SIZE */
        mat4 model = mat4_multiply(
            mat4_translate(vec3_create(x, y, z)),
            mat4_scale(vec3_create(CUBE_HALF_SIZE, CUBE_HALF_SIZE,
                                   CUBE_HALF_SIZE)));

        if (state->use_atlas) {
            /* Atlas mode: all 30 cubes sample from one texture.  Bind the
             * atlas texture once before the first cube, then draw each cube
             * without re-binding — this is the optimization atlas rendering
             * provides: 1 bind call instead of 30. */
            if (i == 0) {
                if (!forge_scene_bind_textured_resources(
                        s, state->atlas_texture, state->sampler)) {
                    break;  /* bind failed — skip all atlas draws */
                }
                state->bind_count = 1;
            }
            int idx = state->atlas_entry_idx[i];
            const float *uv_xform = UV_IDENTITY;
            float atlas_uv[4];
            if (idx >= 0) {
                ForgePipelineAtlasEntry *e = &state->atlas_meta.entries[idx];
                atlas_uv[0] = e->u_offset;
                atlas_uv[1] = e->v_offset;
                atlas_uv[2] = e->u_scale;
                atlas_uv[3] = e->v_scale;
                uv_xform = atlas_uv;
            }
            forge_scene_draw_textured_mesh_no_bind(
                s, state->cube_vb, state->cube_ib,
                (Uint32)state->cube_shape.index_count,
                model, uv_xform);
        } else {
            /* Individual mode: each cube binds its own texture */
            forge_scene_draw_textured_mesh(
                s, state->cube_vb, state->cube_ib,
                (Uint32)state->cube_shape.index_count,
                model, state->individual_textures[i], state->sampler,
                UV_IDENTITY);
            state->bind_count++;
        }
    }

    forge_scene_end_main_pass(s);

    /* ── UI panel ────────────────────────────────────────────────────── */

    float mx, my;
    Uint32 buttons = SDL_GetMouseState(&mx, &my);
    bool mouse_down = !s->mouse_captured && (buttons & SDL_BUTTON_LMASK);

    forge_scene_begin_ui(s, mx, my, mouse_down);
    {
        ForgeUiWindowContext *wctx = forge_scene_window_ui(s);
        if (wctx) {
            if (forge_ui_wctx_window_begin(wctx, "Texture Atlas",
                                           &state->ui_window)) {
                ForgeUiContext *ui = wctx->ctx;
                char buf[128];

                /* Current mode */
                SDL_snprintf(buf, sizeof(buf), "Mode: %s",
                             state->use_atlas ? "ATLAS" : "INDIVIDUAL");
                forge_ui_ctx_label_layout(ui, buf, UI_LABEL_H);

                /* Unique textures used this frame */
                SDL_snprintf(buf, sizeof(buf), "Unique textures: %d",
                             state->bind_count);
                forge_ui_ctx_label_layout(ui, buf, UI_LABEL_H);

                /* Draw calls (always 30 — one per cube) */
                SDL_snprintf(buf, sizeof(buf), "Draw calls: %d",
                             MATERIAL_COUNT);
                forge_ui_ctx_label_layout(ui, buf, UI_LABEL_H);

                /* Atlas dimensions and utilization */
                SDL_snprintf(buf, sizeof(buf), "Atlas: %dx%d (%.0f%% used)",
                             state->atlas_meta.width,
                             state->atlas_meta.height,
                             state->atlas_meta.utilization * 100.0f);
                forge_ui_ctx_label_layout(ui, buf, UI_LABEL_H);

                /* Material count */
                SDL_snprintf(buf, sizeof(buf), "Materials: %d",
                             state->atlas_meta.entry_count);
                forge_ui_ctx_label_layout(ui, buf, UI_LABEL_H);

                /* Instructions */
                forge_ui_ctx_label_layout(ui, "Tab: toggle mode",
                                          UI_LABEL_H);

                forge_ui_wctx_window_end(wctx);
            }
        }
    }
    forge_scene_end_ui(s);

    return forge_scene_end_frame(s);
}

/* ═══════════════════════════════════════════════════════════════════════
 * SDL_AppQuit — Release all resources in reverse order
 * ═══════════════════════════════════════════════════════════════════════ */

void SDL_AppQuit(void *appstate, SDL_AppResult result)
{
    (void)result;
    if (!appstate) return;

    app_state *state = (app_state *)appstate;
    SDL_GPUDevice *dev = forge_scene_device(&state->scene);

    if (dev) {
        SDL_WaitForGPUIdle(dev);

        /* Release sampler */
        if (state->sampler)
            SDL_ReleaseGPUSampler(dev, state->sampler);

        /* Release atlas texture */
        if (state->atlas_texture)
            SDL_ReleaseGPUTexture(dev, state->atlas_texture);

        /* Release individual textures */
        for (int i = 0; i < MATERIAL_COUNT; i++) {
            if (state->individual_textures[i])
                SDL_ReleaseGPUTexture(dev, state->individual_textures[i]);
        }

        /* Release geometry buffers */
        if (state->cube_vb) SDL_ReleaseGPUBuffer(dev, state->cube_vb);
        if (state->cube_ib) SDL_ReleaseGPUBuffer(dev, state->cube_ib);
    }

    /* Release CPU-side resources */
    forge_pipeline_free_atlas(&state->atlas_meta);
    forge_shapes_free(&state->cube_shape);

    /* Destroy scene (releases device, window, all scene resources) */
    forge_scene_destroy(&state->scene);

    SDL_free(state);
}
