/* Auto-generated from triangle.vert.msl -- do not edit by hand. */
static const char triangle_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_Uniforms\n"
    "{\n"
    "    float time;\n"
    "    float aspect;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_Uniforms& Uniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float _30 = cos(Uniforms.time);\n"
    "    float _31 = sin(Uniforms.time);\n"
    "    out.gl_Position = float4(((in.in_var_TEXCOORD0.x * _30) - (in.in_var_TEXCOORD0.y * _31)) / Uniforms.aspect, (in.in_var_TEXCOORD0.x * _31) + (in.in_var_TEXCOORD0.y * _30), 0.0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = float4(in.in_var_TEXCOORD1, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int triangle_vert_msl_size = sizeof(triangle_vert_msl) - 1;
