/* Auto-generated from instanced.frag.msl -- do not edit by hand. */
static const char instanced_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    uint has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _62;\n"
    "    if (FragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _62 = diffuse_tex.sample(smp, in.in_var_TEXCOORD0) * FragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _62 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _63 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _67 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    out.out_var_SV_Target = float4(((_62.xyz * FragUniforms.ambient) + (_62.xyz * precise::max(dot(_63, _67), 0.0))) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_63, fast::normalize(_67 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), FragUniforms.shininess))), _62.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int instanced_frag_msl_size = sizeof(instanced_frag_msl) - 1;
