/* Auto-generated from instanced.vert.msl -- do not edit by hand. */
static const char instanced_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "    float4 in_var_TEXCOORD4 [[attribute(4)]];\n"
    "    float4 in_var_TEXCOORD5 [[attribute(5)]];\n"
    "    float4 in_var_TEXCOORD6 [[attribute(6)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4x4 _44 = transpose(float4x4(in.in_var_TEXCOORD3, in.in_var_TEXCOORD4, in.in_var_TEXCOORD5, in.in_var_TEXCOORD6));\n"
    "    float4 _49 = float4(in.in_var_TEXCOORD0, 1.0) * _44;\n"
    "    float3 _55 = _44[0].xyz;\n"
    "    float3 _57 = _44[1].xyz;\n"
    "    float3 _59 = _44[2].xyz;\n"
    "    out.gl_Position = VertUniforms.vp * _49;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD1 = in.in_var_TEXCOORD1 * float3x3(cross(_57, _59), cross(_59, _55), cross(_55, _57));\n"
    "    out.out_var_TEXCOORD2 = _49.xyz;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int instanced_vert_msl_size = sizeof(instanced_vert_msl) - 1;
