/* Auto-generated from ui.vert.msl -- do not edit by hand. */
static const char ui_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_UiUniforms\n"
    "{\n"
    "    float4x4 projection;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float2 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float2 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_UiUniforms& UiUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = UiUniforms.projection * float4(in.in_var_TEXCOORD0, 0.0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD1;\n"
    "    out.out_var_TEXCOORD1 = float4(in.in_var_TEXCOORD2, in.in_var_TEXCOORD3);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int ui_vert_msl_size = sizeof(ui_vert_msl) - 1;
