/* Auto-generated from debug.vert.msl -- do not edit by hand. */
static const char debug_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_DebugUniforms\n"
    "{\n"
    "    float4x4 view_projection;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float4 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_DebugUniforms& DebugUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = DebugUniforms.view_projection * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD1;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int debug_vert_msl_size = sizeof(debug_vert_msl) - 1;
