/* Auto-generated from scene_model.frag.msl -- do not edit by hand. */
static const char scene_model_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4 base_color_factor;\n"
    "    packed_float3 emissive_factor;\n"
    "    float shadow_texel;\n"
    "    float metallic_factor;\n"
    "    float roughness_factor;\n"
    "    float normal_scale;\n"
    "    float occlusion_strength;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float alpha_cutoff;\n"
    "    float ambient;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float3 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 in_var_TEXCOORD5 [[user(locn5)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> base_color_tex [[texture(0)]], texture2d<float> normal_tex [[texture(1)]], texture2d<float> mr_tex [[texture(2)]], texture2d<float> occlusion_tex [[texture(3)]], texture2d<float> emissive_tex [[texture(4)]], depth2d<float> shadow_map [[texture(5)]], sampler base_color_smp [[sampler(0)]], sampler normal_smp [[sampler(1)]], sampler mr_smp [[sampler(2)]], sampler occlusion_smp [[sampler(3)]], sampler emissive_smp [[sampler(4)]], sampler shadow_sampler [[sampler(5)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _92 = base_color_tex.sample(base_color_smp, in.in_var_TEXCOORD2);\n"
    "    float4 _95 = _92 * FragUniforms.base_color_factor;\n"
    "    bool _103;\n"
    "    if (FragUniforms.alpha_cutoff > 0.0)\n"
    "    {\n"
    "        _103 = _95.w < FragUniforms.alpha_cutoff;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _103 = false;\n"
    "    }\n"
    "    if (_103)\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    float4 _112 = normal_tex.sample(normal_smp, in.in_var_TEXCOORD2);\n"
    "    float2 _118 = ((_112.xy * 2.0) - float2(1.0)) * FragUniforms.normal_scale;\n"
    "    float3 _129 = fast::normalize(float3x3(fast::normalize(in.in_var_TEXCOORD3), fast::normalize(in.in_var_TEXCOORD4), fast::normalize(in.in_var_TEXCOORD1)) * fast::normalize(float3(_118, sqrt(fast::clamp(1.0 - dot(_118, _118), 0.0, 1.0)))));\n"
    "    float4 _133 = mr_tex.sample(mr_smp, in.in_var_TEXCOORD2);\n"
    "    float _137 = _133.z * FragUniforms.metallic_factor;\n"
    "    float4 _145 = occlusion_tex.sample(occlusion_smp, in.in_var_TEXCOORD2);\n"
    "    float4 _155 = emissive_tex.sample(emissive_smp, in.in_var_TEXCOORD2);\n"
    "    float3 _163 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _175 = _95.xyz;\n"
    "    float3 _178 = _175 * (1.0 - (_137 * 0.699999988079071044921875));\n"
    "    float _179 = 1.0 - (_133.y * FragUniforms.roughness_factor);\n"
    "    float _302;\n"
    "    do\n"
    "    {\n"
    "        float3 _202 = in.in_var_TEXCOORD5.xyz / float3(in.in_var_TEXCOORD5.w);\n"
    "        float2 _205 = (_202.xy * 0.5) + float2(0.5);\n"
    "        float _207 = 1.0 - _205.y;\n"
    "        float2 _208 = _205;\n"
    "        _208.y = _207;\n"
    "        float _209 = _202.z;\n"
    "        float _210 = _205.x;\n"
    "        bool _215;\n"
    "        if ((isunordered(_210, 0.0) || _210 >= 0.0))\n"
    "        {\n"
    "            _215 = _210 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _215 = true;\n"
    "        }\n"
    "        bool _220;\n"
    "        if (!_215)\n"
    "        {\n"
    "            _220 = _207 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _220 = true;\n"
    "        }\n"
    "        bool _225;\n"
    "        if (!_220)\n"
    "        {\n"
    "            _225 = _207 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _225 = true;\n"
    "        }\n"
    "        bool _230;\n"
    "        if (!_225)\n"
    "        {\n"
    "            _230 = _209 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _230 = true;\n"
    "        }\n"
    "        bool _235;\n"
    "        if (!_230)\n"
    "        {\n"
    "            _235 = _209 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _235 = true;\n"
    "        }\n"
    "        if (_235)\n"
    "        {\n"
    "            _302 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _244 = _209 - 0.004999999888241291046142578125;\n"
    "        _302 = ((((((((shadow_map.sample_compare(shadow_sampler, (_208 + (float2(-1.0) * FragUniforms.shadow_texel)), _244, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(0.0, -1.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(1.0, -1.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(-1.0, 0.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _208, _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(1.0, 0.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(-1.0, 1.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(0.0, 1.0) * FragUniforms.shadow_texel)), _244, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_208 + (float2(1.0) * FragUniforms.shadow_texel)), _244, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((((_178 * FragUniforms.ambient) * (1.0 + (FragUniforms.occlusion_strength * (_145.x - 1.0)))) + (((_178 * precise::max(dot(_129, _163), 0.0)) + (mix(float3(1.0), _175, float3(_137)) * ((FragUniforms.specular_str * _179) * powr(precise::max(dot(_129, fast::normalize(_163 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess * precise::max(_179, 0.039999999105930328369140625))))) * _302)) + (_155.xyz * float3(FragUniforms.emissive_factor)), _95.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_model_frag_msl_size = sizeof(scene_model_frag_msl) - 1;
