/* Auto-generated from scene_morph_shadow.vert.msl -- do not edit by hand. */
static const char scene_morph_shadow_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_ShadowUniforms\n"
    "{\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct type_StructuredBuffer_v4float\n"
    "{\n"
    "    float4 _m0[1];\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_ShadowUniforms& ShadowUniforms [[buffer(0)]], const device type_StructuredBuffer_v4float& morph_pos_deltas [[buffer(1)]], uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowUniforms.light_vp * float4(in.in_var_TEXCOORD0 + morph_pos_deltas._m0[gl_VertexIndex].xyz, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_morph_shadow_vert_msl_size = sizeof(scene_morph_shadow_vert_msl) - 1;
