/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float2 _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _57 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float3 _66 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _78 = fast::normalize(SceneFragUniforms.light_dir.xyz);\n"
    "    float _144;\n"
    "    do\n"
    "    {\n"
    "        float3 _97 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _100 = (_97.xy * 0.5) + float2(0.5);\n"
    "        float _102 = 1.0 - _100.y;\n"
    "        float2 _103 = _100;\n"
    "        _103.y = _102;\n"
    "        float _104 = _100.x;\n"
    "        bool _109;\n"
    "        if ((isunordered(_104, 0.0) || _104 >= 0.0))\n"
    "        {\n"
    "            _109 = _104 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _109 = true;\n"
    "        }\n"
    "        bool _114;\n"
    "        if (!_109)\n"
    "        {\n"
    "            _114 = _102 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _114 = true;\n"
    "        }\n"
    "        bool _119;\n"
    "        if (!_114)\n"
    "        {\n"
    "            _119 = _102 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _119 = true;\n"
    "        }\n"
    "        if (_119)\n"
    "        {\n"
    "            _144 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _122 = _97.z;\n"
    "        float _124;\n"
    "        _124 = 0.0;\n"
    "        for (int _127 = 0; _127 < 4; )\n"
    "        {\n"
    "            _124 += float((_122 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_103 + (_57[_127] * float2(0.00048828125)))).x);\n"
    "            _127++;\n"
    "            continue;\n"
    "        }\n"
    "        _144 = _124 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((SceneFragUniforms.base_color.xyz * SceneFragUniforms.ambient) + (((((SceneFragUniforms.base_color.xyz * precise::max(dot(_66, _78), 0.0)) + float3(SceneFragUniforms.specular_str * powr(precise::max(dot(_66, fast::normalize(_78 + fast::normalize(float3(SceneFragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), SceneFragUniforms.shininess))) * SceneFragUniforms.light_intensity) * float3(SceneFragUniforms.light_color)) * _144), SceneFragUniforms.base_color.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
