/* Auto-generated from scene_textured.frag.msl -- do not edit by hand. */
static const char scene_textured_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_SceneTexturedFragUniforms\n"
    "{\n"
    "    float4 uv_transform;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float2 _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _63 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float2 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneTexturedFragUniforms& SceneTexturedFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], texture2d<float> material_tex [[texture(1)]], sampler shadow_smp [[sampler(0)]], sampler material_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _81 = material_tex.sample(material_smp, ((fast::clamp(in.in_var_TEXCOORD3, float2(0.0), float2(1.0)) * SceneTexturedFragUniforms.uv_transform.zw) + SceneTexturedFragUniforms.uv_transform.xy));\n"
    "    float3 _82 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _87 = _81.xyz;\n"
    "    float3 _94 = fast::normalize(SceneTexturedFragUniforms.light_dir.xyz);\n"
    "    float _159;\n"
    "    do\n"
    "    {\n"
    "        float3 _112 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _115 = (_112.xy * 0.5) + float2(0.5);\n"
    "        float _117 = 1.0 - _115.y;\n"
    "        float2 _118 = _115;\n"
    "        _118.y = _117;\n"
    "        float _119 = _115.x;\n"
    "        bool _124;\n"
    "        if ((isunordered(_119, 0.0) || _119 >= 0.0))\n"
    "        {\n"
    "            _124 = _119 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _124 = true;\n"
    "        }\n"
    "        bool _129;\n"
    "        if (!_124)\n"
    "        {\n"
    "            _129 = _117 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _129 = true;\n"
    "        }\n"
    "        bool _134;\n"
    "        if (!_129)\n"
    "        {\n"
    "            _134 = _117 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        if (_134)\n"
    "        {\n"
    "            _159 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _137 = _112.z;\n"
    "        float _139;\n"
    "        _139 = 0.0;\n"
    "        for (int _142 = 0; _142 < 4; )\n"
    "        {\n"
    "            _139 += float((_137 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_118 + (_63[_142] * float2(0.00048828125)))).x);\n"
    "            _142++;\n"
    "            continue;\n"
    "        }\n"
    "        _159 = _139 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((_87 * SceneTexturedFragUniforms.ambient) + (((((_87 * precise::max(dot(_82, _94), 0.0)) + float3(SceneTexturedFragUniforms.specular_str * powr(precise::max(dot(_82, fast::normalize(_94 + fast::normalize(float3(SceneTexturedFragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), SceneTexturedFragUniforms.shininess))) * SceneTexturedFragUniforms.light_intensity) * float3(SceneTexturedFragUniforms.light_color)) * _159), _81.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_textured_frag_msl_size = sizeof(scene_textured_frag_msl) - 1;
