/* Auto-generated from scene_instanced.vert.msl -- do not edit by hand. */
static const char scene_instanced_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_InstancedVertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "    float4x4 light_vp;\n"
    "    float4x4 node_world;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float4 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "    float4 in_var_TEXCOORD4 [[attribute(4)]];\n"
    "    float4 in_var_TEXCOORD5 [[attribute(5)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_InstancedVertUniforms& InstancedVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4x4 _41 = transpose(float4x4(in.in_var_TEXCOORD2, in.in_var_TEXCOORD3, in.in_var_TEXCOORD4, in.in_var_TEXCOORD5));\n"
    "    float4 _49 = (InstancedVertUniforms.node_world * float4(in.in_var_TEXCOORD0, 1.0)) * _41;\n"
    "    float3x3 _68 = float3x3(float4(InstancedVertUniforms.node_world[0][0], InstancedVertUniforms.node_world[1][0], InstancedVertUniforms.node_world[2][0], InstancedVertUniforms.node_world[3][0]).xyz, float4(InstancedVertUniforms.node_world[0][1], InstancedVertUniforms.node_world[1][1], InstancedVertUniforms.node_world[2][1], InstancedVertUniforms.node_world[3][1]).xyz, float4(InstancedVertUniforms.node_world[0][2], InstancedVertUniforms.node_world[1][2], InstancedVertUniforms.node_world[2][2], InstancedVertUniforms.node_world[3][2]).xyz) * float3x3(_41[0].xyz, _41[1].xyz, _41[2].xyz);\n"
    "    float3 _69 = _68[1];\n"
    "    float3 _70 = _68[2];\n"
    "    float3 _72 = _68[0];\n"
    "    out.gl_Position = InstancedVertUniforms.vp * _49;\n"
    "    out.out_var_TEXCOORD0 = _49.xyz;\n"
    "    out.out_var_TEXCOORD1 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(cross(_69, _70), cross(_70, _72), cross(_72, _69)));\n"
    "    out.out_var_TEXCOORD2 = InstancedVertUniforms.light_vp * _49;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_instanced_vert_msl_size = sizeof(scene_instanced_vert_msl) - 1;
