/* Auto-generated from scene_instanced_colored.frag.msl -- do not edit by hand. */
static const char scene_instanced_colored_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float2 _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _58 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _68 = SceneFragUniforms.base_color * in.in_var_TEXCOORD3;\n"
    "    float3 _69 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _74 = _68.xyz;\n"
    "    float3 _81 = fast::normalize(SceneFragUniforms.light_dir.xyz);\n"
    "    float _147;\n"
    "    do\n"
    "    {\n"
    "        float3 _100 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _103 = (_100.xy * 0.5) + float2(0.5);\n"
    "        float _105 = 1.0 - _103.y;\n"
    "        float2 _106 = _103;\n"
    "        _106.y = _105;\n"
    "        float _107 = _103.x;\n"
    "        bool _112;\n"
    "        if ((isunordered(_107, 0.0) || _107 >= 0.0))\n"
    "        {\n"
    "            _112 = _107 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _112 = true;\n"
    "        }\n"
    "        bool _117;\n"
    "        if (!_112)\n"
    "        {\n"
    "            _117 = _105 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _117 = true;\n"
    "        }\n"
    "        bool _122;\n"
    "        if (!_117)\n"
    "        {\n"
    "            _122 = _105 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _122 = true;\n"
    "        }\n"
    "        if (_122)\n"
    "        {\n"
    "            _147 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _125 = _100.z;\n"
    "        float _127;\n"
    "        _127 = 0.0;\n"
    "        for (int _130 = 0; _130 < 4; )\n"
    "        {\n"
    "            _127 += float((_125 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_106 + (_58[_130] * float2(0.00048828125)))).x);\n"
    "            _130++;\n"
    "            continue;\n"
    "        }\n"
    "        _147 = _127 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((_74 * SceneFragUniforms.ambient) + (((((_74 * precise::max(dot(_69, _81), 0.0)) + float3(SceneFragUniforms.specular_str * powr(precise::max(dot(_69, fast::normalize(_81 + fast::normalize(float3(SceneFragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), SceneFragUniforms.shininess))) * SceneFragUniforms.light_intensity) * float3(SceneFragUniforms.light_color)) * _147), _68.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_instanced_colored_frag_msl_size = sizeof(scene_instanced_colored_frag_msl) - 1;
