/* Auto-generated from scene_instanced_shadow.vert.msl -- do not edit by hand. */
static const char scene_instanced_shadow_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_ShadowUniforms\n"
    "{\n"
    "    float4x4 light_vp;\n"
    "    float4x4 node_world;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float4 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float4 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "    float4 in_var_TEXCOORD4 [[attribute(4)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_ShadowUniforms& ShadowUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowUniforms.light_vp * ((ShadowUniforms.node_world * float4(in.in_var_TEXCOORD0, 1.0)) * transpose(float4x4(in.in_var_TEXCOORD1, in.in_var_TEXCOORD2, in.in_var_TEXCOORD3, in.in_var_TEXCOORD4)));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_instanced_shadow_vert_msl_size = sizeof(scene_instanced_shadow_vert_msl) - 1;
