/* Auto-generated from scene_model_instanced.vert.msl -- do not edit by hand. */
static const char scene_model_instanced_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_InstancedVertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "    float4x4 light_vp;\n"
    "    float4x4 node_world;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float3 out_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 out_var_TEXCOORD5 [[user(locn5)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "    float4 in_var_TEXCOORD4 [[attribute(4)]];\n"
    "    float4 in_var_TEXCOORD5 [[attribute(5)]];\n"
    "    float4 in_var_TEXCOORD6 [[attribute(6)]];\n"
    "    float4 in_var_TEXCOORD7 [[attribute(7)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_InstancedVertUniforms& InstancedVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4x4 _51 = transpose(float4x4(in.in_var_TEXCOORD4, in.in_var_TEXCOORD5, in.in_var_TEXCOORD6, in.in_var_TEXCOORD7));\n"
    "    float4 _59 = (InstancedVertUniforms.node_world * float4(in.in_var_TEXCOORD0, 1.0)) * _51;\n"
    "    float3x3 _81 = float3x3(float4(InstancedVertUniforms.node_world[0][0], InstancedVertUniforms.node_world[1][0], InstancedVertUniforms.node_world[2][0], InstancedVertUniforms.node_world[3][0]).xyz, float4(InstancedVertUniforms.node_world[0][1], InstancedVertUniforms.node_world[1][1], InstancedVertUniforms.node_world[2][1], InstancedVertUniforms.node_world[3][1]).xyz, float4(InstancedVertUniforms.node_world[0][2], InstancedVertUniforms.node_world[1][2], InstancedVertUniforms.node_world[2][2], InstancedVertUniforms.node_world[3][2]).xyz) * float3x3(_51[0].xyz, _51[1].xyz, _51[2].xyz);\n"
    "    float3 _82 = _81[1];\n"
    "    float3 _83 = _81[2];\n"
    "    float3 _85 = _81[0];\n"
    "    float3 _90 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(cross(_82, _83), cross(_83, _85), cross(_85, _82)));\n"
    "    float3 _93 = fast::normalize(in.in_var_TEXCOORD3.xyz * _81);\n"
    "    float3 _97 = fast::normalize(_93 - (_90 * dot(_90, _93)));\n"
    "    out.gl_Position = InstancedVertUniforms.vp * _59;\n"
    "    out.out_var_TEXCOORD0 = _59.xyz;\n"
    "    out.out_var_TEXCOORD1 = _90;\n"
    "    out.out_var_TEXCOORD2 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD3 = _97;\n"
    "    out.out_var_TEXCOORD4 = cross(_90, _97) * in.in_var_TEXCOORD3.w;\n"
    "    out.out_var_TEXCOORD5 = InstancedVertUniforms.light_vp * _59;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_model_instanced_vert_msl_size = sizeof(scene_model_instanced_vert_msl) - 1;
