/* Auto-generated from shadow_mask.vert.msl -- do not edit by hand. */
static const char shadow_mask_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_ShadowUniforms\n"
    "{\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_ShadowUniforms& ShadowUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = ShadowUniforms.light_vp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD2;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_mask_vert_msl_size = sizeof(shadow_mask_vert_msl) - 1;
