/* Auto-generated from shadow_mask.frag.msl -- do not edit by hand. */
static const char shadow_mask_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_MaskUniforms\n"
    "{\n"
    "    float4 base_color_factor;\n"
    "    float alpha_cutoff;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_MaskUniforms& MaskUniforms [[buffer(0)]], texture2d<float> base_color_tex [[texture(0)]], sampler base_color_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    if ((base_color_tex.sample(base_color_smp, in.in_var_TEXCOORD0).w * MaskUniforms.base_color_factor.w) < MaskUniforms.alpha_cutoff)\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(0.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_mask_frag_msl_size = sizeof(shadow_mask_frag_msl) - 1;
