/* Auto-generated from decal.frag.msl -- do not edit by hand. */
static const char decal_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_DecalFragUniforms\n"
    "{\n"
    "    float4x4 inv_vp;\n"
    "    float4x4 inv_decal_model;\n"
    "    float4x4 light_vp;\n"
    "    float2 screen_size;\n"
    "    float near_plane;\n"
    "    float far_plane;\n"
    "    float4 decal_tint;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    packed_float3 light_dir;\n"
    "    float light_intensity;\n"
    "    packed_float3 light_color;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    packed_float3 _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _76 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(constant type_DecalFragUniforms& DecalFragUniforms [[buffer(0)]], texture2d<float> depth_tex [[texture(0)]], texture2d<float> decal_tex [[texture(1)]], texture2d<float> shadow_tex [[texture(2)]], texture2d<float> normal_tex [[texture(3)]], sampler depth_smp [[sampler(0)]], sampler decal_smp [[sampler(1)]], sampler shadow_smp [[sampler(2)]], sampler normal_smp [[sampler(3)]], float4 gl_FragCoord [[position]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _85 = gl_FragCoord.xy / DecalFragUniforms.screen_size;\n"
    "    float4 _89 = depth_tex.sample(depth_smp, _85);\n"
    "    float _90 = _89.x;\n"
    "    if (_90 >= 0.99989998340606689453125)\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    float2 _95 = (_85 * 2.0) - float2(1.0);\n"
    "    float4 _102 = DecalFragUniforms.inv_vp * float4(_95.x, -_95.y, _90, 1.0);\n"
    "    float3 _106 = _102.xyz / float3(_102.w);\n"
    "    float4 _112 = float4(_106, 1.0);\n"
    "    float4 _113 = DecalFragUniforms.inv_decal_model * _112;\n"
    "    if (any(abs(_113.xyz) > float3(0.5)))\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    float4 _125 = decal_tex.sample(decal_smp, (_113.xz + float2(0.5)));\n"
    "    float4 _128 = _125 * DecalFragUniforms.decal_tint;\n"
    "    float _141 = _128.w * ((smoothstep(0.5, 0.4000000059604644775390625, abs(_113.x)) * smoothstep(0.5, 0.4000000059604644775390625, abs(_113.y))) * smoothstep(0.5, 0.4000000059604644775390625, abs(_113.z)));\n"
    "    if (_141 < 0.00999999977648258209228515625)\n"
    "    {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    float4 _148 = normal_tex.sample(normal_smp, _85);\n"
    "    float3 _152 = fast::normalize((_148.xyz * 2.0) - float3(1.0));\n"
    "    float3 _160 = fast::normalize(-float3(DecalFragUniforms.light_dir));\n"
    "    float3 _161 = _128.xyz;\n"
    "    float _233;\n"
    "    do\n"
    "    {\n"
    "        float4 _182 = DecalFragUniforms.light_vp * _112;\n"
    "        float3 _186 = _182.xyz / float3(_182.w);\n"
    "        float2 _189 = (_186.xy * 0.5) + float2(0.5);\n"
    "        float _191 = 1.0 - _189.y;\n"
    "        float2 _192 = _189;\n"
    "        _192.y = _191;\n"
    "        float _193 = _189.x;\n"
    "        bool _198;\n"
    "        if ((isunordered(_193, 0.0) || _193 >= 0.0))\n"
    "        {\n"
    "            _198 = _193 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _198 = true;\n"
    "        }\n"
    "        bool _203;\n"
    "        if (!_198)\n"
    "        {\n"
    "            _203 = _191 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _203 = true;\n"
    "        }\n"
    "        bool _208;\n"
    "        if (!_203)\n"
    "        {\n"
    "            _208 = _191 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _208 = true;\n"
    "        }\n"
    "        if (_208)\n"
    "        {\n"
    "            _233 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _211 = _186.z;\n"
    "        float _213;\n"
    "        _213 = 0.0;\n"
    "        for (int _216 = 0; _216 < 4; )\n"
    "        {\n"
    "            _213 += float((_211 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_192 + (_76[_216] * float2(0.00048828125)))).x);\n"
    "            _216++;\n"
    "            continue;\n"
    "        }\n"
    "        _233 = _213 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_161 * DecalFragUniforms.ambient) + (((((_161 * precise::max(dot(_152, _160), 0.0)) + float3(DecalFragUniforms.specular_str * powr(precise::max(dot(_152, fast::normalize(_160 + fast::normalize(float3(DecalFragUniforms.eye_pos) - _106))), 0.0), DecalFragUniforms.shininess))) * DecalFragUniforms.light_intensity) * float3(DecalFragUniforms.light_color)) * _233), _141);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int decal_frag_msl_size = sizeof(decal_frag_msl) - 1;
