/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 light_dir;\n"
    "    float light_intensity;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _61 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _71 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _76 = fwidth(_71);\n"
    "    float2 _79 = float2(GridFragUniforms.line_width);\n"
    "    float2 _82 = float2(1.0) - smoothstep(_79, _79 + _76, abs(fract(_71 - float2(0.5)) - float2(0.5)));\n"
    "    float _168;\n"
    "    do\n"
    "    {\n"
    "        float3 _121 = in.in_var_TEXCOORD1.xyz / float3(in.in_var_TEXCOORD1.w);\n"
    "        float2 _124 = (_121.xy * 0.5) + float2(0.5);\n"
    "        float _126 = 1.0 - _124.y;\n"
    "        float2 _127 = _124;\n"
    "        _127.y = _126;\n"
    "        float _128 = _124.x;\n"
    "        bool _133;\n"
    "        if ((isunordered(_128, 0.0) || _128 >= 0.0))\n"
    "        {\n"
    "            _133 = _128 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _133 = true;\n"
    "        }\n"
    "        bool _138;\n"
    "        if (!_133)\n"
    "        {\n"
    "            _138 = _126 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _138 = true;\n"
    "        }\n"
    "        bool _143;\n"
    "        if (!_138)\n"
    "        {\n"
    "            _143 = _126 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _143 = true;\n"
    "        }\n"
    "        if (_143)\n"
    "        {\n"
    "            _168 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _146 = _121.z;\n"
    "        float _148;\n"
    "        _148 = 0.0;\n"
    "        for (int _151 = 0; _151 < 4; )\n"
    "        {\n"
    "            _148 += float((_146 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_127 + (_61[_151] * float2(0.00048828125)))).x);\n"
    "            _151++;\n"
    "            continue;\n"
    "        }\n"
    "        _168 = _148 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4(mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_82.x, _82.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_76.x, _76.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(GridFragUniforms.eye_pos)))))) * (GridFragUniforms.ambient + ((precise::max(fast::normalize(-float3(GridFragUniforms.light_dir)).y, 0.0) * GridFragUniforms.light_intensity) * _168)), 1.0);\n"
    "    out.out_var_SV_Target1 = float4(0.5, 1.0, 0.5, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
