/* Auto-generated from shuttle.frag.msl -- do not edit by hand. */
static const char shuttle_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    uint has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float reflectivity;\n"
    "    packed_float3 _padding;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texturecube<float> env_tex [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler env_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _68;\n"
    "    if (FragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _68 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0) * FragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _68 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _69 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _73 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _78 = fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2);\n"
    "    float3 _90 = mix(_68.xyz, env_tex.sample(env_smp, reflect(-_78, _69)).xyz, float3(FragUniforms.reflectivity));\n"
    "    out.out_var_SV_Target = float4(((_90 * FragUniforms.ambient) + (_90 * precise::max(dot(_69, _73), 0.0))) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_69, fast::normalize(_73 + _78)), 0.0), FragUniforms.shininess))), _68.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shuttle_frag_msl_size = sizeof(shuttle_frag_msl) - 1;
