/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    uint has_texture;\n"
    "    uint _pad0;\n"
    "    uint _pad1;\n"
    "    uint _pad2;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _48;\n"
    "    do\n"
    "    {\n"
    "        if (FragUniforms.has_texture != 0u)\n"
    "        {\n"
    "            _48 = diffuse_tex.sample(smp, in.in_var_TEXCOORD0) * FragUniforms.base_color;\n"
    "            break;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _48 = FragUniforms.base_color;\n"
    "            break;\n"
    "        }\n"
    "        break; // unreachable workaround\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = _48;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
