/* Auto-generated from composite.frag.msl -- do not edit by hand. */
static const char composite_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_CompositeParams\n"
    "{\n"
    "    int display_mode;\n"
    "    float reflection_str;\n"
    "    float2 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_CompositeParams& CompositeParams [[buffer(0)]], texture2d<float> color_tex [[texture(0)]], texture2d<float> ssr_tex [[texture(1)]], texture2d<float> depth_tex [[texture(2)]], texture2d<float> normal_tex [[texture(3)]], texture2d<float> wpos_tex [[texture(4)]], sampler color_smp [[sampler(0)]], sampler ssr_smp [[sampler(1)]], sampler depth_smp [[sampler(2)]], sampler normal_smp [[sampler(3)]], sampler wpos_smp [[sampler(4)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _133;\n"
    "    do\n"
    "    {\n"
    "        float4 _56 = color_tex.sample(color_smp, in.in_var_TEXCOORD0);\n"
    "        float4 _61 = ssr_tex.sample(ssr_smp, in.in_var_TEXCOORD0);\n"
    "        if (CompositeParams.display_mode == 0)\n"
    "        {\n"
    "            _133 = float4(mix(_56.xyz, _61.xyz, float3(_61.w * CompositeParams.reflection_str)), 1.0);\n"
    "            break;\n"
    "        }\n"
    "        if (CompositeParams.display_mode == 1)\n"
    "        {\n"
    "            _133 = float4(_61.xyz * _61.w, 1.0);\n"
    "            break;\n"
    "        }\n"
    "        if (CompositeParams.display_mode == 2)\n"
    "        {\n"
    "            _133 = float4((normal_tex.sample(normal_smp, in.in_var_TEXCOORD0).xyz * 0.5) + float3(0.5), 1.0);\n"
    "            break;\n"
    "        }\n"
    "        if (CompositeParams.display_mode == 3)\n"
    "        {\n"
    "            float _113 = fast::clamp(0.100000001490116119384765625 / (500.0 - (depth_tex.sample(depth_smp, in.in_var_TEXCOORD0).x * 499.899993896484375)), 0.0, 1.0);\n"
    "            _133 = float4(_113, _113, _113, 1.0);\n"
    "            break;\n"
    "        }\n"
    "        if (CompositeParams.display_mode == 4)\n"
    "        {\n"
    "            _133 = float4(fract(wpos_tex.sample(wpos_smp, in.in_var_TEXCOORD0).xyz * 0.100000001490116119384765625), 1.0);\n"
    "            break;\n"
    "        }\n"
    "        _133 = float4(_56.xyz, 1.0);\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = _133;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int composite_frag_msl_size = sizeof(composite_frag_msl) - 1;
