/* Auto-generated from grid.vert.msl -- do not edit by hand. */
static const char grid_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 vp_matrix;\n"
    "    float4x4 view_matrix;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _36 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = VertUniforms.vp_matrix * _36;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD0;\n"
    "    out.out_var_TEXCOORD1 = fast::normalize(float3(0.0, 1.0, 0.0) * float3x3(float4(VertUniforms.view_matrix[0][0], VertUniforms.view_matrix[1][0], VertUniforms.view_matrix[2][0], VertUniforms.view_matrix[3][0]).xyz, float4(VertUniforms.view_matrix[0][1], VertUniforms.view_matrix[1][1], VertUniforms.view_matrix[2][1], VertUniforms.view_matrix[3][1]).xyz, float4(VertUniforms.view_matrix[0][2], VertUniforms.view_matrix[1][2], VertUniforms.view_matrix[2][2], VertUniforms.view_matrix[3][2]).xyz));\n"
    "    out.out_var_TEXCOORD2 = VertUniforms.light_vp * _36;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_vert_msl_size = sizeof(grid_vert_msl) - 1;
