/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _65 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "    float4 out_var_SV_Target2 [[color(2)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_tex [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _86;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _86 = FragUniforms.base_color * diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _86 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _87 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _100 = fast::normalize(-FragUniforms.light_dir.xyz);\n"
    "    float _166;\n"
    "    do\n"
    "    {\n"
    "        float3 _119 = in.in_var_TEXCOORD4.xyz / float3(in.in_var_TEXCOORD4.w);\n"
    "        float2 _122 = (_119.xy * 0.5) + float2(0.5);\n"
    "        float _124 = 1.0 - _122.y;\n"
    "        float2 _125 = _122;\n"
    "        _125.y = _124;\n"
    "        float _126 = _122.x;\n"
    "        bool _131;\n"
    "        if ((isunordered(_126, 0.0) || _126 >= 0.0))\n"
    "        {\n"
    "            _131 = _126 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _131 = true;\n"
    "        }\n"
    "        bool _136;\n"
    "        if (!_131)\n"
    "        {\n"
    "            _136 = _124 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _136 = true;\n"
    "        }\n"
    "        bool _141;\n"
    "        if (!_136)\n"
    "        {\n"
    "            _141 = _124 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _141 = true;\n"
    "        }\n"
    "        if (_141)\n"
    "        {\n"
    "            _166 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _144 = _119.z;\n"
    "        float _146;\n"
    "        _146 = 0.0;\n"
    "        for (int _149 = 0; _149 < 4; )\n"
    "        {\n"
    "            _146 += float((_144 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_125 + (_65[_149] * float2(0.00048828125)))).x);\n"
    "            _149++;\n"
    "            continue;\n"
    "        }\n"
    "        _166 = _146 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((_86.xyz * FragUniforms.ambient) + (((((_86.xyz * precise::max(dot(_87, _100), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_87, fast::normalize(_100 + fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess))) * FragUniforms.light_intensity) * float3(FragUniforms.light_color)) * _166), _86.w);\n"
    "    out.out_var_SV_Target1 = float4(fast::normalize(in.in_var_TEXCOORD3), 1.0);\n"
    "    out.out_var_SV_Target2 = float4(in.in_var_TEXCOORD0, 0.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
