/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float alpha_cutoff;\n"
    "    float has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "    float _pad2;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler diffuse_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _56;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _56 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _56 = float4(1.0);\n"
    "    }\n"
    "    float4 _59 = _56 * FragUniforms.base_color;\n"
    "    float3 _60 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _64 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _70 = _59.xyz;\n"
    "    out.out_var_SV_Target = float4(((_70 * FragUniforms.ambient) + (_70 * precise::max(dot(_60, _64), 0.0))) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_60, fast::normalize(_64 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), FragUniforms.shininess))), _59.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
