/* Auto-generated from noise.vert.msl -- do not edit by hand. */
static const char noise_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(uint gl_VertexIndex [[vertex_id]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    bool _30;\n"
    "    if (gl_VertexIndex != 1u)\n"
    "    {\n"
    "        _30 = gl_VertexIndex == 4u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _30 = true;\n"
    "    }\n"
    "    bool _35;\n"
    "    if (!_30)\n"
    "    {\n"
    "        _35 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _35 = true;\n"
    "    }\n"
    "    float _36 = float(_35);\n"
    "    bool _41;\n"
    "    if (gl_VertexIndex != 2u)\n"
    "    {\n"
    "        _41 = gl_VertexIndex == 3u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _41 = true;\n"
    "    }\n"
    "    bool _46;\n"
    "    if (!_41)\n"
    "    {\n"
    "        _46 = gl_VertexIndex == 5u;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _46 = true;\n"
    "    }\n"
    "    float _47 = float(_46);\n"
    "    out.gl_Position = float4((_36 * 2.0) - 1.0, (_47 * 2.0) - 1.0, 0.0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = float2(_36, 1.0 - _47);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int noise_vert_msl_size = sizeof(noise_vert_msl) - 1;
