/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _40 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _41 = fwidth(_40);\n"
    "    float2 _46 = abs(fract(_40 - float2(0.5)) - float2(0.5)) / _41;\n"
    "    float4 _74 = mix(GridFragUniforms.bg_color, GridFragUniforms.line_color, float4(((1.0 - fast::clamp(precise::min(_46.x, _46.y), 0.0, 1.0)) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_41.x, _41.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0.xz - GridFragUniforms.eye_pos.xz)))));\n"
    "    float3 _78 = fast::normalize(GridFragUniforms.light_dir.xyz);\n"
    "    float3 _82 = _74.xyz;\n"
    "    float3 _101 = ((_82 * GridFragUniforms.ambient) + (_82 * precise::max(_78.y, 0.0))) + (float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_78 + fast::normalize(GridFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0)).y, 0.0), GridFragUniforms.shininess)));\n"
    "    out.out_var_SV_Target = float4(_101, _74.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
