/* Auto-generated from material.frag.msl -- do not edit by hand. */
static const char material_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 mat_ambient;\n"
    "    float4 mat_diffuse;\n"
    "    float4 mat_specular;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    uint has_texture;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float3 _59;\n"
    "    if (FragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _59 = FragUniforms.mat_diffuse.xyz * diffuse_tex.sample(smp, in.in_var_TEXCOORD0).xyz;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _59 = FragUniforms.mat_diffuse.xyz;\n"
    "    }\n"
    "    float3 _60 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _64 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    out.out_var_SV_Target = float4((FragUniforms.mat_ambient.xyz + (_59 * precise::max(dot(_60, _64), 0.0))) + (FragUniforms.mat_specular.xyz * powr(precise::max(dot(_60, fast::normalize(_64 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), FragUniforms.mat_specular.w)), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int material_frag_msl_size = sizeof(material_frag_msl) - 1;
