/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct PointLight\n"
    "{\n"
    "    packed_float3 position;\n"
    "    float intensity;\n"
    "    packed_float3 color;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float shadow_far_plane;\n"
    "    float _pad1;\n"
    "    float _pad2;\n"
    "    PointLight lights[4];\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texturecube<float> shadow_cube0 [[texture(0)]], texturecube<float> shadow_cube1 [[texture(1)]], texturecube<float> shadow_cube2 [[texture(2)]], texturecube<float> shadow_cube3 [[texture(3)]], sampler shadow_smp0 [[sampler(0)]], sampler shadow_smp1 [[sampler(1)]], sampler shadow_smp2 [[sampler(2)]], sampler shadow_smp3 [[sampler(3)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _64 = in.in_var_TEXCOORD0.xz / float2(FragUniforms.grid_spacing);\n"
    "    float2 _69 = fwidth(_64);\n"
    "    float2 _72 = float2(FragUniforms.line_width);\n"
    "    float2 _75 = float2(1.0) - smoothstep(_72, _72 + _69, abs(fract(_64 - float2(0.5)) - float2(0.5)));\n"
    "    float3 _102 = mix(FragUniforms.bg_color.xyz, FragUniforms.line_color.xyz, float3((precise::max(_75.x, _75.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_69.x, _69.y)))) * (1.0 - smoothstep(FragUniforms.fade_distance * 0.5, FragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(FragUniforms.eye_pos))))));\n"
    "    float3 _104 = fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0);\n"
    "    float3 _109;\n"
    "    _109 = _102 * FragUniforms.ambient;\n"
    "    float3 _110;\n"
    "    for (int _112 = 0; _112 < 4; _109 = _110, _112++)\n"
    "    {\n"
    "        if (FragUniforms.lights[_112].intensity <= 0.0)\n"
    "        {\n"
    "            _110 = _109;\n"
    "            continue;\n"
    "        }\n"
    "        float3 _124 = float3(FragUniforms.lights[_112].position) - in.in_var_TEXCOORD0;\n"
    "        float _125 = length(_124);\n"
    "        float3 _127 = _124 / float3(_125);\n"
    "        float3 _148 = in.in_var_TEXCOORD0 - float3(FragUniforms.lights[_112].position);\n"
    "        float _187;\n"
    "        if (_112 == 0)\n"
    "        {\n"
    "            _187 = shadow_cube0.sample(shadow_smp0, _148).x;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _186;\n"
    "            if (_112 == 1)\n"
    "            {\n"
    "                _186 = shadow_cube1.sample(shadow_smp1, _148).x;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                float _185;\n"
    "                if (_112 == 2)\n"
    "                {\n"
    "                    _185 = shadow_cube2.sample(shadow_smp2, _148).x;\n"
    "                }\n"
    "                else\n"
    "                {\n"
    "                    _185 = shadow_cube3.sample(shadow_smp3, _148).x;\n"
    "                }\n"
    "                _186 = _185;\n"
    "            }\n"
    "            _187 = _186;\n"
    "        }\n"
    "        _110 = _109 + ((((((_102 * precise::max(_127.y, 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(fast::normalize(_127 + _104).y, 0.0), FragUniforms.shininess))) * ((((length(_148) / FragUniforms.shadow_far_plane) - 0.00200000009499490261077880859375) > _187) ? 0.0 : 1.0)) * (1.0 / ((1.0 + (0.3499999940395355224609375 * _125)) + ((0.439999997615814208984375 * _125) * _125)))) * FragUniforms.lights[_112].intensity) * float3(FragUniforms.lights[_112].color));\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(_109, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
