/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct PointLight\n"
    "{\n"
    "    packed_float3 position;\n"
    "    float intensity;\n"
    "    packed_float3 color;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float shadow_far_plane;\n"
    "    PointLight lights[4];\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texturecube<float> shadow_cube0 [[texture(1)]], texturecube<float> shadow_cube1 [[texture(2)]], texturecube<float> shadow_cube2 [[texture(3)]], texturecube<float> shadow_cube3 [[texture(4)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp0 [[sampler(1)]], sampler shadow_smp1 [[sampler(2)]], sampler shadow_smp2 [[sampler(3)]], sampler shadow_smp3 [[sampler(4)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _76;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _76 = FragUniforms.base_color * diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _76 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _77 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _81 = fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0);\n"
    "    float3 _87;\n"
    "    _87 = _76.xyz * FragUniforms.ambient;\n"
    "    float3 _88;\n"
    "    for (int _90 = 0; _90 < 4; _87 = _88, _90++)\n"
    "    {\n"
    "        if (FragUniforms.lights[_90].intensity <= 0.0)\n"
    "        {\n"
    "            _88 = _87;\n"
    "            continue;\n"
    "        }\n"
    "        float3 _102 = float3(FragUniforms.lights[_90].position) - in.in_var_TEXCOORD0;\n"
    "        float _103 = length(_102);\n"
    "        float3 _105 = _102 / float3(_103);\n"
    "        float3 _126 = in.in_var_TEXCOORD0 - float3(FragUniforms.lights[_90].position);\n"
    "        float _165;\n"
    "        if (_90 == 0)\n"
    "        {\n"
    "            _165 = shadow_cube0.sample(shadow_smp0, _126).x;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _164;\n"
    "            if (_90 == 1)\n"
    "            {\n"
    "                _164 = shadow_cube1.sample(shadow_smp1, _126).x;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                float _163;\n"
    "                if (_90 == 2)\n"
    "                {\n"
    "                    _163 = shadow_cube2.sample(shadow_smp2, _126).x;\n"
    "                }\n"
    "                else\n"
    "                {\n"
    "                    _163 = shadow_cube3.sample(shadow_smp3, _126).x;\n"
    "                }\n"
    "                _164 = _163;\n"
    "            }\n"
    "            _165 = _164;\n"
    "        }\n"
    "        _88 = _87 + ((((((_76.xyz * precise::max(dot(_77, _105), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_77, fast::normalize(_105 + _81)), 0.0), FragUniforms.shininess))) * ((((length(_126) / FragUniforms.shadow_far_plane) - 0.00200000009499490261077880859375) > _165) ? 0.0 : 1.0)) * (1.0 / ((1.0 + (0.3499999940395355224609375 * _103)) + ((0.439999997615814208984375 * _103) * _103)))) * FragUniforms.lights[_90].intensity) * float3(FragUniforms.lights[_90].color));\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(_87, _76.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
