/* Auto-generated from shadow.frag.msl -- do not edit by hand. */
static const char shadow_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    packed_float3 light_pos;\n"
    "    float far_plane;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.out_var_SV_Target = float4(length(in.in_var_TEXCOORD0 - float3(FragUniforms.light_pos)) / FragUniforms.far_plane, 0.0, 0.0, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_frag_msl_size = sizeof(shadow_frag_msl) - 1;
