/* Auto-generated from shadow.vert.msl -- do not edit by hand. */
static const char shadow_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 light_mvp;\n"
    "    float4x4 model;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _29 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = VertUniforms.light_mvp * _29;\n"
    "    out.out_var_TEXCOORD0 = (VertUniforms.model * _29).xyz;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int shadow_vert_msl_size = sizeof(shadow_vert_msl) - 1;
