/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 light_pos;\n"
    "    float light_intensity;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    packed_float3 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _46 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _51 = fwidth(_46);\n"
    "    float2 _54 = float2(GridFragUniforms.line_width);\n"
    "    float2 _57 = float2(1.0) - smoothstep(_54, _54 + _51, abs(fract(_46 - float2(0.5)) - float2(0.5)));\n"
    "    float3 _84 = mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_57.x, _57.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_51.x, _51.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(GridFragUniforms.eye_pos))))));\n"
    "    float3 _87 = float3(GridFragUniforms.light_pos) - in.in_var_TEXCOORD0;\n"
    "    float _88 = length(_87);\n"
    "    float3 _90 = _87 / float3(_88);\n"
    "    out.out_var_SV_Target = float4((_84 * GridFragUniforms.ambient) + ((((_84 * precise::max(_90.y, 0.0)) + (float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_90 + fast::normalize(float3(GridFragUniforms.eye_pos) - in.in_var_TEXCOORD0)).y, 0.0), GridFragUniforms.shininess)))) * (1.0 / ((1.0 + (0.0900000035762786865234375 * _88)) + ((0.0320000015199184417724609375 * _88) * _88)))) * GridFragUniforms.light_intensity), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
