/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 light_pos;\n"
    "    float light_intensity;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], sampler diffuse_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _64;\n"
    "    if (SceneFragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _64 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0) * SceneFragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _64 = SceneFragUniforms.base_color;\n"
    "    }\n"
    "    float3 _65 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _68 = float3(SceneFragUniforms.light_pos) - in.in_var_TEXCOORD2;\n"
    "    float _69 = length(_68);\n"
    "    float3 _71 = _68 / float3(_69);\n"
    "    out.out_var_SV_Target = float4((_64.xyz * SceneFragUniforms.ambient) + ((((_64.xyz * precise::max(dot(_65, _71), 0.0)) + (float3(1.0) * (SceneFragUniforms.specular_str * powr(precise::max(dot(_65, fast::normalize(_71 + fast::normalize(float3(SceneFragUniforms.eye_pos) - in.in_var_TEXCOORD2))), 0.0), SceneFragUniforms.shininess)))) * (1.0 / ((1.0 + (0.0900000035762786865234375 * _69)) + ((0.0320000015199184417724609375 * _69) * _69)))) * SceneFragUniforms.light_intensity), _64.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
