/* Auto-generated from scene.vert.msl -- do not edit by hand. */
static const char scene_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SceneVertUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_SceneVertUniforms& SceneVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _40 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = SceneVertUniforms.mvp * _40;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD1 = in.in_var_TEXCOORD1 * float3x3(cross(float4(SceneVertUniforms.model[0][1], SceneVertUniforms.model[1][1], SceneVertUniforms.model[2][1], SceneVertUniforms.model[3][1]).xyz, float4(SceneVertUniforms.model[0][2], SceneVertUniforms.model[1][2], SceneVertUniforms.model[2][2], SceneVertUniforms.model[3][2]).xyz), cross(float4(SceneVertUniforms.model[0][2], SceneVertUniforms.model[1][2], SceneVertUniforms.model[2][2], SceneVertUniforms.model[3][2]).xyz, float4(SceneVertUniforms.model[0][0], SceneVertUniforms.model[1][0], SceneVertUniforms.model[2][0], SceneVertUniforms.model[3][0]).xyz), cross(float4(SceneVertUniforms.model[0][0], SceneVertUniforms.model[1][0], SceneVertUniforms.model[2][0], SceneVertUniforms.model[3][0]).xyz, float4(SceneVertUniforms.model[0][1], SceneVertUniforms.model[1][1], SceneVertUniforms.model[2][1], SceneVertUniforms.model[3][1]).xyz));\n"
    "    out.out_var_TEXCOORD2 = (SceneVertUniforms.model * _40).xyz;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_vert_msl_size = sizeof(scene_vert_msl) - 1;
