/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 light_dir;\n"
    "    float light_intensity;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _59 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _69 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _74 = fwidth(_69);\n"
    "    float2 _77 = float2(GridFragUniforms.line_width);\n"
    "    float2 _80 = float2(1.0) - smoothstep(_77, _77 + _74, abs(fract(_69 - float2(0.5)) - float2(0.5)));\n"
    "    float _166;\n"
    "    do\n"
    "    {\n"
    "        float3 _119 = in.in_var_TEXCOORD1.xyz / float3(in.in_var_TEXCOORD1.w);\n"
    "        float2 _122 = (_119.xy * 0.5) + float2(0.5);\n"
    "        float _124 = 1.0 - _122.y;\n"
    "        float2 _125 = _122;\n"
    "        _125.y = _124;\n"
    "        float _126 = _122.x;\n"
    "        bool _131;\n"
    "        if ((isunordered(_126, 0.0) || _126 >= 0.0))\n"
    "        {\n"
    "            _131 = _126 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _131 = true;\n"
    "        }\n"
    "        bool _136;\n"
    "        if (!_131)\n"
    "        {\n"
    "            _136 = _124 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _136 = true;\n"
    "        }\n"
    "        bool _141;\n"
    "        if (!_136)\n"
    "        {\n"
    "            _141 = _124 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _141 = true;\n"
    "        }\n"
    "        if (_141)\n"
    "        {\n"
    "            _166 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _144 = _119.z;\n"
    "        float _146;\n"
    "        _146 = 0.0;\n"
    "        for (int _149 = 0; _149 < 4; )\n"
    "        {\n"
    "            _146 += float((_144 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_125 + (_59[_149] * float2(0.00048828125)))).x);\n"
    "            _149++;\n"
    "            continue;\n"
    "        }\n"
    "        _166 = _146 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4(mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_80.x, _80.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_74.x, _74.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(GridFragUniforms.eye_pos)))))) * (GridFragUniforms.ambient + ((precise::max(fast::normalize(-float3(GridFragUniforms.light_dir)).y, 0.0) * GridFragUniforms.light_intensity) * _166)), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
