/* Auto-generated from water.frag.msl -- do not edit by hand. */
static const char water_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    packed_float3 eye_pos;\n"
    "    float water_level;\n"
    "    float4 water_tint;\n"
    "    float fresnel_f0;\n"
    "    float4 _pad[3];\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> reflection_tex [[texture(0)]], sampler reflection_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _49 = ((in.in_var_TEXCOORD1.xy / float2(in.in_var_TEXCOORD1.w)) * 0.5) + float2(0.5);\n"
    "    _49.y = 1.0 - _49.y;\n"
    "    float _70 = FragUniforms.fresnel_f0 + ((1.0 - FragUniforms.fresnel_f0) * powr(1.0 - precise::max(fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0).y, 0.0), 5.0));\n"
    "    out.out_var_SV_Target = float4(mix(FragUniforms.water_tint.xyz, reflection_tex.sample(reflection_smp, _49).xyz, float3(_70)), mix(0.60000002384185791015625, 1.0, _70));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int water_frag_msl_size = sizeof(water_frag_msl) - 1;
