/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float has_texture;\n"
    "    float has_normal_map;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float normal_mode;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float3 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> normal_tex [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler normal_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _67;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _67 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _67 = float4(1.0);\n"
    "    }\n"
    "    float4 _70 = _67 * FragUniforms.base_color;\n"
    "    float3 _107;\n"
    "    if (FragUniforms.normal_mode > 1.5)\n"
    "    {\n"
    "        float3 _79 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "        float4 _84 = normal_tex.sample(normal_smp, in.in_var_TEXCOORD0);\n"
    "        float3 _96;\n"
    "        if (FragUniforms.has_normal_map > 0.5)\n"
    "        {\n"
    "            _96 = fast::normalize(float3x3(fast::normalize(in.in_var_TEXCOORD3), fast::normalize(in.in_var_TEXCOORD4), _79) * ((_84.xyz * 2.0) - float3(1.0)));\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _96 = _79;\n"
    "        }\n"
    "        _107 = _96;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float3 _106;\n"
    "        if (FragUniforms.normal_mode > 0.5)\n"
    "        {\n"
    "            _106 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _106 = fast::normalize(cross(dfdx(in.in_var_TEXCOORD2), dfdy(in.in_var_TEXCOORD2)));\n"
    "        }\n"
    "        _107 = _106;\n"
    "    }\n"
    "    float3 _111 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _117 = _70.xyz;\n"
    "    out.out_var_SV_Target = float4(((_117 * FragUniforms.ambient) + (_117 * precise::max(dot(_107, _111), 0.0))) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_107, fast::normalize(_111 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), FragUniforms.shininess))), _70.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
