/* Auto-generated from scene.vert.msl -- do not edit by hand. */
static const char scene_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float2 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float3 out_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "    float4 in_var_TEXCOORD3 [[attribute(3)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _45 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    float3 _63 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(cross(float4(VertUniforms.model[0][1], VertUniforms.model[1][1], VertUniforms.model[2][1], VertUniforms.model[3][1]).xyz, float4(VertUniforms.model[0][2], VertUniforms.model[1][2], VertUniforms.model[2][2], VertUniforms.model[3][2]).xyz), cross(float4(VertUniforms.model[0][2], VertUniforms.model[1][2], VertUniforms.model[2][2], VertUniforms.model[3][2]).xyz, float4(VertUniforms.model[0][0], VertUniforms.model[1][0], VertUniforms.model[2][0], VertUniforms.model[3][0]).xyz), cross(float4(VertUniforms.model[0][0], VertUniforms.model[1][0], VertUniforms.model[2][0], VertUniforms.model[3][0]).xyz, float4(VertUniforms.model[0][1], VertUniforms.model[1][1], VertUniforms.model[2][1], VertUniforms.model[3][1]).xyz)));\n"
    "    float3 _66 = fast::normalize(in.in_var_TEXCOORD3.xyz * float3x3(float4(VertUniforms.model[0][0], VertUniforms.model[1][0], VertUniforms.model[2][0], VertUniforms.model[3][0]).xyz, float4(VertUniforms.model[0][1], VertUniforms.model[1][1], VertUniforms.model[2][1], VertUniforms.model[3][1]).xyz, float4(VertUniforms.model[0][2], VertUniforms.model[1][2], VertUniforms.model[2][2], VertUniforms.model[3][2]).xyz));\n"
    "    float3 _70 = fast::normalize(_66 - (_63 * dot(_63, _66)));\n"
    "    out.gl_Position = VertUniforms.mvp * _45;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD1 = _63;\n"
    "    out.out_var_TEXCOORD2 = (VertUniforms.model * _45).xyz;\n"
    "    out.out_var_TEXCOORD3 = _70;\n"
    "    out.out_var_TEXCOORD4 = cross(_63, _70) * in.in_var_TEXCOORD3.w;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_vert_msl_size = sizeof(scene_vert_msl) - 1;
