/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float _pad1;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _42 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _47 = fwidth(_42);\n"
    "    float2 _50 = float2(GridFragUniforms.line_width);\n"
    "    float2 _53 = float2(1.0) - smoothstep(_50, _50 + _47, abs(fract(_42 - float2(0.5)) - float2(0.5)));\n"
    "    float3 _81 = mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_53.x, _53.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_47.x, _47.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - GridFragUniforms.eye_pos.xyz)))));\n"
    "    float3 _85 = fast::normalize(GridFragUniforms.light_dir.xyz);\n"
    "    float3 _106 = ((_81 * GridFragUniforms.ambient) + (_81 * precise::max(_85.y, 0.0))) + (float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_85 + fast::normalize(GridFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0)).y, 0.0), GridFragUniforms.shininess)));\n"
    "    out.out_var_SV_Target = float4(_106, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
