/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4 cascade_splits;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float light_intensity;\n"
    "    float shadow_texel_size;\n"
    "    float shadow_bias;\n"
    "    packed_float3 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], texture2d<float> shadow_map0 [[texture(0)]], texture2d<float> shadow_map1 [[texture(1)]], texture2d<float> shadow_map2 [[texture(2)]], sampler shadow_smp0 [[sampler(0)]], sampler shadow_smp1 [[sampler(1)]], sampler shadow_smp2 [[sampler(2)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _75 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _80 = fwidth(_75);\n"
    "    float2 _83 = float2(GridFragUniforms.line_width);\n"
    "    float2 _86 = float2(1.0) - smoothstep(_83, _83 + _80, abs(fract(_75 - float2(0.5)) - float2(0.5)));\n"
    "    float _100 = length(in.in_var_TEXCOORD0 - GridFragUniforms.eye_pos.xyz);\n"
    "    float3 _114 = mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_86.x, _86.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_80.x, _80.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, _100))));\n"
    "    float _401;\n"
    "    if (_100 < GridFragUniforms.cascade_splits.x)\n"
    "    {\n"
    "        float3 _125 = in.in_var_TEXCOORD1.xyz / float3(in.in_var_TEXCOORD1.w);\n"
    "        float2 _128 = (_125.xy * 0.5) + float2(0.5);\n"
    "        _128.y = 1.0 - _128.y;\n"
    "        float _144 = _125.z - GridFragUniforms.shadow_bias;\n"
    "        _401 = ((((((((float(shadow_map0.sample(shadow_smp0, (_128 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _144) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, _128).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) + float(shadow_map0.sample(shadow_smp0, (_128 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _144)) * 0.111111111938953399658203125;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _400;\n"
    "        if (_100 < GridFragUniforms.cascade_splits.y)\n"
    "        {\n"
    "            float3 _220 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "            float2 _223 = (_220.xy * 0.5) + float2(0.5);\n"
    "            _223.y = 1.0 - _223.y;\n"
    "            float _239 = _220.z - GridFragUniforms.shadow_bias;\n"
    "            _400 = ((((((((float(shadow_map1.sample(shadow_smp1, (_223 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _239) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, _223).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) + float(shadow_map1.sample(shadow_smp1, (_223 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _239)) * 0.111111111938953399658203125;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _399;\n"
    "            if (_100 < GridFragUniforms.cascade_splits.z)\n"
    "            {\n"
    "                float3 _314 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "                float2 _317 = (_314.xy * 0.5) + float2(0.5);\n"
    "                _317.y = 1.0 - _317.y;\n"
    "                float _333 = _314.z - GridFragUniforms.shadow_bias;\n"
    "                _399 = ((((((((float(shadow_map2.sample(shadow_smp2, (_317 + (float2(-1.0) * GridFragUniforms.shadow_texel_size))).x >= _333) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, _317).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) + float(shadow_map2.sample(shadow_smp2, (_317 + (float2(1.0) * GridFragUniforms.shadow_texel_size))).x >= _333)) * 0.111111111938953399658203125;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _399 = 1.0;\n"
    "            }\n"
    "            _400 = _399;\n"
    "        }\n"
    "        _401 = _400;\n"
    "    }\n"
    "    float3 _405 = fast::normalize(GridFragUniforms.light_dir.xyz);\n"
    "    out.out_var_SV_Target = float4((_114 * GridFragUniforms.ambient) + (((_114 * (_401 * precise::max(_405.y, 0.0))) + ((float3(1.0) * (GridFragUniforms.specular_str * powr(precise::max(fast::normalize(_405 + fast::normalize(GridFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0)).y, 0.0), GridFragUniforms.shininess))) * _401)) * GridFragUniforms.light_intensity), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
