/* Auto-generated from grid.vert.msl -- do not edit by hand. */
static const char grid_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridVertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "};\n"
    "\n"
    "struct type_ShadowMatrices\n"
    "{\n"
    "    float4x4 light_vp[3];\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_GridVertUniforms& GridVertUniforms [[buffer(0)]], constant type_ShadowMatrices& ShadowMatrices [[buffer(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _37 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = GridVertUniforms.vp * _37;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD0;\n"
    "    out.out_var_TEXCOORD1 = ShadowMatrices.light_vp[0] * _37;\n"
    "    out.out_var_TEXCOORD2 = ShadowMatrices.light_vp[1] * _37;\n"
    "    out.out_var_TEXCOORD3 = ShadowMatrices.light_vp[2] * _37;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_vert_msl_size = sizeof(grid_vert_msl) - 1;
