/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4 cascade_splits;\n"
    "    uint has_texture;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "    float light_intensity;\n"
    "    float shadow_texel_size;\n"
    "    float shadow_bias;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 in_var_TEXCOORD5 [[user(locn5)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_map0 [[texture(1)]], texture2d<float> shadow_map1 [[texture(2)]], texture2d<float> shadow_map2 [[texture(3)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp0 [[sampler(1)]], sampler shadow_smp1 [[sampler(2)]], sampler shadow_smp2 [[sampler(3)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _92;\n"
    "    if (SceneFragUniforms.has_texture != 0u)\n"
    "    {\n"
    "        _92 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD0) * SceneFragUniforms.base_color;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _92 = SceneFragUniforms.base_color;\n"
    "    }\n"
    "    float _97 = length(in.in_var_TEXCOORD2 - SceneFragUniforms.eye_pos.xyz);\n"
    "    float _384;\n"
    "    if (_97 < SceneFragUniforms.cascade_splits.x)\n"
    "    {\n"
    "        float3 _108 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _111 = (_108.xy * 0.5) + float2(0.5);\n"
    "        _111.y = 1.0 - _111.y;\n"
    "        float _127 = _108.z - SceneFragUniforms.shadow_bias;\n"
    "        _384 = ((((((((float(shadow_map0.sample(shadow_smp0, (_111 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, _111).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) + float(shadow_map0.sample(shadow_smp0, (_111 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _127)) * 0.111111111938953399658203125;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float _383;\n"
    "        if (_97 < SceneFragUniforms.cascade_splits.y)\n"
    "        {\n"
    "            float3 _203 = in.in_var_TEXCOORD4.xyz / float3(in.in_var_TEXCOORD4.w);\n"
    "            float2 _206 = (_203.xy * 0.5) + float2(0.5);\n"
    "            _206.y = 1.0 - _206.y;\n"
    "            float _222 = _203.z - SceneFragUniforms.shadow_bias;\n"
    "            _383 = ((((((((float(shadow_map1.sample(shadow_smp1, (_206 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, _206).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) + float(shadow_map1.sample(shadow_smp1, (_206 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _222)) * 0.111111111938953399658203125;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float _382;\n"
    "            if (_97 < SceneFragUniforms.cascade_splits.z)\n"
    "            {\n"
    "                float3 _297 = in.in_var_TEXCOORD5.xyz / float3(in.in_var_TEXCOORD5.w);\n"
    "                float2 _300 = (_297.xy * 0.5) + float2(0.5);\n"
    "                _300.y = 1.0 - _300.y;\n"
    "                float _316 = _297.z - SceneFragUniforms.shadow_bias;\n"
    "                _382 = ((((((((float(shadow_map2.sample(shadow_smp2, (_300 + (float2(-1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(0.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(1.0, -1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(-1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, _300).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(1.0, 0.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(-1.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(0.0, 1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) + float(shadow_map2.sample(shadow_smp2, (_300 + (float2(1.0) * SceneFragUniforms.shadow_texel_size))).x >= _316)) * 0.111111111938953399658203125;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _382 = 1.0;\n"
    "            }\n"
    "            _383 = _382;\n"
    "        }\n"
    "        _384 = _383;\n"
    "    }\n"
    "    float3 _385 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _389 = fast::normalize(SceneFragUniforms.light_dir.xyz);\n"
    "    out.out_var_SV_Target = float4((_92.xyz * SceneFragUniforms.ambient) + (((_92.xyz * (_384 * precise::max(dot(_385, _389), 0.0))) + (float3(1.0) * ((_384 * SceneFragUniforms.specular_str) * powr(precise::max(dot(_385, fast::normalize(_389 + fast::normalize(SceneFragUniforms.eye_pos.xyz - in.in_var_TEXCOORD2))), 0.0), SceneFragUniforms.shininess)))) * SceneFragUniforms.light_intensity), _92.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
