"""Diagram functions for ui lessons."""

__all__ = [
    "diagram_ttf_file_structure",
    "diagram_glyph_anatomy",
    "diagram_endianness",
    "diagram_contour_reconstruction",
    "diagram_scanline_crossings",
    "diagram_winding_direction",
    "diagram_antialiasing_comparison",
    "diagram_shelf_packing",
    "diagram_padding_bleed",
    "diagram_uv_coordinates",
    "diagram_pen_advance",
    "diagram_baseline_metrics",
    "diagram_quad_vertex_layout",
    "diagram_line_breaking",
    "diagram_hot_active_state_machine",
    "diagram_declare_then_draw",
    "diagram_button_draw_data",
    "diagram_hit_testing",
    "diagram_checkbox_anatomy",
    "diagram_checkbox_vs_button",
    "diagram_slider_anatomy",
    "diagram_slider_value_mapping",
    "diagram_drag_outside_bounds",
    "diagram_slider_state_colors",
    "diagram_widget_interaction_comparison",
    "diagram_focus_state_machine",
    "diagram_text_input_anatomy",
    "diagram_cursor_positioning",
    "diagram_character_insertion",
    "diagram_character_deletion",
    "diagram_keyboard_input_flow",
    "diagram_layout_cursor_model",
    "diagram_horizontal_vs_vertical",
    "diagram_nested_layout",
    "diagram_layout_stack_visualization",
    "diagram_padding_and_spacing",
    "diagram_layout_next_sequence",
    "diagram_panel_anatomy",
    "diagram_clip_rect_operation",
    "diagram_scroll_offset_model",
    "diagram_scrollbar_proportions",
    "diagram_uv_remap_on_clip",
    "diagram_panel_with_scroll_sequence",
    "diagram_mouse_wheel_and_drag",
    "diagram_window_anatomy",
    "diagram_z_order_model",
    "diagram_drag_mechanics",
    "diagram_deferred_draw_pipeline",
    "diagram_input_routing_overlap",
    "diagram_collapse_toggle",
    "diagram_window_state_persistence",
    "diagram_window_vs_panel_comparison",
    "diagram_id_collision",
    "diagram_id_scope_stack",
    "diagram_scale_factor_effect",
    "diagram_spacing_anatomy",
    "diagram_spacing_struct_overview",
    "diagram_atlas_rebuild_at_scale",
    "diagram_before_after_spacing",
    "diagram_scaled_dimensions_formula",
    "diagram_theme_color_slots",
    "diagram_wcag_contrast_formula",
    "diagram_contrast_ratio_scale",
    "diagram_srgb_linearization_curve",
    "diagram_theme_slot_mapping",
    "diagram_adjacent_pair_matrix",
    "diagram_before_after_theming",
]

from .lesson_01 import (
    diagram_endianness,
    diagram_glyph_anatomy,
    diagram_ttf_file_structure,
)
from .lesson_02 import (
    diagram_antialiasing_comparison,
    diagram_contour_reconstruction,
    diagram_scanline_crossings,
    diagram_winding_direction,
)
from .lesson_03 import (
    diagram_padding_bleed,
    diagram_shelf_packing,
    diagram_uv_coordinates,
)
from .lesson_04 import (
    diagram_baseline_metrics,
    diagram_line_breaking,
    diagram_pen_advance,
    diagram_quad_vertex_layout,
)
from .lesson_05 import (
    diagram_button_draw_data,
    diagram_declare_then_draw,
    diagram_hit_testing,
    diagram_hot_active_state_machine,
)
from .lesson_06 import (
    diagram_checkbox_anatomy,
    diagram_checkbox_vs_button,
    diagram_drag_outside_bounds,
    diagram_slider_anatomy,
    diagram_slider_state_colors,
    diagram_slider_value_mapping,
    diagram_widget_interaction_comparison,
)
from .lesson_07 import (
    diagram_character_deletion,
    diagram_character_insertion,
    diagram_cursor_positioning,
    diagram_focus_state_machine,
    diagram_keyboard_input_flow,
    diagram_text_input_anatomy,
)
from .lesson_08 import (
    diagram_horizontal_vs_vertical,
    diagram_layout_cursor_model,
    diagram_layout_next_sequence,
    diagram_layout_stack_visualization,
    diagram_nested_layout,
    diagram_padding_and_spacing,
)
from .lesson_09 import (
    diagram_clip_rect_operation,
    diagram_mouse_wheel_and_drag,
    diagram_panel_anatomy,
    diagram_panel_with_scroll_sequence,
    diagram_scroll_offset_model,
    diagram_scrollbar_proportions,
    diagram_uv_remap_on_clip,
)
from .lesson_10 import (
    diagram_collapse_toggle,
    diagram_deferred_draw_pipeline,
    diagram_drag_mechanics,
    diagram_input_routing_overlap,
    diagram_window_anatomy,
    diagram_window_state_persistence,
    diagram_window_vs_panel_comparison,
    diagram_z_order_model,
)
from .lesson_11 import diagram_id_collision, diagram_id_scope_stack
from .lesson_12 import (
    diagram_atlas_rebuild_at_scale,
    diagram_before_after_spacing,
    diagram_scale_factor_effect,
    diagram_scaled_dimensions_formula,
    diagram_spacing_anatomy,
    diagram_spacing_struct_overview,
)
from .lesson_13 import (
    diagram_adjacent_pair_matrix,
    diagram_before_after_theming,
    diagram_contrast_ratio_scale,
    diagram_srgb_linearization_curve,
    diagram_theme_color_slots,
    diagram_theme_slot_mapping,
    diagram_wcag_contrast_formula,
)
