/* Auto-generated from blur.frag.msl -- do not edit by hand. */
static const char blur_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_BlurParams\n"
    "{\n"
    "    float2 texel_size;\n"
    "    float2 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_BlurParams& BlurParams [[buffer(0)]], texture2d<float> ssao_tex [[texture(0)]], sampler ssao_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float _35;\n"
    "    int _38;\n"
    "    _35 = 0.0;\n"
    "    _38 = -2;\n"
    "    float _36;\n"
    "    for (; _38 < 2; _35 = _36, _38++)\n"
    "    {\n"
    "        _36 = _35;\n"
    "        for (int _46 = -2; _46 < 2; )\n"
    "        {\n"
    "            _36 += ssao_tex.sample(ssao_smp, (in.in_var_TEXCOORD0 + (float2(float(_38) + 0.5, float(_46) + 0.5) * BlurParams.texel_size))).x;\n"
    "            _46++;\n"
    "            continue;\n"
    "        }\n"
    "    }\n"
    "    float _64 = _35 * 0.0625;\n"
    "    out.out_var_SV_Target = float4(_64, _64, _64, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int blur_frag_msl_size = sizeof(blur_frag_msl) - 1;
