/* Auto-generated from composite.frag.msl -- do not edit by hand. */
static const char composite_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_CompositeParams\n"
    "{\n"
    "    int display_mode;\n"
    "    int use_dither;\n"
    "    float2 _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_CompositeParams& CompositeParams [[buffer(0)]], texture2d<float> color_tex [[texture(0)]], texture2d<float> ao_tex [[texture(1)]], sampler color_smp [[sampler(0)]], sampler ao_smp [[sampler(1)]], float4 gl_FragCoord [[position]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _45 = color_tex.sample(color_smp, in.in_var_TEXCOORD0);\n"
    "    float3 _46 = _45.xyz;\n"
    "    float4 _50 = ao_tex.sample(ao_smp, in.in_var_TEXCOORD0);\n"
    "    float _51 = _50.x;\n"
    "    float3 _65;\n"
    "    if (CompositeParams.display_mode == 0)\n"
    "    {\n"
    "        _65 = float3(_51);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        float3 _64;\n"
    "        if (CompositeParams.display_mode == 1)\n"
    "        {\n"
    "            _64 = _46 * _51;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _64 = _46;\n"
    "        }\n"
    "        _65 = _64;\n"
    "    }\n"
    "    float3 _80;\n"
    "    if (CompositeParams.use_dither != 0)\n"
    "    {\n"
    "        _80 = _65 + float3((fract(52.98291778564453125 * fract(dot(gl_FragCoord.xy, float2(0.067110560834407806396484375, 0.005837149918079376220703125)))) - 0.5) * 0.0039215688593685626983642578125);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _80 = _65;\n"
    "    }\n"
    "    out.out_var_SV_Target = float4(_80, 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int composite_frag_msl_size = sizeof(composite_frag_msl) - 1;
