/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float light_intensity;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _62 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _73 = in.in_var_TEXCOORD0.xz / float2(FragUniforms.grid_spacing);\n"
    "    float2 _78 = fwidth(_73);\n"
    "    float2 _81 = float2(FragUniforms.line_width);\n"
    "    float2 _84 = float2(1.0) - smoothstep(_81, _81 + _78, abs(fract(_73 - float2(0.5)) - float2(0.5)));\n"
    "    float3 _111 = mix(FragUniforms.bg_color.xyz, FragUniforms.line_color.xyz, float3((precise::max(_84.x, _84.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_78.x, _78.y)))) * (1.0 - smoothstep(FragUniforms.fade_distance * 0.5, FragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(FragUniforms.eye_pos))))));\n"
    "    float _174;\n"
    "    do\n"
    "    {\n"
    "        float3 _127 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _130 = (_127.xy * 0.5) + float2(0.5);\n"
    "        float _132 = 1.0 - _130.y;\n"
    "        float2 _133 = _130;\n"
    "        _133.y = _132;\n"
    "        float _134 = _130.x;\n"
    "        bool _139;\n"
    "        if ((isunordered(_134, 0.0) || _134 >= 0.0))\n"
    "        {\n"
    "            _139 = _134 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _139 = true;\n"
    "        }\n"
    "        bool _144;\n"
    "        if (!_139)\n"
    "        {\n"
    "            _144 = _132 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _144 = true;\n"
    "        }\n"
    "        bool _149;\n"
    "        if (!_144)\n"
    "        {\n"
    "            _149 = _132 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _149 = true;\n"
    "        }\n"
    "        if (_149)\n"
    "        {\n"
    "            _174 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _152 = _127.z;\n"
    "        float _154;\n"
    "        _154 = 0.0;\n"
    "        for (int _157 = 0; _157 < 4; )\n"
    "        {\n"
    "            _154 += float((_152 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_133 + (_62[_157] * float2(0.00048828125)))).x);\n"
    "            _157++;\n"
    "            continue;\n"
    "        }\n"
    "        _174 = _154 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((_111 * FragUniforms.ambient) + ((((_111 * precise::max(fast::normalize(-FragUniforms.light_dir.xyz).y, 0.0)) * FragUniforms.light_intensity) * float3(FragUniforms.light_color)) * _174), 1.0);\n"
    "    out.out_var_SV_Target1 = float4(fast::normalize(in.in_var_TEXCOORD1), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
