/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float has_texture;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float _pad0;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _64 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> shadow_tex [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_smp [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _85;\n"
    "    if (FragUniforms.has_texture > 0.5)\n"
    "    {\n"
    "        _85 = FragUniforms.base_color * diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        _85 = FragUniforms.base_color;\n"
    "    }\n"
    "    float3 _86 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _99 = fast::normalize(-FragUniforms.light_dir.xyz);\n"
    "    float _165;\n"
    "    do\n"
    "    {\n"
    "        float3 _118 = in.in_var_TEXCOORD4.xyz / float3(in.in_var_TEXCOORD4.w);\n"
    "        float2 _121 = (_118.xy * 0.5) + float2(0.5);\n"
    "        float _123 = 1.0 - _121.y;\n"
    "        float2 _124 = _121;\n"
    "        _124.y = _123;\n"
    "        float _125 = _121.x;\n"
    "        bool _130;\n"
    "        if ((isunordered(_125, 0.0) || _125 >= 0.0))\n"
    "        {\n"
    "            _130 = _125 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _130 = true;\n"
    "        }\n"
    "        bool _135;\n"
    "        if (!_130)\n"
    "        {\n"
    "            _135 = _123 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _135 = true;\n"
    "        }\n"
    "        bool _140;\n"
    "        if (!_135)\n"
    "        {\n"
    "            _140 = _123 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _140 = true;\n"
    "        }\n"
    "        if (_140)\n"
    "        {\n"
    "            _165 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _143 = _118.z;\n"
    "        float _145;\n"
    "        _145 = 0.0;\n"
    "        for (int _148 = 0; _148 < 4; )\n"
    "        {\n"
    "            _145 += float((_143 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_124 + (_64[_148] * float2(0.00048828125)))).x);\n"
    "            _148++;\n"
    "            continue;\n"
    "        }\n"
    "        _165 = _145 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((_85.xyz * FragUniforms.ambient) + (((((_85.xyz * precise::max(dot(_86, _99), 0.0)) + float3(FragUniforms.specular_str * powr(precise::max(dot(_86, fast::normalize(_99 + fast::normalize(float3(FragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess))) * FragUniforms.light_intensity) * float3(FragUniforms.light_color)) * _165), _85.w);\n"
    "    out.out_var_SV_Target1 = float4(fast::normalize(in.in_var_TEXCOORD3), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
