/* Auto-generated from edge_detect.frag.msl -- do not edit by hand. */
static const char edge_detect_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_EdgeDetectUniforms\n"
    "{\n"
    "    float2 texel_size;\n"
    "    float depth_threshold;\n"
    "    float normal_threshold;\n"
    "    int edge_source;\n"
    "    int show_debug;\n"
    "    float2 _pad0;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float2 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_EdgeDetectUniforms& EdgeDetectUniforms [[buffer(0)]], texture2d<float> depth_tex [[texture(0)]], texture2d<float> normal_tex [[texture(1)]], texture2d<float> color_tex [[texture(2)]], sampler depth_smp [[sampler(0)]], sampler normal_smp [[sampler(1)]], sampler color_smp [[sampler(2)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _344;\n"
    "    do\n"
    "    {\n"
    "        if (EdgeDetectUniforms.show_debug != 0)\n"
    "        {\n"
    "            if (in.in_var_TEXCOORD0.x < 0.5)\n"
    "            {\n"
    "                float _77 = powr(depth_tex.sample(depth_smp, in.in_var_TEXCOORD0).x, 50.0);\n"
    "                _344 = float4(_77, _77, _77, 1.0);\n"
    "                break;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _344 = float4((normal_tex.sample(normal_smp, in.in_var_TEXCOORD0).xyz * 0.5) + float3(0.5), 1.0);\n"
    "                break;\n"
    "            }\n"
    "            break; // unreachable workaround\n"
    "        }\n"
    "        bool _138;\n"
    "        do\n"
    "        {\n"
    "            if (depth_tex.sample(depth_smp, in.in_var_TEXCOORD0).x >= 0.999000012874603271484375)\n"
    "            {\n"
    "                _138 = true;\n"
    "                break;\n"
    "            }\n"
    "            float _93 = -EdgeDetectUniforms.texel_size.x;\n"
    "            float4 _99 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(_93, EdgeDetectUniforms.texel_size.y)));\n"
    "            float _100 = _99.x;\n"
    "            float4 _106 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, EdgeDetectUniforms.texel_size.y)));\n"
    "            float _110 = -EdgeDetectUniforms.texel_size.y;\n"
    "            float4 _114 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(_93, _110)));\n"
    "            float4 _121 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, _110)));\n"
    "            bool _127;\n"
    "            if ((isunordered(_100, 0.999000012874603271484375) || _100 < 0.999000012874603271484375))\n"
    "            {\n"
    "                _127 = _106.x >= 0.999000012874603271484375;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _127 = true;\n"
    "            }\n"
    "            bool _132;\n"
    "            if (!_127)\n"
    "            {\n"
    "                _132 = _114.x >= 0.999000012874603271484375;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _132 = true;\n"
    "            }\n"
    "            bool _137;\n"
    "            if (!_132)\n"
    "            {\n"
    "                _137 = _121.x >= 0.999000012874603271484375;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _137 = true;\n"
    "            }\n"
    "            _138 = _137;\n"
    "            break;\n"
    "        } while(false);\n"
    "        float _332;\n"
    "        if (!_138)\n"
    "        {\n"
    "            bool _148;\n"
    "            if (EdgeDetectUniforms.edge_source != 0)\n"
    "            {\n"
    "                _148 = EdgeDetectUniforms.edge_source == 2;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _148 = true;\n"
    "            }\n"
    "            float _237;\n"
    "            if (_148)\n"
    "            {\n"
    "                float _155 = -EdgeDetectUniforms.texel_size.x;\n"
    "                float4 _175 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, EdgeDetectUniforms.texel_size.y)));\n"
    "                float _176 = _175.x;\n"
    "                float _193 = -EdgeDetectUniforms.texel_size.y;\n"
    "                float4 _197 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(_155, _193)));\n"
    "                float _198 = _197.x;\n"
    "                float4 _211 = depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, _193)));\n"
    "                float _212 = _211.x;\n"
    "                float _213 = -depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(_155, EdgeDetectUniforms.texel_size.y))).x;\n"
    "                float _220 = ((((_213 - (2.0 * depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(_155, 0.0))).x)) - _198) + _176) + (2.0 * depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, 0.0))).x)) + _212;\n"
    "                float _227 = ((((_213 - (2.0 * depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(0.0, EdgeDetectUniforms.texel_size.y))).x)) - _176) + _198) + (2.0 * depth_tex.sample(depth_smp, (in.in_var_TEXCOORD0 + float2(0.0, _193))).x)) + _212;\n"
    "                _237 = precise::max(0.0, smoothstep(EdgeDetectUniforms.depth_threshold, EdgeDetectUniforms.depth_threshold * 2.0, sqrt((_220 * _220) + (_227 * _227))));\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _237 = 0.0;\n"
    "            }\n"
    "            bool _242;\n"
    "            if (EdgeDetectUniforms.edge_source != 1)\n"
    "            {\n"
    "                _242 = EdgeDetectUniforms.edge_source == 2;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _242 = true;\n"
    "            }\n"
    "            float _331;\n"
    "            if (_242)\n"
    "            {\n"
    "                float _249 = -EdgeDetectUniforms.texel_size.x;\n"
    "                float3 _270 = normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, EdgeDetectUniforms.texel_size.y))).xyz;\n"
    "                float _287 = -EdgeDetectUniforms.texel_size.y;\n"
    "                float3 _292 = normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(_249, _287))).xyz;\n"
    "                float3 _306 = normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, _287))).xyz;\n"
    "                float3 _307 = -normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(_249, EdgeDetectUniforms.texel_size.y))).xyz;\n"
    "                float3 _314 = ((((_307 - (normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(_249, 0.0))).xyz * 2.0)) - _292) + _270) + (normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(EdgeDetectUniforms.texel_size.x, 0.0))).xyz * 2.0)) + _306;\n"
    "                float3 _321 = ((((_307 - (normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(0.0, EdgeDetectUniforms.texel_size.y))).xyz * 2.0)) - _270) + _292) + (normal_tex.sample(normal_smp, (in.in_var_TEXCOORD0 + float2(0.0, _287))).xyz * 2.0)) + _306;\n"
    "                _331 = precise::max(_237, smoothstep(EdgeDetectUniforms.normal_threshold, EdgeDetectUniforms.normal_threshold * 2.0, sqrt(dot(_314, _314) + dot(_321, _321))));\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                _331 = _237;\n"
    "            }\n"
    "            _332 = _331;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _332 = 0.0;\n"
    "        }\n"
    "        _344 = float4(mix(color_tex.sample(color_smp, in.in_var_TEXCOORD0).xyz, float3(0.0), float3(_332)), 1.0);\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = _344;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int edge_detect_frag_msl_size = sizeof(edge_detect_frag_msl) - 1;
