/* Auto-generated from ghost.vert.msl -- do not edit by hand. */
static const char ghost_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GhostVertUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model_view;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_GhostVertUniforms& GhostVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    out.gl_Position = GhostVertUniforms.mvp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.out_var_TEXCOORD0 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(float4(GhostVertUniforms.model_view[0][0], GhostVertUniforms.model_view[1][0], GhostVertUniforms.model_view[2][0], GhostVertUniforms.model_view[3][0]).xyz, float4(GhostVertUniforms.model_view[0][1], GhostVertUniforms.model_view[1][1], GhostVertUniforms.model_view[2][1], GhostVertUniforms.model_view[3][1]).xyz, float4(GhostVertUniforms.model_view[0][2], GhostVertUniforms.model_view[1][2], GhostVertUniforms.model_view[2][2], GhostVertUniforms.model_view[3][2]).xyz));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int ghost_vert_msl_size = sizeof(ghost_vert_msl) - 1;
