/* Auto-generated from ghost.frag.msl -- do not edit by hand. */
static const char ghost_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GhostFragUniforms\n"
    "{\n"
    "    packed_float3 ghost_color;\n"
    "    float ghost_power;\n"
    "    float ghost_brightness;\n"
    "    packed_float3 _pad0;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GhostFragUniforms& GhostFragUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float _30 = powr(1.0 - abs(fast::normalize(in.in_var_TEXCOORD0).z), GhostFragUniforms.ghost_power);\n"
    "    out.out_var_SV_Target0 = float4((float3(GhostFragUniforms.ghost_color) * _30) * GhostFragUniforms.ghost_brightness, _30);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int ghost_frag_msl_size = sizeof(ghost_frag_msl) - 1;
