/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    packed_float3 light_dir;\n"
    "    float light_intensity;\n"
    "    packed_float3 eye_pos;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _61 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _72 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _77 = fwidth(_72);\n"
    "    float2 _80 = float2(GridFragUniforms.line_width);\n"
    "    float2 _83 = float2(1.0) - smoothstep(_80, _80 + _77, abs(fract(_72 - float2(0.5)) - float2(0.5)));\n"
    "    float _169;\n"
    "    do\n"
    "    {\n"
    "        float3 _122 = in.in_var_TEXCOORD1.xyz / float3(in.in_var_TEXCOORD1.w);\n"
    "        float2 _125 = (_122.xy * 0.5) + float2(0.5);\n"
    "        float _127 = 1.0 - _125.y;\n"
    "        float2 _128 = _125;\n"
    "        _128.y = _127;\n"
    "        float _129 = _125.x;\n"
    "        bool _134;\n"
    "        if ((isunordered(_129, 0.0) || _129 >= 0.0))\n"
    "        {\n"
    "            _134 = _129 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        bool _139;\n"
    "        if (!_134)\n"
    "        {\n"
    "            _139 = _127 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _139 = true;\n"
    "        }\n"
    "        bool _144;\n"
    "        if (!_139)\n"
    "        {\n"
    "            _144 = _127 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _144 = true;\n"
    "        }\n"
    "        if (_144)\n"
    "        {\n"
    "            _169 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _147 = _122.z;\n"
    "        float _149;\n"
    "        _149 = 0.0;\n"
    "        for (int _152 = 0; _152 < 4; )\n"
    "        {\n"
    "            _149 += float((_147 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_128 + (_61[_152] * float2(0.00048828125)))).x);\n"
    "            _152++;\n"
    "            continue;\n"
    "        }\n"
    "        _169 = _149 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4(mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3((precise::max(_83.x, _83.y) * (1.0 - smoothstep(0.300000011920928955078125, 0.5, precise::max(_77.x, _77.y)))) * (1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0 - float3(GridFragUniforms.eye_pos)))))) * (GridFragUniforms.ambient + ((precise::max(fast::normalize(-float3(GridFragUniforms.light_dir)).y, 0.0) * GridFragUniforms.light_intensity) * _169)), 1.0);\n"
    "    out.out_var_SV_Target1 = float4(fast::normalize(in.in_var_TEXCOORD2), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
