/* Auto-generated from grid.vert.msl -- do not edit by hand. */
static const char grid_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridVertUniforms\n"
    "{\n"
    "    float4x4 vp;\n"
    "    float4x4 light_vp;\n"
    "    float4x4 view;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float4 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float3 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_GridVertUniforms& GridVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _34 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = GridVertUniforms.vp * _34;\n"
    "    out.out_var_TEXCOORD0 = in.in_var_TEXCOORD0;\n"
    "    out.out_var_TEXCOORD1 = GridVertUniforms.light_vp * _34;\n"
    "    out.out_var_TEXCOORD2 = fast::normalize(float3(0.0, 1.0, 0.0) * float3x3(float4(GridVertUniforms.view[0][0], GridVertUniforms.view[1][0], GridVertUniforms.view[2][0], GridVertUniforms.view[3][0]).xyz, float4(GridVertUniforms.view[0][1], GridVertUniforms.view[1][1], GridVertUniforms.view[2][1], GridVertUniforms.view[3][1]).xyz, float4(GridVertUniforms.view[0][2], GridVertUniforms.view[1][2], GridVertUniforms.view[2][2], GridVertUniforms.view[3][2]).xyz));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_vert_msl_size = sizeof(grid_vert_msl) - 1;
