/* Auto-generated from scene.frag.msl -- do not edit by hand. */
static const char scene_frag_msl[] =
    "#pragma clang diagnostic ignored \"-Wmissing-prototypes\"\n"
    "#pragma clang diagnostic ignored \"-Wmissing-braces\"\n"
    "\n"
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "template<typename T, size_t Num>\n"
    "struct spvUnsafeArray\n"
    "{\n"
    "    T elements[Num ? Num : 1];\n"
    "    \n"
    "    thread T& operator [] (size_t pos) thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const thread T& operator [] (size_t pos) const thread\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    device T& operator [] (size_t pos) device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const device T& operator [] (size_t pos) const device\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    constexpr const constant T& operator [] (size_t pos) const constant\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    \n"
    "    threadgroup T& operator [] (size_t pos) threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup\n"
    "    {\n"
    "        return elements[pos];\n"
    "    }\n"
    "};\n"
    "\n"
    "struct type_SceneFragUniforms\n"
    "{\n"
    "    float4 base_color;\n"
    "    packed_float3 eye_pos;\n"
    "    float ambient;\n"
    "    float4 light_dir;\n"
    "    packed_float3 light_color;\n"
    "    float light_intensity;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float2 _pad0;\n"
    "};\n"
    "\n"
    "constant spvUnsafeArray<float2, 4> _59 = spvUnsafeArray<float2, 4>({ float2(-0.5), float2(0.5, -0.5), float2(-0.5, 0.5), float2(0.5) });\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target0 [[color(0)]];\n"
    "    float4 out_var_SV_Target1 [[color(1)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_SceneFragUniforms& SceneFragUniforms [[buffer(0)]], texture2d<float> shadow_tex [[texture(0)]], sampler shadow_smp [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float3 _69 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _82 = fast::normalize(-SceneFragUniforms.light_dir.xyz);\n"
    "    float _148;\n"
    "    do\n"
    "    {\n"
    "        float3 _101 = in.in_var_TEXCOORD2.xyz / float3(in.in_var_TEXCOORD2.w);\n"
    "        float2 _104 = (_101.xy * 0.5) + float2(0.5);\n"
    "        float _106 = 1.0 - _104.y;\n"
    "        float2 _107 = _104;\n"
    "        _107.y = _106;\n"
    "        float _108 = _104.x;\n"
    "        bool _113;\n"
    "        if ((isunordered(_108, 0.0) || _108 >= 0.0))\n"
    "        {\n"
    "            _113 = _108 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _113 = true;\n"
    "        }\n"
    "        bool _118;\n"
    "        if (!_113)\n"
    "        {\n"
    "            _118 = _106 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _118 = true;\n"
    "        }\n"
    "        bool _123;\n"
    "        if (!_118)\n"
    "        {\n"
    "            _123 = _106 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _123 = true;\n"
    "        }\n"
    "        if (_123)\n"
    "        {\n"
    "            _148 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _126 = _101.z;\n"
    "        float _128;\n"
    "        _128 = 0.0;\n"
    "        for (int _131 = 0; _131 < 4; )\n"
    "        {\n"
    "            _128 += float((_126 - 0.004999999888241291046142578125) <= shadow_tex.sample(shadow_smp, (_107 + (_59[_131] * float2(0.00048828125)))).x);\n"
    "            _131++;\n"
    "            continue;\n"
    "        }\n"
    "        _148 = _128 * 0.25;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target0 = float4((SceneFragUniforms.base_color.xyz * SceneFragUniforms.ambient) + (((((SceneFragUniforms.base_color.xyz * precise::max(dot(_69, _82), 0.0)) + float3(SceneFragUniforms.specular_str * powr(precise::max(dot(_69, fast::normalize(_82 + fast::normalize(float3(SceneFragUniforms.eye_pos) - in.in_var_TEXCOORD0))), 0.0), SceneFragUniforms.shininess))) * SceneFragUniforms.light_intensity) * float3(SceneFragUniforms.light_color)) * _148), SceneFragUniforms.base_color.w);\n"
    "    out.out_var_SV_Target1 = float4(fast::normalize(in.in_var_TEXCOORD3), 1.0);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_frag_msl_size = sizeof(scene_frag_msl) - 1;
