/* Auto-generated from scene.vert.msl -- do not edit by hand. */
static const char scene_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_SceneVertUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model;\n"
    "    float4x4 light_vp;\n"
    "    float4x4 model_view;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float4 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_SceneVertUniforms& SceneVertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _38 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    out.gl_Position = SceneVertUniforms.mvp * _38;\n"
    "    out.out_var_TEXCOORD0 = (SceneVertUniforms.model * _38).xyz;\n"
    "    out.out_var_TEXCOORD1 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(float4(SceneVertUniforms.model[0][0], SceneVertUniforms.model[1][0], SceneVertUniforms.model[2][0], SceneVertUniforms.model[3][0]).xyz, float4(SceneVertUniforms.model[0][1], SceneVertUniforms.model[1][1], SceneVertUniforms.model[2][1], SceneVertUniforms.model[3][1]).xyz, float4(SceneVertUniforms.model[0][2], SceneVertUniforms.model[1][2], SceneVertUniforms.model[2][2], SceneVertUniforms.model[3][2]).xyz));\n"
    "    out.out_var_TEXCOORD2 = SceneVertUniforms.light_vp * _38;\n"
    "    out.out_var_TEXCOORD3 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(float4(SceneVertUniforms.model_view[0][0], SceneVertUniforms.model_view[1][0], SceneVertUniforms.model_view[2][0], SceneVertUniforms.model_view[3][0]).xyz, float4(SceneVertUniforms.model_view[0][1], SceneVertUniforms.model_view[1][1], SceneVertUniforms.model_view[2][1], SceneVertUniforms.model_view[3][1]).xyz, float4(SceneVertUniforms.model_view[0][2], SceneVertUniforms.model_view[1][2], SceneVertUniforms.model_view[2][2], SceneVertUniforms.model_view[3][2]).xyz));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_vert_msl_size = sizeof(scene_vert_msl) - 1;
