/* Auto-generated from grid.frag.msl -- do not edit by hand. */
static const char grid_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_GridFragUniforms\n"
    "{\n"
    "    float4 line_color;\n"
    "    float4 bg_color;\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float4x4 light_vp;\n"
    "    float grid_spacing;\n"
    "    float line_width;\n"
    "    float fade_distance;\n"
    "    float ambient;\n"
    "    float shininess;\n"
    "    float specular_str;\n"
    "    float shadow_texel;\n"
    "    float _pad;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_GridFragUniforms& GridFragUniforms [[buffer(0)]], depth2d<float> shadow_map [[texture(0)]], sampler shadow_sampler [[sampler(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float2 _63 = in.in_var_TEXCOORD0.xz / float2(GridFragUniforms.grid_spacing);\n"
    "    float2 _67 = fwidth(_63);\n"
    "    float2 _75 = smoothstep(_67 * (0.5 + GridFragUniforms.line_width), _67 * (0.5 - GridFragUniforms.line_width), abs(fract(_63 + float2(0.5)) - float2(0.5)));\n"
    "    float _88 = 1.0 - smoothstep(GridFragUniforms.fade_distance * 0.5, GridFragUniforms.fade_distance, length(in.in_var_TEXCOORD0.xz - GridFragUniforms.eye_pos.xz));\n"
    "    float _89 = precise::max(_75.x, _75.y) * _88;\n"
    "    float3 _97 = mix(GridFragUniforms.bg_color.xyz, GridFragUniforms.line_color.xyz, float3(_89));\n"
    "    float _216;\n"
    "    do\n"
    "    {\n"
    "        float4 _112 = GridFragUniforms.light_vp * float4(in.in_var_TEXCOORD0, 1.0);\n"
    "        float3 _116 = _112.xyz / float3(_112.w);\n"
    "        float2 _119 = (_116.xy * 0.5) + float2(0.5);\n"
    "        float _121 = 1.0 - _119.y;\n"
    "        float2 _122 = _119;\n"
    "        _122.y = _121;\n"
    "        float _123 = _116.z;\n"
    "        float _124 = _119.x;\n"
    "        bool _129;\n"
    "        if ((isunordered(_124, 0.0) || _124 >= 0.0))\n"
    "        {\n"
    "            _129 = _124 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _129 = true;\n"
    "        }\n"
    "        bool _134;\n"
    "        if (!_129)\n"
    "        {\n"
    "            _134 = _121 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        bool _139;\n"
    "        if (!_134)\n"
    "        {\n"
    "            _139 = _121 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _139 = true;\n"
    "        }\n"
    "        bool _144;\n"
    "        if (!_139)\n"
    "        {\n"
    "            _144 = _123 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _144 = true;\n"
    "        }\n"
    "        bool _149;\n"
    "        if (!_144)\n"
    "        {\n"
    "            _149 = _123 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _149 = true;\n"
    "        }\n"
    "        if (_149)\n"
    "        {\n"
    "            _216 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _158 = _123 - 0.00200000009499490261077880859375;\n"
    "        _216 = ((((((((shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(0.0, -1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0, -1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0, 0.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _122, _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0, 0.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(-1.0, 1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(0.0, 1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_122 + (float2(1.0) * GridFragUniforms.shadow_texel)), _158, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_97 * GridFragUniforms.ambient) + (_97 * (_216 * precise::max(fast::normalize(GridFragUniforms.light_dir.xyz).y, 0.0))), precise::max(_89 * _88, (GridFragUniforms.bg_color.w * _88) * 0.5));\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int grid_frag_msl_size = sizeof(grid_frag_msl) - 1;
