/* Auto-generated from scene_raw.frag.msl -- do not edit by hand. */
static const char scene_raw_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float shadow_texel;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], depth2d<float> shadow_map [[texture(1)]], sampler diffuse_smp [[sampler(0)]], sampler shadow_sampler [[sampler(1)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _67 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    float3 _68 = fast::normalize(in.in_var_TEXCOORD1);\n"
    "    float3 _72 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _84 = _67.xyz;\n"
    "    float _201;\n"
    "    do\n"
    "    {\n"
    "        float3 _101 = in.in_var_TEXCOORD3.xyz / float3(in.in_var_TEXCOORD3.w);\n"
    "        float2 _104 = (_101.xy * 0.5) + float2(0.5);\n"
    "        float _106 = 1.0 - _104.y;\n"
    "        float2 _107 = _104;\n"
    "        _107.y = _106;\n"
    "        float _108 = _101.z;\n"
    "        float _109 = _104.x;\n"
    "        bool _114;\n"
    "        if ((isunordered(_109, 0.0) || _109 >= 0.0))\n"
    "        {\n"
    "            _114 = _109 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _114 = true;\n"
    "        }\n"
    "        bool _119;\n"
    "        if (!_114)\n"
    "        {\n"
    "            _119 = _106 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _119 = true;\n"
    "        }\n"
    "        bool _124;\n"
    "        if (!_119)\n"
    "        {\n"
    "            _124 = _106 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _124 = true;\n"
    "        }\n"
    "        bool _129;\n"
    "        if (!_124)\n"
    "        {\n"
    "            _129 = _108 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _129 = true;\n"
    "        }\n"
    "        bool _134;\n"
    "        if (!_129)\n"
    "        {\n"
    "            _134 = _108 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        if (_134)\n"
    "        {\n"
    "            _201 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _143 = _108 - 0.00200000009499490261077880859375;\n"
    "        _201 = ((((((((shadow_map.sample_compare(shadow_sampler, (_107 + (float2(-1.0) * FragUniforms.shadow_texel)), _143, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(0.0, -1.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(1.0, -1.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(-1.0, 0.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _107, _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(1.0, 0.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(-1.0, 1.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(0.0, 1.0) * FragUniforms.shadow_texel)), _143, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_107 + (float2(1.0) * FragUniforms.shadow_texel)), _143, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_84 * FragUniforms.ambient) + (((_84 * precise::max(dot(_68, _72), 0.0)) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_68, fast::normalize(_72 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess)))) * _201), _67.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_raw_frag_msl_size = sizeof(scene_raw_frag_msl) - 1;
