/* Auto-generated from scene_pipeline.frag.msl -- do not edit by hand. */
static const char scene_pipeline_frag_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_FragUniforms\n"
    "{\n"
    "    float4 light_dir;\n"
    "    float4 eye_pos;\n"
    "    float shadow_texel;\n"
    "    float shininess;\n"
    "    float ambient;\n"
    "    float specular_str;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float4 out_var_SV_Target [[color(0)]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 in_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 in_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float3 in_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float3 in_var_TEXCOORD4 [[user(locn4)]];\n"
    "    float4 in_var_TEXCOORD5 [[user(locn5)]];\n"
    "};\n"
    "\n"
    "fragment main0_out main0(main0_in in [[stage_in]], constant type_FragUniforms& FragUniforms [[buffer(0)]], texture2d<float> diffuse_tex [[texture(0)]], texture2d<float> normal_tex [[texture(1)]], depth2d<float> shadow_map [[texture(2)]], sampler diffuse_smp [[sampler(0)]], sampler normal_smp [[sampler(1)]], sampler shadow_sampler [[sampler(2)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _75 = diffuse_tex.sample(diffuse_smp, in.in_var_TEXCOORD2);\n"
    "    float4 _82 = normal_tex.sample(normal_smp, in.in_var_TEXCOORD2);\n"
    "    float3 _88 = fast::normalize(float3x3(fast::normalize(in.in_var_TEXCOORD3), fast::normalize(in.in_var_TEXCOORD4), fast::normalize(in.in_var_TEXCOORD1)) * ((_82.xyz * 2.0) - float3(1.0)));\n"
    "    float3 _92 = fast::normalize(FragUniforms.light_dir.xyz);\n"
    "    float3 _104 = _75.xyz;\n"
    "    float _221;\n"
    "    do\n"
    "    {\n"
    "        float3 _121 = in.in_var_TEXCOORD5.xyz / float3(in.in_var_TEXCOORD5.w);\n"
    "        float2 _124 = (_121.xy * 0.5) + float2(0.5);\n"
    "        float _126 = 1.0 - _124.y;\n"
    "        float2 _127 = _124;\n"
    "        _127.y = _126;\n"
    "        float _128 = _121.z;\n"
    "        float _129 = _124.x;\n"
    "        bool _134;\n"
    "        if ((isunordered(_129, 0.0) || _129 >= 0.0))\n"
    "        {\n"
    "            _134 = _129 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _134 = true;\n"
    "        }\n"
    "        bool _139;\n"
    "        if (!_134)\n"
    "        {\n"
    "            _139 = _126 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _139 = true;\n"
    "        }\n"
    "        bool _144;\n"
    "        if (!_139)\n"
    "        {\n"
    "            _144 = _126 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _144 = true;\n"
    "        }\n"
    "        bool _149;\n"
    "        if (!_144)\n"
    "        {\n"
    "            _149 = _128 < 0.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _149 = true;\n"
    "        }\n"
    "        bool _154;\n"
    "        if (!_149)\n"
    "        {\n"
    "            _154 = _128 > 1.0;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            _154 = true;\n"
    "        }\n"
    "        if (_154)\n"
    "        {\n"
    "            _221 = 1.0;\n"
    "            break;\n"
    "        }\n"
    "        float _163 = _128 - 0.00200000009499490261077880859375;\n"
    "        _221 = ((((((((shadow_map.sample_compare(shadow_sampler, (_127 + (float2(-1.0) * FragUniforms.shadow_texel)), _163, level(0.0)) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(0.0, -1.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(1.0, -1.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(-1.0, 0.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, _127, _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(1.0, 0.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(-1.0, 1.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(0.0, 1.0) * FragUniforms.shadow_texel)), _163, level(0.0))) + shadow_map.sample_compare(shadow_sampler, (_127 + (float2(1.0) * FragUniforms.shadow_texel)), _163, level(0.0))) * 0.111111111938953399658203125;\n"
    "        break;\n"
    "    } while(false);\n"
    "    out.out_var_SV_Target = float4((_104 * FragUniforms.ambient) + (((_104 * precise::max(dot(_88, _92), 0.0)) + (float3(1.0) * (FragUniforms.specular_str * powr(precise::max(dot(_88, fast::normalize(_92 + fast::normalize(FragUniforms.eye_pos.xyz - in.in_var_TEXCOORD0))), 0.0), FragUniforms.shininess)))) * _221), _75.w);\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_pipeline_frag_msl_size = sizeof(scene_pipeline_frag_msl) - 1;
