/* Auto-generated from scene_raw.vert.msl -- do not edit by hand. */
static const char scene_raw_vert_msl[] =
    "#include <metal_stdlib>\n"
    "#include <simd/simd.h>\n"
    "\n"
    "using namespace metal;\n"
    "\n"
    "struct type_VertUniforms\n"
    "{\n"
    "    float4x4 mvp;\n"
    "    float4x4 model;\n"
    "    float4x4 light_vp;\n"
    "};\n"
    "\n"
    "struct main0_out\n"
    "{\n"
    "    float3 out_var_TEXCOORD0 [[user(locn0)]];\n"
    "    float3 out_var_TEXCOORD1 [[user(locn1)]];\n"
    "    float2 out_var_TEXCOORD2 [[user(locn2)]];\n"
    "    float4 out_var_TEXCOORD3 [[user(locn3)]];\n"
    "    float4 gl_Position [[position]];\n"
    "};\n"
    "\n"
    "struct main0_in\n"
    "{\n"
    "    float3 in_var_TEXCOORD0 [[attribute(0)]];\n"
    "    float3 in_var_TEXCOORD1 [[attribute(1)]];\n"
    "    float2 in_var_TEXCOORD2 [[attribute(2)]];\n"
    "};\n"
    "\n"
    "vertex main0_out main0(main0_in in [[stage_in]], constant type_VertUniforms& VertUniforms [[buffer(0)]])\n"
    "{\n"
    "    main0_out out = {};\n"
    "    float4 _42 = float4(in.in_var_TEXCOORD0, 1.0);\n"
    "    float4 _46 = VertUniforms.model * _42;\n"
    "    out.gl_Position = VertUniforms.mvp * _42;\n"
    "    out.out_var_TEXCOORD0 = _46.xyz;\n"
    "    out.out_var_TEXCOORD1 = fast::normalize(in.in_var_TEXCOORD1 * float3x3(cross(float4(VertUniforms.model[0][1], VertUniforms.model[1][1], VertUniforms.model[2][1], VertUniforms.model[3][1]).xyz, float4(VertUniforms.model[0][2], VertUniforms.model[1][2], VertUniforms.model[2][2], VertUniforms.model[3][2]).xyz), cross(float4(VertUniforms.model[0][2], VertUniforms.model[1][2], VertUniforms.model[2][2], VertUniforms.model[3][2]).xyz, float4(VertUniforms.model[0][0], VertUniforms.model[1][0], VertUniforms.model[2][0], VertUniforms.model[3][0]).xyz), cross(float4(VertUniforms.model[0][0], VertUniforms.model[1][0], VertUniforms.model[2][0], VertUniforms.model[3][0]).xyz, float4(VertUniforms.model[0][1], VertUniforms.model[1][1], VertUniforms.model[2][1], VertUniforms.model[3][1]).xyz)));\n"
    "    out.out_var_TEXCOORD2 = in.in_var_TEXCOORD2;\n"
    "    out.out_var_TEXCOORD3 = VertUniforms.light_vp * _46;\n"
    "    return out;\n"
    "}\n"
    "\n"
;
static const unsigned int scene_raw_vert_msl_size = sizeof(scene_raw_vert_msl) - 1;
