"""Diagram functions for gpu lessons."""

__all__ = [
    "diagram_unit_circle",
    "diagram_aspect_ratio",
    "diagram_uv_mapping",
    "diagram_filtering_comparison",
    "diagram_blinn_phong_vectors",
    "diagram_specular_comparison",
    "diagram_normal_transformation",
    "diagram_fullscreen_triangle",
    "diagram_undersampling",
    "diagram_reflection_mapping",
    "diagram_cascaded_shadow_maps",
    "diagram_cascade_ortho_projections",
    "diagram_pcf_kernel",
    "diagram_peter_panning",
    "diagram_blend_modes",
    "diagram_aabb_sorting",
    "diagram_arvo_method",
    "diagram_tangent_space",
    "diagram_lengyel_tangent_basis",
    "diagram_fog_falloff_curves",
    "diagram_fog_blending",
    "diagram_fog_scene_layout",
    "diagram_hdr_pipeline",
    "diagram_ldr_clipping",
    "diagram_tone_map_comparison",
    "diagram_exposure_effect",
    "diagram_bloom_pipeline",
    "diagram_downsample_13tap",
    "diagram_tent_filter",
    "diagram_karis_averaging",
    "diagram_mip_chain_flow",
    "diagram_brightness_threshold",
    "diagram_cube_face_layout",
    "diagram_linear_vs_hardware_depth",
    "diagram_shadow_lookup",
    "diagram_atmosphere_layers",
    "diagram_density_profiles",
    "diagram_ray_sphere_intersection",
    "diagram_scattering_geometry",
    "diagram_ray_march",
    "diagram_phase_functions",
    "diagram_sun_transmittance",
    "diagram_sun_limb_darkening",
    "diagram_time_of_day_colors",
    "diagram_sky_render_pipeline",
    "diagram_ssao_render_pipeline",
    "diagram_gbuffer_mrt",
    "diagram_hemisphere_sampling",
    "diagram_kernel_distribution",
    "diagram_depth_reconstruction",
    "diagram_tbn_construction",
    "diagram_occlusion_test",
    "diagram_range_check",
    "diagram_noise_and_blur",
    "diagram_composite_modes",
    "diagram_ssr_render_pipeline",
    "diagram_ssr_ray_march",
    "diagram_ssr_gbuffer_layout",
    "diagram_ssr_self_intersection",
    "diagram_reflection_camera",
    "diagram_oblique_clip_planes",
    "diagram_frustum_plane_extraction",
    "diagram_fresnel_curve",
    "diagram_water_layers",
    "diagram_planar_render_pipeline",
    "diagram_screen_space_projection",
    "diagram_underwater_camera_guard",
    "diagram_keyframe_interpolation",
    "diagram_quaternion_slerp",
    "diagram_animation_clip_structure",
    "diagram_transform_hierarchy",
    "diagram_path_following",
    "diagram_animation_timeline",
    "diagram_forward_driven_movement",
    "diagram_arc_length_parameterization",
    "diagram_joint_matrix_pipeline",
    "diagram_skinned_normal_transform",
    "diagram_traditional_vs_pulled_pipeline",
    "diagram_storage_buffer_layout",
    "diagram_pipeline_state_comparison",
    "diagram_vertex_pulling_use_cases",
    "diagram_binding_comparison",
    "diagram_stencil_buffer_concept",
    "diagram_stencil_test_pipeline",
    "diagram_portal_technique",
    "diagram_outline_technique",
    "diagram_stencil_operations",
    "diagram_draw_order_stencil",
    "diagram_phase_ordering",
    "diagram_decal_box_projection",
    "diagram_decal_depth_reconstruction",
    "diagram_decal_local_space",
    "diagram_decal_render_pipeline",
    "diagram_back_face_culling_decals",
    "diagram_decal_layering",
    "diagram_sobel_kernels",
    "diagram_depth_vs_normal_edges",
    "diagram_edge_detection_gbuffer_layout",
    "diagram_xray_depth_fail",
    "diagram_outline_method_comparison",
    "diagram_edge_detection_pipeline",
    "diagram_color_id_picking",
    "diagram_stencil_id_picking",
    "diagram_gpu_readback_pipeline",
    "diagram_picking_method_comparison",
    "diagram_outline_selection",
    "diagram_pick_event_timing",
    "diagram_id_color_encoding",
    "diagram_indirect_draw_concept",
    "diagram_frustum_culling",
    "diagram_indirect_buffer_layout",
    "diagram_compute_to_render_pipeline",
    "diagram_split_screen_layout",
    "diagram_sphere_frustum_test",
    "diagram_asset_pipeline_flow",
    "diagram_bc7_block_compression",
    "diagram_bc5_normal_z_reconstruction",
    "diagram_fmesh_binary_layout",
    "diagram_lod_distance_selection",
    "diagram_tbn_gram_schmidt",
    "diagram_skinning_pipeline_flow",
]

from .lesson_03 import diagram_aspect_ratio, diagram_unit_circle
from .lesson_04 import diagram_filtering_comparison, diagram_uv_mapping
from .lesson_10 import (
    diagram_blinn_phong_vectors,
    diagram_normal_transformation,
    diagram_specular_comparison,
)
from .lesson_11 import diagram_fullscreen_triangle
from .lesson_12 import diagram_undersampling
from .lesson_14 import diagram_reflection_mapping
from .lesson_15 import (
    diagram_cascade_ortho_projections,
    diagram_cascaded_shadow_maps,
    diagram_pcf_kernel,
    diagram_peter_panning,
)
from .lesson_16 import diagram_aabb_sorting, diagram_arvo_method, diagram_blend_modes
from .lesson_17 import diagram_lengyel_tangent_basis, diagram_tangent_space
from .lesson_20 import (
    diagram_fog_blending,
    diagram_fog_falloff_curves,
    diagram_fog_scene_layout,
)
from .lesson_21 import (
    diagram_exposure_effect,
    diagram_hdr_pipeline,
    diagram_ldr_clipping,
    diagram_tone_map_comparison,
)
from .lesson_22 import (
    diagram_bloom_pipeline,
    diagram_brightness_threshold,
    diagram_downsample_13tap,
    diagram_karis_averaging,
    diagram_mip_chain_flow,
    diagram_tent_filter,
)
from .lesson_23 import (
    diagram_cube_face_layout,
    diagram_linear_vs_hardware_depth,
    diagram_shadow_lookup,
)
from .lesson_26 import (
    diagram_atmosphere_layers,
    diagram_density_profiles,
    diagram_phase_functions,
    diagram_ray_march,
    diagram_ray_sphere_intersection,
    diagram_scattering_geometry,
    diagram_sky_render_pipeline,
    diagram_sun_limb_darkening,
    diagram_sun_transmittance,
    diagram_time_of_day_colors,
)
from .lesson_27 import (
    diagram_composite_modes,
    diagram_depth_reconstruction,
    diagram_gbuffer_mrt,
    diagram_hemisphere_sampling,
    diagram_kernel_distribution,
    diagram_noise_and_blur,
    diagram_occlusion_test,
    diagram_range_check,
    diagram_ssao_render_pipeline,
    diagram_tbn_construction,
)
from .lesson_29 import (
    diagram_ssr_gbuffer_layout,
    diagram_ssr_ray_march,
    diagram_ssr_render_pipeline,
    diagram_ssr_self_intersection,
)
from .lesson_30 import (
    diagram_fresnel_curve,
    diagram_frustum_plane_extraction,
    diagram_oblique_clip_planes,
    diagram_planar_render_pipeline,
    diagram_reflection_camera,
    diagram_screen_space_projection,
    diagram_underwater_camera_guard,
    diagram_water_layers,
)
from .lesson_31 import (
    diagram_animation_clip_structure,
    diagram_animation_timeline,
    diagram_arc_length_parameterization,
    diagram_forward_driven_movement,
    diagram_keyframe_interpolation,
    diagram_path_following,
    diagram_quaternion_slerp,
    diagram_transform_hierarchy,
)
from .lesson_32 import diagram_joint_matrix_pipeline, diagram_skinned_normal_transform
from .lesson_33 import (
    diagram_binding_comparison,
    diagram_pipeline_state_comparison,
    diagram_storage_buffer_layout,
    diagram_traditional_vs_pulled_pipeline,
    diagram_vertex_pulling_use_cases,
)
from .lesson_34 import (
    diagram_draw_order_stencil,
    diagram_outline_technique,
    diagram_phase_ordering,
    diagram_portal_technique,
    diagram_stencil_buffer_concept,
    diagram_stencil_operations,
    diagram_stencil_test_pipeline,
)
from .lesson_35 import (
    diagram_back_face_culling_decals,
    diagram_decal_box_projection,
    diagram_decal_depth_reconstruction,
    diagram_decal_layering,
    diagram_decal_local_space,
    diagram_decal_render_pipeline,
)
from .lesson_36 import (
    diagram_depth_vs_normal_edges,
    diagram_edge_detection_gbuffer_layout,
    diagram_edge_detection_pipeline,
    diagram_outline_method_comparison,
    diagram_sobel_kernels,
    diagram_xray_depth_fail,
)
from .lesson_37 import (
    diagram_color_id_picking,
    diagram_gpu_readback_pipeline,
    diagram_id_color_encoding,
    diagram_outline_selection,
    diagram_pick_event_timing,
    diagram_picking_method_comparison,
    diagram_stencil_id_picking,
)
from .lesson_38 import (
    diagram_compute_to_render_pipeline,
    diagram_frustum_culling,
    diagram_indirect_buffer_layout,
    diagram_indirect_draw_concept,
    diagram_sphere_frustum_test,
    diagram_split_screen_layout,
)
from .lesson_39 import (
    diagram_asset_pipeline_flow,
    diagram_bc5_normal_z_reconstruction,
    diagram_bc7_block_compression,
    diagram_fmesh_binary_layout,
    diagram_lod_distance_selection,
    diagram_tbn_gram_schmidt,
)
from .lesson_43 import diagram_skinning_pipeline_flow
